### ISSUE TITLE
Video crash on Android

### ISSUE THREAD

**Issue by duongtungls** [TheWidlarzGroup/react-native-video#1061]
### Current behavior
Video component crash on Android 7.1

```
06-11 14:01:46.979 9263-9263/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: , PID: 9263
    java.lang.IllegalStateException
        at android.media.MediaPlayer.getPlaybackParams(Native Method)
        at com.brentvatne.react.ReactVideoView.setRateModifier(ReactVideoView.java:391)
        at com.brentvatne.react.ReactVideoView.applyModifiers(ReactVideoView.java:406)
        at com.brentvatne.react.ReactVideoView.onPrepared(ReactVideoView.java:447)
        at android.media.MediaPlayer$2.onPrepared(MediaPlayer.java:966)
        at com.oppo.media.OppoMediaPlayer$EventHandler.handleMessage(OppoMediaPlayer.java:2018)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:232)
        at android.app.ActivityThread.main(ActivityThread.java:6802)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

### Reproduction steps
Will hard to reproduce, on my other android device app still can work correctly. On my Oppo phone with Android 7.1 video crash on release signed APK ( work on debug APK)

### Platform
Which player are you experiencing the problem on:
* Android 7.1
* Android ExoPlayer

I can fix by add try catch into native android of library `com.brentvatne.react.ReactVideoView.setRateModifier`
```
try {
    mMediaPlayer.setPlaybackParams(mMediaPlayer.getPlaybackParams().setSpeed(rate));
} catch (Exception e) {
    e.printStackTrace();
}
```

**Comment by cobarx** [comment]
Thanks for all the info. It looks like you're actually using the Android MediaPlayer. ExoPlayer often works better, you can switch by changing `settings.gradle` to:
`project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')`

I will test this some and see if I can get it to happen. I'd rather not put a try / catch block around it without seeing if there's something we can do to prevent the error.

**Comment by cobarx** [comment]
From https://stackoverflow.com/questions/39442522/setplaybackparams-causes-illegalstateexception, there is an issue with some devices where if you don't reset the media player before setting the rate, it causes this exception. The fix is to call `reset()` on the player but that resets the player and would require a fair bit of work to figure out how to do that correctly. Given that I'm trying to deprecate MediaPlayer and push everyone to ExoPlayer, I don't want to spend the time on that.

So I've gone ahead and merged a PR that catches the exception like you suggested.
