### ISSUE TITLE
“Unfortunately, app has stopped” error

### ISSUE THREAD

**Issue by mvnnn** [TheWidlarzGroup/react-native-video#1133]
I got “Unfortunately, app has stopped” error when I integrate react-native-video on my RN project in Android. I am experiencing the problem on Android MediaPlayer

### Version
   "react": "16.4.1",
    "react-native": "0.56.0",
   "react-native-video": "^3.1.0"

**Comment by waqarmobi** [comment]
Could you run with android studio and check the logcat which exception are you getting ?

**Comment by mvnnn** [comment]
I got this error in logcat
```
07-17 17:38:10.130 5868-5908/com.videopro E/LoadTask: Unexpected exception loading stream
                                                      java.lang.ArrayIndexOutOfBoundsException: size=-387982887 offset=5322 byteCount=367
                                                          at okio.Util.checkOffsetAndCount(Util.java:30)
                                                          at okio.RealBufferedSource$1.read(RealBufferedSource.java:437)
                                                          at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.readInternal(OkHttpDataSource.java:370)
                                                          at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.read(OkHttpDataSource.java:216)
                                                          at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:152)
                                                          at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:260)
                                                          at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:61)
                                                          at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:547)
                                                          at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:522)
                                                          at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:191)
                                                          at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:853)
                                                          at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:308)
                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                          at java.lang.Thread.run(Thread.java:818)
-17 17:33:37.016 5738-5834/com.videopro E/OMXNodeInstance: setConfig(1:google.aac.decoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
07-17 17:33:37.016 5738-5834/com.videopro I/ACodec: codec does not support config priority (err -2147483648)
07-17 17:33:37.018 5738-5835/com.videopro I/SoftAAC2: limiting to stereo output
07-17 17:33:37.118 5738-5835/com.videopro I/SoftAAC2: Reconfiguring decoder: 0->48000 Hz, 0->2 channels
07-17 17:33:37.140 1234-2463/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 86016
                                                 
                                                 
                                                 [ 07-17 17:33:37.150  5738: 5830 D/         ]
                                                 HostConnection::get() New Host Connection established 0xddf05100, tid 5830
07-17 17:33:37.151 5738-5830/com.videopro A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0xdc750000 in tid 5830 (MediaCodec_loop)
07-17 17:33:37.254 1650-1650/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-17 17:33:37.254 1650-1650/? A/DEBUG: Build fingerprint: 'Android/sdk_google_phone_x86_64/generic_x86_64:6.0/MASTER/4729342:userdebug/test-keys'
07-17 17:33:37.254 1650-1650/? A/DEBUG: Revision: '0'
07-17 17:33:37.254 1650-1650/? A/DEBUG: ABI: 'x86'
07-17 17:33:37.254 1650-1650/? A/DEBUG: pid: 5738, tid: 5830, name: MediaCodec_loop  >>> com.videopro <<<
07-17 17:33:37.254 1650-1650/? A/DEBUG: signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xdc750000
07-17 17:33:37.262 1650-1650/? A/DEBUG:     eax 00014a00  ebx ea2fdeb4  ecx 00002a80  edx eabcab9c
07-17 17:33:37.262 1650-1650/? A/DEBUG:     esi db134000  edi dc750000
07-17 17:33:37.262 1650-1650/? A/DEBUG:     xcs 00000023  xds 0000002b  xes 0000002b  xfs 00000117  xss 0000002b
07-17 17:33:37.262 1650-1650/? A/DEBUG:     eip ea2f7a38  ebp 003fffc4  esp dbb3f0b4  flags 00210202
07-17 17:33:37.264 1650-1650/? A/DEBUG: backtrace:
07-17 17:33:37.264 1650-1650/? A/DEBUG:     #00 pc 00002a38  /system/lib/libOpenglSystemCommon.so (goldfish_dma_write(goldfish_dma_context*, void*, unsigned int)+56)
07-17 17:33:37.265 1650-1650/? A/DEBUG:     #01 pc 00003853  /system/lib/libOpenglSystemCommon.so (ExtendedRCEncoderContext::lockAndWriteDma(void*, unsigned int)+67)
07-17 17:33:37.265 1650-1650/? A/DEBUG:     #02 pc 00003062  /system/lib/lib_renderControl_enc.so
07-17 17:33:37.265 1650-1650/? A/DEBUG:     #03 pc 0000314e  /system/lib/hw/gralloc.ranchu.so
07-17 17:33:37.265 1650-1650/? A/DEBUG:     #04 pc 00009e67  /system/lib/libui.so (android::GraphicBufferMapper::unlock(native_handle const*)+71)
07-17 17:33:37.265 1650-1650/? A/DEBUG:     #05 pc 0012987d  /system/lib/libstagefright.so (android::SoftwareRenderer::render(void const*, unsigned int, long long, long long, void*, android::sp<android::AMessage> const&)+813)
07-17 17:33:37.265 1650-1650/? A/DEBUG:     #06 pc 000dec7e  /system/lib/libstagefright.so (android::MediaCodec::onReleaseOutputBuffer(android::sp<android::AMessage> const&)+670)
07-17 17:33:37.265 1650-1650/? A/DEBUG:     #07 pc 000da678  /system/lib/libstagefright.so (android::MediaCodec::onMessageReceived(android::sp<android::AMessage> const&)+6920)
07-17 17:33:37.265 1650-1650/? A/DEBUG:     #08 pc 0000c9b9  /system/lib/libstagefright_foundation.so (android::AHandler::deliverMessage(android::sp<android::AMessage> const&)+41)
07-17 17:33:37.265 1650-1650/? A/DEBUG:     #09 pc 00010ed2  /system/lib/libstagefright_foundation.so (android::AMessage::deliver()+114)
07-17 17:33:37.265 1650-1650/? A/DEBUG:     #10 pc 0000ddef  /system/lib/libstagefright_foundation.so (android::ALooper::loop()+463)
07-17 17:33:37.265 1650-1650/? A/DEBUG:     #11 pc 0000e7a3  /system/lib/libstagefright_foundation.so (android::ALooper::LooperThread::threadLoop()+35)
07-17 17:33:37.265 1650-1650/? A/DEBUG:     #12 pc 00014aac  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+418)
07-17 17:33:37.265 1650-1650/? A/DEBUG:     #13 pc 0006bfae  /system/lib/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+98)
07-17 17:33:37.265 1650-1650/? A/DEBUG:     #14 pc 000141cf  /system/lib/libutils.so (thread_data_t::trampoline(thread_data_t const*)+122)
07-17 17:33:37.265 1650-1650/? A/DEBUG:     #15 pc 00081953  /system/lib/libc.so (__pthread_start(void*)+56)
07-17 17:33:37.265 1650-1650/? A/DEBUG:     #16 pc 000227f2  /system/lib/libc.so (__start_thread+25)
07-17 17:33:37.265 1650-1650/? A/DEBUG:     #17 pc 000170b6  /system/lib/libc.so (__bionic_clone+70)
07-17 17:33:37.383 1650-1650/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_05
07-17 17:33:37.383 1938-5855/system_process W/ActivityManager:   Force finishing activity com.videopro/.MainActivity
07-17 17:33:37.383 1650-1650/? E/DEBUG: AM write failed: Broken pipe
07-17 17:33:37.383 1938-1955/system_process I/BootReceiver: Copying /data/tombstones/tombstone_05 to DropBox (SYSTEM_TOMBSTONE)
07-17 17:33:37.389 1234-1263/? D/gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 1019904
                                                 
                                                 
                                                 [ 07-17 17:33:37.397  1938: 5855 D/         ]
                                                 HostConnection::get() New Host Connection established 0x7fac6663de20, tid 5855
07-17 17:33:37.419 1232-1232/? E/lowmemorykiller: Error writing /proc/5738/oom_score_adj; errno=22
07-17 17:33:37.432 1938-2004/system_process W/InputDispatcher: channel '424c528 com.videopro/com.videopro.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
07-17 17:33:37.432 1938-2004/system_process E/InputDispatcher: channel '424c528 com.videopro/com.videopro.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-17 17:33:37.443 1938-2681/system_process W/MediaFocusControl:   AudioFocus   audio focus client died
07-17 17:33:37.443 1938-2681/system_process I/MediaFocusControl: AudioFocus  removeFocusStackEntry(): removing entry for android.os.BinderProxy@23b4a70
07-17 17:33:37.444 1938-2184/system_process D/GraphicsStats: Buffer count: 3
07-17 17:33:37.449 1938-2681/system_process E/MediaFocusControl: Failure to signal gain of audio focus due to: 
                                                                 android.os.DeadObjectException
                                                                     at android.os.BinderProxy.transactNative(Native Method)
                                                                     at android.os.BinderProxy.transact(Binder.java:503)
                                                                     at android.media.IAudioFocusDispatcher$Stub$Proxy.dispatchAudioFocusChange(IAudioFocusDispatcher.java:85)
                                                                     at com.android.server.audio.FocusRequester.handleFocusGain(FocusRequester.java:283)
                                                                     at com.android.server.audio.MediaFocusControl.notifyTopOfAudioFocusStack(MediaFocusControl.java:451)
                                                                     at com.android.server.audio.MediaFocusControl.removeFocusStackEntryForClient(MediaFocusControl.java:552)
                                                                     at com.android.server.audio.MediaFocusControl.-wrap7(MediaFocusControl.java)
                                                                     at com.android.server.audio.MediaFocusControl$AudioFocusDeathHandler.binderDied(MediaFocusControl.java:621)
                                                                     at android.os.BinderProxy.sendDeathNotice(Binder.java:558)
07-17 17:33:37.449 1938-2090/system_process W/MediaFocusControl:   AudioFocus   audio focus client died
07-17 17:33:37.449 1938-2090/system_process I/MediaFocusControl: AudioFocus  removeFocusStackEntry(): removing entry for android.os.BinderProxy@68d01e9
07-17 17:33:37.455 1938-2179/system_process I/WindowState: WIN DEATH: Window{424c528 u0 com.videopro/com.videopro.MainActivity}
07-17 17:33:37.455 1938-2179/system_process W/InputDispatcher: Attempted to unregister already unregistered input channel '424c528 com.videopro/com.videopro.MainActivity (server)'
07-17 17:33:37.468 1938-3749/system_process I/ActivityManager: Process com.videopro (pid 5738) has died
07-17 17:33:37.469 2543-2543/com.google.android.googlequicksearchbox:search I/BackgroundMemoryTrimmer: Trimming objects from memory, since app is in the background.
07-17 17:33:37.485 1938-4897/system_process D/EGL_emulation: eglMakeCurrent: 0x7fac66634aa0: ver 3 0 (tinfo 0x7fac64ebe040)
07-17 17:33:37.503 1938-1949/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
07-17 17:33:37.510 1938-2179/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
07-17 17:33:37.537 3751-3781/com.android.launcher3 D/EGL_emulation: eglMakeCurrent: 0x7fac769dc280: ver 3 0 (tinfo 0x7fac769ec820)
07-17 17:33:38.113 1938-1957/system_process W/WindowAnimator: Failed to dispatch window animation state change.
                                                              android.os.DeadObjectException
                                                                  at android.os.BinderProxy.transactNative(Native Method)
                                                                  at android.os.BinderProxy.transact(Binder.java:503)
                                                                  at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
                                                                  at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
                                                                  at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
                                                                  at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
                                                                  at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                  at com.android.server.ServiceThread.run(ServiceThread.java:46)
07-17 17:33:38.113 1938-1957/system_process W/WindowAnimator: Failed to dispatch window animation state change.
                                                              android.os.DeadObjectException
                                                                  at android.os.BinderProxy.transactNative(Native Method)
                                                                  at android.os.BinderProxy.transact(Binder.java:503)
                                                                  at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
                                                                  at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
                                                                  at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
                                                                  at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
                                                                  at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                  at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                  at com.android.server.ServiceThread.run(ServiceThread.java:46)
07-17 17:33:38.779 2235-2626/com.android.systemui D/EGL_emulation: eglMakeCurrent: 0x7fac7a3f8ec0: ver 3 0 (tinfo 0x7fac6e79e180)
07-17 17:33:39.651 1654-1980/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 4318876 , only wrote 4056557
```

**Comment by cobarx** [comment]
@mvnnn Thanks for sharing the stack track, it looks like the problem is an java.lang.ArrayIndexOutOfBoundsException in the ExoPlayer code itself. It's not clear exactly what's going on unfortunately, so can you post an example of the your code for loading the video.

My guess would be you are using text tracks and something is misconfigured, or ExoPlayer or your device aren't compatible with the video.

**Comment by buraksak35** [comment]
I got this error also.Please help

**Comment by cobarx** [comment]
@buraksak35 Can you provide a sample video and a snippet of the props you're passing to Video?
