### ISSUE TITLE
fails with typescript and react-test-renderer

### ISSUE THREAD

**Issue by ethanneff** [TheWidlarzGroup/react-native-video#1208]
```
    TypeError: Cannot read property 'Constants' of undefined

      at Video.render (node_modules/react-native-video/Video.js:210:59)
      at finishClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5276:31)
      at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5238:10)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5907:14)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7949:12)
      at workLoop (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7980:24)
      at renderRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8020:7)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8592:22)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8527:7)
      at performSyncWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8499:3)
```

**Comment by ethanneff** [comment]
fails here https://github.com/react-native-community/react-native-video/blob/master/Video.js#L210

**Comment by aharonamir** [comment]
Had the same problem even after link.
only after restarting the vscode and restarting the packager it was solved.
hope this helps.

**Comment by whathejoe** [comment]
@ethanneff were you able to resolve this?

Still happening to me with the ff versions:
- react-native: 0.56.0
- react-native-video: 3.2.1

**Comment by ethanneff** [comment]
```

**Comment by ethanneff** [comment]
```

**Comment by ethanneff** [comment]
I never solved it. I just mocked the entire `react-native-video` dependency with a string so I could build a snapshot off the component with a Video inside it.

```js
import React from "react";
import renderer from "react-test-renderer";
import Component from "..";

jest.mock("react-native-video", () => "Video");

describe("Video Component", () => {
  const video = require("../../../commons/Assets/Exercises/Back/intro.mp4");
  it("renders correctly", () => {
    const component = renderer.create(<Component source={video} />).toJSON();
    expect(component).toMatchSnapshot();
  });
});
```

**Comment by genkobar** [comment]
@ethanneff Did you only encounter this when doing snapshot tests, or also when you were running the app proper?

I ask because the Jest documentation notes that when doing snapshot tests of anything that makes use of native code, you need to mock it (like you've done here) because Jest can't run native code.

> However some react-native components or third party components rely on native code to be rendered. In such cases, Jest's manual mocking system can help to mock out the underlying implementation. [#](https://jestjs.io/docs/en/tutorial-react-native#mock-native-modules-using-jestmock)

Well, it doesn't state it directly, but this is the only part of the documentation that talks about components that rely on native code.
