### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/trackselection/MappingTrackSelector$SelectionOverride

### ISSUE THREAD

**Issue by yoyo001** [TheWidlarzGroup/react-native-video#1256]
### Current behavior
version react-native-video @3.2.1;   app crash when video load completed;  it looks for a class that not available on latest exoplayer2;  
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/trackselection/MappingTrackSelector$SelectionOverride;
        at com.brentvatne.exoplayer.ReactExoplayerView.setSelectedTrack(ReactExoplayerView.java:823)
        at com.brentvatne.exoplayer.ReactExoplayerView.setSelectedAudioTrack(ReactExoplayerView.java:851)
        at com.brentvatne.exoplayer.ReactExoplayerView.videoLoaded(ReactExoplayerView.java:514)
        at com.brentvatne.exoplayer.ReactExoplayerView.onPlayerStateChanged(ReactExoplayerView.java:493)
        at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.notifyListeners(ExoPlayerImpl.java:769)
        at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:681)
        at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:622)
        at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:567)
        at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:109)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

from the auto-generate iml file, i could see it refer to 
  com.google.android.exoplayer:exoplayer-hls-2.8.4
    com.google.android.exoplayer:exoplayer-core-2.8.4

shouldn't it refer to 2.7.3?   any idea ?

### Reproduction steps
always

### Expected behavior
no crash

### Platform
* Android ExoPlayer

### Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by yoyo001** [comment]
my fault,  another module introduce that, just close

**Comment by SamiChab** [comment]
@yoyo001 Can you explain how you solved this?
