### ISSUE TITLE
ANDROID: Audio don't play after a while: Caused by AudioTrack init failed: 0 error

### ISSUE THREAD

**Issue by matamicen** [TheWidlarzGroup/react-native-video#1265]
Hi everybody,

We load 3 .mp4 audios from the cloud (https) in a FlatList  and everything is Ok, then we reload another 3 files to the same screen, it works Ok, after 3 or 4 times doing the same the audios don't play anymore.

react-native-video: 3.2.1
Phone: Android 7.0 J7 (Physical phone) 
 react-native: "0.56.0"

Any idea? 

Thanks!!

This is the log that throw when the audio don't play anymore:

```
 selectOutput() commonFlags for output 13, 0000
    selectOutput() commonFlags for output 21, 0000
10-06 19:02:22.565 2480-27194/? V/APM_AudioPolicyManager: getOutputForAttr() usage=1, content=0, tag= flags=00000200 session 6385 selectedDeviceId 0
10-06 19:02:22.565 2480-27194/? D/APM::SoundKitchen: getDevice, uid = 10234, device = 0
10-06 19:02:22.565 2480-27194/? V/APM_AudioPolicyManager: getOutputForAttr() device 0x2, samplingRate 22050, format 1, channelMask 1, flags 8
    selectOutput() commonFlags for output 13, 0001
      getOutputForAttr() returns output 13 selectedDeviceId 2
10-06 19:02:22.566 2480-2737/? E/AudioFlinger: no more track names available
    createTrack_l() initCheck failed -12; no control block?
10-06 19:02:22.567 31782-13716/com.sqsonative E/AudioTrack: AudioFlinger could not create track, status: -12
10-06 19:02:22.567 2480-2655/? V/APM_AudioPolicyManager: releaseOutput() 13
10-06 19:02:22.567 31782-13716/com.sqsonative E/AudioTrack-JNI: Error -12 initializing AudioTrack
10-06 19:02:22.567 31782-13716/com.sqsonative E/android.media.AudioTrack: Error code -20 when initializing AudioTrack.
10-06 19:02:22.570 31782-13716/com.sqsonative E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:467)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1068)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:567)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed: 0, Config(22050, 4, 14240)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:1220)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.initialize(DefaultAudioSink.java:517)
        at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:574)
        at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:461)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1068) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:567) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
10-06 19:02:22.571 31782-17636/com.sqsonative I/ACodec: [OMX.google.aac.decoder] Now Executing->Idle
10-06 19:02:22.573 31782-17636/com.sqsonative I/ACodec: [OMX.google.aac.decoder] Now Idle->Loaded
    [OMX.google.aac.decoder] Now Loaded
     [OMX.google.aac.decoder] Now kWhatShutdownCompleted event : 8526

```

**Comment by matamicen** [comment]
Solved.
It was an “out of memory” problem, we switch to exoplayer and the problem was the same.
We have  to take out of render the <Video> component with each audio, so when the user press the play button we render the video component to buffer the audio and Start playing and when the audio finish in the Onend event we take out the video component in orden to exoplyaer Release the memory.

Thanks.
