### ISSUE TITLE
Android Crash On Load

### ISSUE THREAD

**Issue by vurteaushane** [TheWidlarzGroup/react-native-video#1398]
### Current behavior
App crashes with error:

java.lang.BootstrapMethodError: Exception from call site #20 bootstrap method
        at com.google.android.exoplayer2.util.SlidingPercentile.<clinit>(SlidingPercentile.java:38)
        at com.google.android.exoplayer2.upstream.DefaultBandwidthMeter.<init>(DefaultBandwidthMeter.java:263)
        at com.google.android.exoplayer2.upstream.DefaultBandwidthMeter.<init>(DefaultBandwidthMeter.java:240)
        at com.brentvatne.exoplayer.ReactExoplayerView.<clinit>(ReactExoplayerView.java:85)
        at com.brentvatne.exoplayer.ReactExoplayerViewManager.createViewInstance(ReactExoplayerViewManager.java:64)
        at com.brentvatne.exoplayer.ReactExoplayerViewManager.createViewInstance(ReactExoplayerViewManager.java:22)
        at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:42)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:260)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:200)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1085)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1056)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:693)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

### Reproduction steps
Load screen with <Video> component

### Expected behavior
Screen load, play video

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

**Comment by chistaesse** [comment]
Same issue here, only with ExoPlayer not with Android MediaPlayer.

**Comment by gramound** [comment]
SlidingPercentile is the first place where the app encounters a lambda expression (while creating an ExoPlayer instance with DefaultBandwidthMeter). lambda expressions require Java 8 support.

As per the ExoPlayer developer guide:
[https://google.github.io/ExoPlayer/guide.html](url)
You need to turn on Java 8 support in all build.gradle files depending on ExoPlayer, by adding the following to the android section:
`compileOptions {
    targetCompatibility JavaVersion.VERSION_1_8
}`
