### ISSUE TITLE
FATAL EXCEPTION: main java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by retyui** [TheWidlarzGroup/react-native-video#1408]
### Current behavior
Application always crash: 
```
I/ACodec:  [] Now uninitialized
I/ACodec: [] onAllocateComponent
I/OMXClient: IOmx service obtained
I/ACodec: [OMX.SEC.mp3.dec] Now Loaded
I/ACodec: [HW_HDR] app-pid : 27260
          >>>UHQA ACodec::configureCodec : 0, 15000000
I/ACodec: [OMX.SEC.mp3.dec] Now Loaded->Idle
I/ACodec: [OMX.SEC.mp3.dec] Now Idle->Executing
I/ACodec: [OMX.SEC.mp3.dec] Now Executing
I/AudioTrack: updateAudioTranstionLength FadeIn[0] FadeOut[0] FadeInRing[0]
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.kykysiki.boom, PID: 27260
                  java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                      at com.google.android.exoplayer2.source.TrackGroupArray.get(TrackGroupArray.java:65)
                      at com.brentvatne.exoplayer.ReactExoplayerView.setSelectedTrack(ReactExoplayerView.java:892)
                      at com.brentvatne.exoplayer.ReactExoplayerView.setSelectedVideoTrack(ReactExoplayerView.java:934)
                      at com.brentvatne.exoplayer.ReactExoplayerView.videoLoaded(ReactExoplayerView.java:541)
                      at com.brentvatne.exoplayer.ReactExoplayerView.onPlayerStateChanged(ReactExoplayerView.java:519)
                      at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.notifyListeners(ExoPlayerImpl.java:803)
                      at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:717)
                      at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:648)
                      at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:593)
                      at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:125)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:214)
                      at android.app.ActivityThread.main(ActivityThread.java:6981)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
W/m.kykysiki.boo: JNI critical lock held for 18.185ms on Thread[48,tid=27489,Runnable,Thread*=0xce858200,peer=0x13780000,"mqt_js"]
D/FA: Logging event (FE): app_exception(_ae), Bundle[{firebase_event_origin(_o)=clx, _r=1, firebase_screen_class(_sc)=MainActivity, firebase_screen_id(_si)=-4548895484062320314, timestamp=1546389906421, fatal=1}]
W/CrashlyticsCore: Cannot send reports. Settings are unavailable.
I/Process: Sending signal. PID: 27260 SIG: 9
Application terminated.
```

### Reproduction steps
When rendering this:
```
<Video
              source={{uri:`https://cs9-9v4.vkuseraudio.net/p4/345b7446fbf535.mp3?extra=CndPePNSunl4haBie5D_MvZ1VgLVObvUKYYHBwFFq7IzYbsp07F0dBoX2WvF0Ml7lO2fqi3Z-tk-aK5X-sIa2k_OO25mGoBrQfLb6qk8ClM-Py2eftxQwmO9pxnN0hBpNuqCR0ICINV_ErBzMpjbHRxgYsc8`}}
            />
```

### Expected behavior
The player will play audio

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

### React Native Environment Info:
```
    System:
      OS: Linux 4.15 Linux Mint 18.3 (Sylvia)
      CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
      Memory: 166.01 MB / 15.55 GB
      Shell: 2.7.1 - /usr/bin/fish
    Binaries:
      Node: 10.15.0 - /usr/bin/node
      Yarn: 1.12.3 - ~/.yarn/bin/yarn
      npm: 6.4.1 - /usr/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64
    npmPackages:
      react: ^16.7.0 => 16.7.0 
      react-native: 0.57.1 => 0.57.1 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by cobarx** [comment]
Shoot I'm guessing the video track selection code in 4.3.0 doesn't handle media with no video tracks. I'll fix this shortly. Thanks for reporting the issue.

**Comment by saad9624-tribalScale** [comment]
Still getting the same crash on react native video very intermittently
version is 5.2.0
@cobarx
