### ISSUE TITLE
Audio not playing on Android (v 4.3.1)

### ISSUE THREAD

**Issue by jmrhvl** [TheWidlarzGroup/react-native-video#1417]
### Current behavior
Video plays fine, but audio files (mp3, m4a) produces the following error:

`
E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
        at com.google.android.exoplayer2.source.TrackGroupArray.get(TrackGroupArray.java:65)
        at com.google.android.exoplayer2.trackselection.DefaultTrackSelector.selectTracks(DefaultTrackSelector.java:1264)
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:394)
        at com.google.android.exoplayer2.MediaPeriodHolder.selectTracks(MediaPeriodHolder.java:160)
        at com.google.android.exoplayer2.MediaPeriodHolder.handlePrepared(MediaPeriodHolder.java:141)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:1549)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:318)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
`

### Reproduction steps
Try to play back mp3 or m4a files.

### Expected behavior
The audio would start playing.

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

### Video sample
https://telavaag.sfnm.build/en/post4intro.mp3

RN is at version 0.57.8.

Edit: This might be related to #1408, but the error message is not 100% the same and version 4.3.1 seems to have that fix.

Also, before the error previously mentioned I see these in LogCat:

`
I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
I/OMXClient: MuxOMX ctor
I/ACodec: codec does not support config priority (err -2147483648)
`

**Comment by supagu** [comment]
I have the same problem 4.2.0 works
I think this is the same bug as mentioned in the description.

**Comment by dkoo761** [comment]
+1, downgrading to 4.2.0 until this is fixed. I don't see any errors in the logs but my MP3s don't start playing at all, they just get stuck at time=0.

**Comment by kesha-antonov** [comment]
Same here with Android
iOS is ok
