### ISSUE TITLE
Trying to play videos from dropbox on Android, works fine on iOS

### ISSUE THREAD

**Issue by skeie** [TheWidlarzGroup/react-native-video#1453]
### Current behavior
Hey,

When we're trying to play movies from dropbox
I.E `https://www.dropbox.com/sh/eu0jqrwe3a3djra/AAC78do99os-RSRQzqJvLBpca/Male%20Updated%20Cues/Walking%20Lunges.mp4?raw=1`
(We need to add raw=1 in order to force-render the video, more info here: https://www.dropbox.com/help/desktop-web/force-download)

using this link works fine on iOS, but on Android we get

```
 { errorException: 'com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [3840, 2160, -1.0], [-1, -1])',
                                                                errorString: 'Unable to instantiate decoder OMX.qcom.video.decoder.avc' } }
```

### Reproduction steps
A 1, 2, 3, etc. list of what's needed to see the issue happen.
Try to render this
```
<RNVideo
          source={{
            uri:
              'https://www.dropbox.com/sh/eu0jqrwe3a3djra/AAC78do99os-RSRQzqJvLBpca/Male%20Updated%20Cues/Walking%20Lunges.mp4?raw=1',
          }}
          controls
          style={StyleSheet.absoluteFill}
            console.log('error', error);
          }}
/>
```

### Expected behavior
Would be great if the movie could be played as on iOS :)

### Platform
Which player are you experiencing the problem on:
* Android ExoPlayer

Full logs
```
 E/ExoPlayerImplInternal: Playback error.
                                                                   com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [3840, 2160, -1.0], [-1, -1])
                                                                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
                                                                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
                                                                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
                                                                       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
                                                                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
                                                                       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
                                                                       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                    Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [3840, 2160, -1.0], [-1, -1])
                                                                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
                                                                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
                                                                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
                                                                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
                                                                       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552) 
                                                                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
                                                                       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
                                                                       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                       at android.os.Looper.loop(Looper.java:154) 
                                                                       at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                    Caused by: android.media.MediaCodec$CodecException: Error 0xfffffc0e
                                                                       at android.media.MediaCodec.native_configure(Native Method)
                                                                       at android.media.MediaCodec.configure(MediaCodec.java:1892)
                                                                       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:483)
                                                                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:805)
                                                                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
                                                                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474) 
                                                                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261) 
                                                                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111) 
                                                                       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552) 
                                                                       at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647) 
                                                                       at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536) 
                                                                       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                       at android.os.Looper.loop(Looper.java:154) 
                                                                       at android.os.HandlerThread.run(HandlerThread.java:61) 
 I/ReactNativeJS: 'error', { error: 
                                                              { errorException: 'com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [3840, 2160, -1.0], [-1, -1])',
                                                                errorString: 'Unable to instantiate decoder OMX.qcom.video.decoder.avc' } }
```

**Comment by jaspervanbrian** [comment]
Same issue here. Does this issue have any workaround?

**Comment by ForestChong** [comment]
same issues here

**Comment by mkgdev** [comment]
Same issue here too

**Comment by stevieoj** [comment]
Same here

**Comment by ramon90** [comment]
I have been trying to debug for several days without any success :(

**Comment by OmarBasem** [comment]
I am facing the same issue, but for any video i try to play, whether local or remote, It happens at random, sometimes the video plays some times and does not and throws that error. I have been trying to debug it for several days without any success.

**Comment by OmarBasem** [comment]
Why no one looks into the issues in this package, I see 500+ open issues!

**Comment by OmarBasem** [comment]
Is this the only video package for react-native? (all others are based on this package)

**Comment by jaspervanbrian** [comment]
Often people face this issue, but I realized I was playing too videos on the screen. You must only render one video at a time.

Tip: Replace your other videos as image thumbnails

**Comment by OmarBasem** [comment]
@jaspervanbrian THANK YOU so much for this! But, this causes flickering on the screen as the component is rerendered from Image to Video, do you know any workarounds to avoid this happening?

**Comment by jaspervanbrian** [comment]
@ramon90 render your videos as image tag, then when clicked you can switch to another screen, or use a separate video player. If I'm not mistaken, I used https://github.com/itsnubix/react-native-video-controls back on my project as a video player

**Comment by OmarBasem** [comment]
@jaspervanbrian yeah that's what i did, although that's not optimal, but it works for now. Hope the ExoPlayer gets fixed for android in the future. Thank You!

**Comment by CHaNGeTe** [comment]
https://github.com/react-native-community/react-native-video/issues/1453#issuecomment-510643479

Version 4.4.4 comes with improvements on multiple video handling for exoplayer. Can you try this version?

**Comment by OmarBasem** [comment]
@CHaNGeTe I did try it and it did not fix it. Still throws the same error and fails to load & play.

**Comment by yayanartha** [comment]
Yes, I also experienced the same, it's still not work on v4.4.4.
