### ISSUE TITLE
[OMX.qcom.video.decoder.avc] ERROR(0x80001000) / No Conent Provider - FileNotFound

### ISSUE THREAD

**Issue by ezranbayantemur** [TheWidlarzGroup/react-native-video#1752]
This issue might not about this library but I getting that error when I try to fetch "a" video.

If I put "https://vjs.zencdn.net/v/oceans.mp4"  on uri it works fine, but when I try our API (PHP/Laravel API) link "https://www.medicres.club/app/v/2a549d75fa33f54a.mp4" it gives logcat error on the below which is Exoplayer. On Android default media player it says "No Content Provider, file not found"

But it works fine on iOS side. The error only occurs Android side. Should I give any permission or something? 

```
2019-09-16 18:09:23.966 1919-1919/com.testmedic I/ExoPlayerImpl: Init 34e7cbd [ExoPlayerLib/2.9.3] [gm4g_sprout, General Mobile 4G Dual, General Mobile, 25]
2019-09-16 18:09:23.972 1919-1919/com.testmedic D/ReactExoplayerView: onStateChanged: playWhenReady=false, playbackState=buffering
2019-09-16 18:09:24.321 1919-2478/com.testmedic I/OMXClient: MuxOMX ctor
2019-09-16 18:09:24.346 1919-2477/com.testmedic I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 1965065
2019-09-16 18:09:24.354 1919-1925/com.testmedic I/art: Do partial code cache collection, code=121KB, data=123KB
2019-09-16 18:09:24.356 1919-1925/com.testmedic I/art: After code cache collection, code=120KB, data=122KB
2019-09-16 18:09:24.356 1919-1925/com.testmedic I/art: Increasing code cache capacity to 512KB
2019-09-16 18:09:24.370 1919-2478/com.testmedic D/SurfaceUtils: set up nativeWindow 0x8ecac808 for 1920x1080, color 0x7fa30c04, rotation 90, usage 0x42002900
2019-09-16 18:09:24.388 1919-2482/com.testmedic I/OMXClient: MuxOMX ctor
2019-09-16 18:09:24.390 1919-2478/com.testmedic E/ACodec: [OMX.qcom.video.decoder.avc] ERROR(0x80001000)
2019-09-16 18:09:24.391 1919-2478/com.testmedic E/ACodec: signalError(omxError 0x80001000, internalError -2147483648)
2019-09-16 18:09:24.391 1919-2477/com.testmedic E/MediaCodec: Codec reported err 0x80001000, actionCode 0, while in state 6
2019-09-16 18:09:24.399 1919-2482/com.testmedic I/ACodec: codec does not support config priority (err -2147483648)
2019-09-16 18:09:24.399 1919-2482/com.testmedic I/ACodec: codec does not support config operating rate (err -2147483648)
2019-09-16 18:09:24.412 1919-2472/com.testmedic E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2570)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1287)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:663)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
2019-09-16 18:09:24.416 1919-2478/com.testmedic E/Surface: getSlotFromBufferLocked: unknown buffer: 0x807521e0
2019-09-16 18:09:24.416 1919-2478/com.testmedic W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 15 to native window
2019-09-16 18:09:24.417 1919-2478/com.testmedic E/Surface: getSlotFromBufferLocked: unknown buffer: 0x80752300
2019-09-16 18:09:24.417 1919-2478/com.testmedic W/ACodec: [OMX.qcom.video.decoder.avc] can not return buffer 14 to native window
2019-09-16 18:09:24.428 1919-2472/com.testmedic E/ExoPlayerImplInternal: Stop failed.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2007)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:608)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:508)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:562)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:377)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:153)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:983)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:771)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:742)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:358)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
2019-09-16 18:09:24.439 1919-1919/com.testmedic D/ReactExoplayerView: onStateChanged: playWhenReady=false, playbackState=idle
```

[Header of problem link](https://eksiup.com/p/eh111416qziu)
[Header of working link](https://eksiup.com/p/o5111418gc3f)

**Comment by ezranbayantemur** [comment]
@CHaNGeTe @cobarx

**Comment by ntkzwane** [comment]
Started experiencing this after upgrading to RN `v0.62.0` - the same "No Content Provider, file not found" error. Similarly, not for all videos, works fine for this test video http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4, but no longer for videos hosted on a DigitalOcean bucket (the same video worked fine on the previous version of RN for me)
