### ISSUE TITLE
DASH(mpd) or HLS(m3u8) adaptive bitrate videos not getting played on IOS and Android

### ISSUE THREAD

**Issue by s4kh** [TheWidlarzGroup/react-native-video#1818]
# Bug
Install the dependency `react-native-video`
Did not run the `react-native link react-native-video` because react-native above 0.60 says you don't need to run it gets auto-linked. It also does not work even though you run the link command
```
<Video
  ref={player}
  source={{
    uri:
      'https://d1uiedghhy643m.cloudfront.net/raw-vids/IELTS-Writing.mpd',
    type: 'mpd',
  }}
  resizeMode="contain"
  onError={onError}
  onVideoError={onError}
  style={styles.mediaPlayer}
/>
```

## Platform
Which player are you experiencing the problem on:
* iOS
* Android ExoPlayer
* Android MediaPlayer

## Environment info
```
"dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.4",
    "react-native-video": "^5.0.2"
  }
```

React native info output:

Library version: 0.61.4

`onError` callback gives `{error:{also some number, what:-1}}`

## Expected behaviour

1. Play the video and change the quality depending on bandwidth of the user

## Video sample
Videos on CloudFront
https://d1uiedghhy643m.cloudfront.net/transcoded-vids/IELTS-Writing.mpd
https://d1uiedghhy643m.cloudfront.net/transcoded-vids/IELTS-Writing.m3u8

**Comment by slhck** [comment]
Same issue here the same cryptic error. Did you find any solution yet?

**Comment by s4kh** [comment]
Mine is actually working. First of all, you have to create config file for linking exoplayer for android. Check with stream tester on like bitmovin and jwplayer. If says network error downloading that means cloudfront config is wrong.

**Comment by slhck** [comment]
"create config file for linking exoplayer for android" – why, or what exactly do you mean by that?

Note that in my case the player runs fine if used with MP4 sources (progressive), but not with MPD manifest URLs. I'm not seeing any network errors.

**Comment by s4kh** [comment]
For react-native autolinking we need to say that it will use exoplayer. Save this in your root folder of your project. https://github.com/react-native-community/react-native-video/issues/1746

```
module.exports = {
  dependencies: {
    'react-native-video': {
      platforms: {
        android: {
          sourceDir: '../node_modules/react-native-video/android-exoplayer',
        },
      },
    },
  },
};
```

**Comment by s4kh** [comment]
https://bitmovin.com/demos/stream-test test your mpd urls with the player and if it does not work that means your cdn or server is restricting access to it.

**Comment by slhck** [comment]
I'll try the autolinking, but as said, the ExoPlayer itself works, so I guess it's not that.

And I'm using exactly the MPD that is the default in the stream test :smile:

**Comment by slhck** [comment]
Okay, I added the file as you suggested. I think I ran into the same issue as you linekd to (#1746).

Now I'm getting the following error, which seems to be caused by the Android project using a newer version of ExoPlayer (2.9.3) than the one that `react-native-video` bundles...

```
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx: Rejecting re-init on previously-failed class java.lang.Class<com.brentvatne.exoplayer.ReactExoplayerView>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/ExoPlayer$EventListener;
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at java.util.List com.brentvatne.react.ReactVideoPackage.createViewManagers(com.facebook.react.bridge.ReactApplicationContext) (ReactVideoPackage.java:28)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at java.util.List com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(com.facebook.react.bridge.ReactApplicationContext) (ReactInstanceManager.java:782)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at com.facebook.react.uimanager.UIManagerModule com.facebook.react.CoreModulesPackage.createUIManager(com.facebook.react.bridge.ReactApplicationContext) (CoreModulesPackage.java:184)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at com.facebook.react.bridge.NativeModule com.facebook.react.CoreModulesPackage.getModule(java.lang.String, com.facebook.react.bridge.ReactApplicationContext) (CoreModulesPackage.java:152)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at com.facebook.react.bridge.NativeModule com.facebook.react.TurboReactPackage$ModuleHolderProvider.get() (TurboReactPackage.java:122)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at java.lang.Object com.facebook.react.TurboReactPackage$ModuleHolderProvider.get() (TurboReactPackage.java:110)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at com.facebook.react.bridge.NativeModule com.facebook.react.bridge.ModuleHolder.create() (ModuleHolder.java:188)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at com.facebook.react.bridge.NativeModule com.facebook.react.bridge.ModuleHolder.getModule() (ModuleHolder.java:153)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at com.facebook.react.bridge.NativeModule com.facebook.react.bridge.NativeModuleRegistry.getModule(java.lang.String) (NativeModuleRegistry.java:148)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at com.facebook.react.bridge.NativeModule com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(java.lang.String) (CatalystInstanceImpl.java:479)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at com.facebook.react.bridge.NativeModule com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(java.lang.Class) (CatalystInstanceImpl.java:466)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at com.facebook.react.bridge.UIManager com.facebook.react.uimanager.UIManagerHelper.getUIManager(com.facebook.react.bridge.ReactContext, int) (UIManagerHelper.java:31)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at void com.facebook.react.ReactInstanceManager.attachRootViewToInstance(com.facebook.react.uimanager.ReactRoot) (ReactInstanceManager.java:1054)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at void com.facebook.react.ReactInstanceManager.setupReactContext(com.facebook.react.bridge.ReactApplicationContext) (ReactInstanceManager.java:1012)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at void com.facebook.react.ReactInstanceManager.access$1400(com.facebook.react.ReactInstanceManager, com.facebook.react.bridge.ReactApplicationContext) (ReactInstanceManager.java:125)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at void com.facebook.react.ReactInstanceManager$5$2.run() (ReactInstanceManager.java:972)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:873)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at void com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(android.os.Message) (MessageQueueThreadHandler.java:26)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at void android.os.Looper.loop() (Looper.java:193)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at void com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run() (MessageQueueThreadImpl.java:225)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at void java.lang.Thread.run() (Thread.java:764)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.ExoPlayer$EventListener" on path: DexPathList[[zip file "/data/app/com.surxxxxxxxxxxxxxxe-kKBs2oDTCO0HeuPs2KcNHA==/base.apk"],nativeLibraryDirectories=[/data/app/com.surxxxxxxxxxxxxxxe-kKBs2oDTCO0HeuPs2KcNHA==/lib/x86, /data/app/com.surxxxxxxxxxxxxxxe-kKBs2oDTCO0HeuPs2KcNHA==/base.apk!/lib/x86, /system/lib]]
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at java.util.List com.brentvatne.react.ReactVideoPackage.createViewManagers(com.facebook.react.bridge.ReactApplicationContext) (ReactVideoPackage.java:28)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at java.util.List com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(com.facebook.react.bridge.ReactApplicationContext) (ReactInstanceManager.java:782)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at com.facebook.react.uimanager.UIManagerModule com.facebook.react.CoreModulesPackage.createUIManager(com.facebook.react.bridge.ReactApplicationContext) (CoreModulesPackage.java:184)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at com.facebook.react.bridge.NativeModule com.facebook.react.CoreModulesPackage.getModule(java.lang.String, com.facebook.react.bridge.ReactApplicationContext) (CoreModulesPackage.java:152)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at com.facebook.react.bridge.NativeModule com.facebook.react.TurboReactPackage$ModuleHolderProvider.get() (TurboReactPackage.java:122)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at java.lang.Object com.facebook.react.TurboReactPackage$ModuleHolderProvider.get() (TurboReactPackage.java:110)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at com.facebook.react.bridge.NativeModule com.facebook.react.bridge.ModuleHolder.create() (ModuleHolder.java:188)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at com.facebook.react.bridge.NativeModule com.facebook.react.bridge.ModuleHolder.getModule() (ModuleHolder.java:153)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at com.facebook.react.bridge.NativeModule com.facebook.react.bridge.NativeModuleRegistry.getModule(java.lang.String) (NativeModuleRegistry.java:148)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at com.facebook.react.bridge.NativeModule com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(java.lang.String) (CatalystInstanceImpl.java:479)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at com.facebook.react.bridge.NativeModule com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(java.lang.Class) (CatalystInstanceImpl.java:466)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at com.facebook.react.bridge.UIManager com.facebook.react.uimanager.UIManagerHelper.getUIManager(com.facebook.react.bridge.ReactContext, int) (UIManagerHelper.java:31)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at void com.facebook.react.ReactInstanceManager.attachRootViewToInstance(com.facebook.react.uimanager.ReactRoot) (ReactInstanceManager.java:1054)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at void com.facebook.react.ReactInstanceManager.setupReactContext(com.facebook.react.bridge.ReactApplicationContext) (ReactInstanceManager.java:1012)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at void com.facebook.react.ReactInstanceManager.access$1400(com.facebook.react.ReactInstanceManager, com.facebook.react.bridge.ReactApplicationContext) (ReactInstanceManager.java:125)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at void com.facebook.react.ReactInstanceManager$5$2.run() (ReactInstanceManager.java:972)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:873)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at void com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(android.os.Message) (MessageQueueThreadHandler.java:26)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at void android.os.Looper.loop() (Looper.java:193)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at void com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run() (MessageQueueThreadImpl.java:225)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx:   at void java.lang.Thread.run() (Thread.java:764)
11-26 17:21:08.940 11566 11602 I xxxxxxxxxxxxxx: 
11-26 17:21:08.941 11566 11602 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
11-26 17:21:08.941 11566 11602 E AndroidRuntime: Process: com.surxxxxxxxxxxxxxxe, PID: 11566
11-26 17:21:08.941 11566 11602 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/ExoPlayer$EventListener;
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at com.brentvatne.react.ReactVideoPackage.createViewManagers(ReactVideoPackage.java:28)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:782)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:184)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:152)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:122)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:110)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:188)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:153)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:148)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:479)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:466)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:31)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1054)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1012)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at com.facebook.react.ReactInstanceManager.access$1400(ReactInstanceManager.java:125)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:972)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:873)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:99)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:193)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at java.lang.Thread.run(Thread.java:764)
11-26 17:21:08.941 11566 11602 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.ExoPlayer$EventListener" on path: DexPathList[[zip file "/data/app/com.surxxxxxxxxxxxxxxe-kKBs2oDTCO0HeuPs2KcNHA==/base.apk"],nativeLibraryDirectories=[/data/app/com.surxxxxxxxxxxxxxxe-kKBs2oDTCO0HeuPs2KcNHA==/lib/x86, /data/app/com.surxxxxxxxxxxxxxxe-kKBs2oDTCO0HeuPs2KcNHA==/base.apk!/lib/x86, /system/lib]]
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
11-26 17:21:08.941 11566 11602 E AndroidRuntime:    ... 22 more
```

**Comment by diego-miranda-ng** [comment]
I am having this error after upgrading to React Native 0.63.2. I've been trying to start the project for two days, but the application always closes with this problem.
I've tried several suggestions on the web and nothing works. I'm out of alternatives.

**Comment by baselbj** [comment]
> I am having this error after upgrading to React Native 0.63.2. I've been trying to start the project for two days, but the application always closes with this problem.
> I've tried several suggestions on the web and nothing works. I'm out of alternatives.

Did you solve it?

**Comment by rzinnatullin** [comment]
Is DASH (mpd) supported for iOS implementation at all?

**Comment by hannojg** [comment]
@rzinnatullin no, it currently isn't. This lib uses `AVPlayer`, which doesn't support dash streaming. This is due to this fact that apple requires app developers to use HLS streaming for video streamings longer than 10 minutes (I lost the reference to the documentation).

**Comment by ngima** [comment]
> @rzinnatullin no, it currently isn't. This lib uses `AVPlayer`, which doesn't support dash streaming. This is due to this fact that apple requires app developers to use HLS streaming for video streamings longer than 10 minutes (I lost the reference to the documentation).

Thanks @rzinnatullin really saved my time

Found the reference to the documentation mentioning it: https://developer.apple.com/app-store/review/guidelines/#media-content

![image](https://user-images.githubusercontent.com/23276565/204705210-a74d5193-7309-424f-aae9-569159cc6df4.png)
