### ISSUE TITLE
App crashed on android immediately 

### ISSUE THREAD

**Issue by waheedakhtar694** [TheWidlarzGroup/react-native-video#1832]
I am using expo-player with react-native-video version "4.4.4", react-native version "0.59.8", videos was working fine previously but i had to add a library named "react-native-track-player" after adding this app start crashing immediately after installation with expo-player on android-player it only shows a black screen for with audio 
here is link with reference for the issue i am facing with android-player.
#1323 
but expo-player crash the app with this error log
 ```    
java.lang.NoClassDefFoundError: com.brentvatne.exoplayer.ReactExoplayerView
        at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
        at java.lang.Class.getDexCacheType(Class.java:476)
        at java.lang.reflect.Method.getReturnType(Method.java:183)
        at java.lang.Class.getDeclaredMethods(Class.java:672)
        at com.facebook.react.uimanager.ViewManagersPropertyCache.extractPropSettersFromViewManagerClassDefinition(ViewManagersPropertyCache.java:429)
        at com.facebook.react.uimanager.ViewManagersPropertyCache.getNativePropSettersForViewManagerClass(ViewManagersPropertyCache.java:323)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.<init>(ViewManagerPropertyUpdater.java:125)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.<init>(ViewManagerPropertyUpdater.java:119)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.findManagerSetter(ViewManagerPropertyUpdater.java:82)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.getNativeProps(ViewManagerPropertyUpdater.java:69)
        at com.facebook.react.uimanager.ViewManager.getNativeProps(ViewManager.java:208)
        at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstantsForViewManager(UIManagerModuleConstantsHelper.java:148)
        at com.facebook.react.uimanager.UIManagerModuleConstantsHelper.createConstants(UIManagerModuleConstantsHelper.java:95)
        at com.facebook.react.uimanager.UIManagerModule.createConstants(UIManagerModule.java:275)
        at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:181)
        at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:142)
        at com.facebook.react.CoreModulesPackage.createUIManager(CoreModulesPackage.java:182)
        at com.facebook.react.CoreModulesPackage.getModule(CoreModulesPackage.java:150)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:123)
        at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:111)
        at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:189)
        at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:154)
        at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:148)
        at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:427)
        at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:38)
        at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1044)
        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1003)
        at com.facebook.react.ReactInstanceManager.access$1300(ReactInstanceManager.java:123)
        at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:964)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:168)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.brentvatne.exoplayer.ReactExoplayerView" on path: DexPathList[[zip file "/data/app/com.create.wefiq-2/base.apk", zip file "/data/app/com.create.wefiq-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.create.wefiq-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.create.wefiq-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.create.wefiq-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.create.wefiq-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.create.wefiq-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.create.wefiq-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.create.wefiq-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.create.wefiq-2/spl
11-25 19:47:21.949 1002-2634/? E/ActivityManager: App crashed!```

**Comment by sootood** [comment]
i have same issue

**Comment by CoSNaYe** [comment]
Same issue here. I have no idea how to fix it. Is there anyone could kindly help?

**Comment by YajanaRao** [comment]
I am getting the same issue. Any solutions for this?

**Comment by waheedakhtar694** [comment]
In my case, It was conflicting with another library (react-native-track-player).
It was basically an exo-player that was making a problem with these libs.

**Comment by YajanaRao** [comment]
@appify-waheed how did you resolve it?. One walk around for crash is to remove android-exoplayer folder from `/node_modules/react-native-video`

**Comment by waheedakhtar694** [comment]
Yes, look at here.
https://github.com/react-native-kit/react-native-track-player/issues/715

**Comment by infinitbility** [comment]
Hope it Helpful For you

https://infinitbility.com/app-crashed-immediately-after-install-react-native-video-or-track-player

**Comment by skychavda** [comment]
Did anyone solve this issue? 

The package version is:
`"react-native-video": "^5.2.0"`

@infinitbility suggests the solution but downgrading is not the solution for it.

**Comment by freeboub** [comment]
I don't think there is any solution for this... You can have only 1 version of exoplayer per app...
