### ISSUE TITLE
com.yqritc:android-scalablevideoview:1.0.4 have bug in StrictMode

### ISSUE THREAD

**Issue by dcboy** [TheWidlarzGroup/react-native-video#2155]
# Bug

```
09-19 04:30:02.214  16275             StrictMode  E  A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
09-19 04:30:02.214  16275             StrictMode  E  java.lang.Throwable: Explicit termination method 'release' not called
09-19 04:30:02.214  16275             StrictMode  E  at dalvik.system.CloseGuard.open(CloseGuard.java:180)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.Surface.setNativeObjectLocked(Surface.java:459)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.Surface.<init>(Surface.java:145)
09-19 04:30:02.214  16275             StrictMode  E  at com.yqritc.scalablevideoview.ScalableVideoView.onSurfaceTextureAvailable(ScalableVideoView.java:58)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.TextureView.getHardwareLayer(TextureView.java:368)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.updateDisplayListIfDirty(View.java:15151)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.draw(View.java:15948)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-19 04:30:02.214  16275             StrictMode  E  at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.updateDisplayListIfDirty(View.java:15169)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.draw(View.java:15948)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-19 04:30:02.214  16275             StrictMode  E  at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.updateDisplayListIfDirty(View.java:15169)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.draw(View.java:15948)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-19 04:30:02.214  16275             StrictMode  E  at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.updateDisplayListIfDirty(View.java:15169)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.draw(View.java:15948)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-19 04:30:02.214  16275             StrictMode  E  at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.draw(View.java:16181)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.updateDisplayListIfDirty(View.java:15174)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.draw(View.java:15948)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-19 04:30:02.214  16275             StrictMode  E  at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.updateDisplayListIfDirty(View.java:15169)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.draw(View.java:15948)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-19 04:30:02.214  16275             StrictMode  E  at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.updateDisplayListIfDirty(View.java:15169)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.draw(View.java:15948)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-19 04:30:02.214  16275             StrictMode  E  at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.updateDisplayListIfDirty(View.java:15169)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.draw(View.java:15948)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-19 04:30:02.214  16275             StrictMode  E  at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.updateDisplayListIfDirty(View.java:15169)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.draw(View.java:15948)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-19 04:30:02.214  16275             StrictMode  E  at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:703)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.updateDisplayListIfDirty(View.java:15169)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.draw(View.java:15948)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-19 04:30:02.214  16275             StrictMode  E  at com.facebook.react.ReactRootView.dispatchDraw(ReactRootView.java:226)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.updateDisplayListIfDirty(View.java:15169)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.draw(View.java:15948)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.ViewGroup.drawChild(ViewGroup.java:3609)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3399)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.updateDisplayListIfDirty(View.java:15169)
09-19 04:30:02.214  16275             StrictMode  E  at android.view.View.draw(View.java:15948)
09-19 04:30:02.214  16275             StrictMode  E  at android
```

## Platform

* Android MediaPlayer

## Environment info

React native info output:

```bash
System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 786.04 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 15, 18, 20, 22, 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.2, 24.0.1, 25.0.0, 25.0.1, 25.0.3, 26.0.0, 26.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.0, 29.0.2, 29.0.3
      System Images: android-17 | Intel x86 Atom, android-19 | Intel x86 Atom, android-22 | Intel x86 Atom_64, android-23 | Intel x86 Atom_64, android-25 | Intel x86 Atom_64, android-29 | Intel x86 Atom_64
      Android NDK: 21.3.6528147
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_192 - /usr/bin/javac
    Python: 2.7.17 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: latest

## Steps To Reproduce

1.
2.
...

## Expected behaviour

1.
2.

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by aureliopetrone** [comment]
Is this causing the wrong aspect ratio of the videos on Android? In my case the bug has appeared after updating to Xcode 12 and react-native 0.63.2
