### ISSUE TITLE
[ExoPlayer] Fatal Exception: android.view.ViewRootImpl$CalledFromWrongThreadException

### ISSUE THREAD

**Issue by thanakij** [TheWidlarzGroup/react-native-video#2434]
# Bug

We have received a report from Crashlytics saying there is an error about ExoPlayer:

**ReactExoplayerView.java** line 625, com.brentvatne.exoplayer.ReactExoplayerView.**pausePlayback**

```
Fatal Exception: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
       at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8910)
       at android.view.ViewRootImpl.recomputeViewAttributes(ViewRootImpl.java:4422)
       at android.view.ViewGroup.recomputeViewAttributes(ViewGroup.java:1640)
       at android.view.ViewGroup.recomputeViewAttributes(ViewGroup.java:1640)
       at android.view.ViewGroup.recomputeViewAttributes(ViewGroup.java:1640)
       at android.view.ViewGroup.recomputeViewAttributes(ViewGroup.java:1640)
       at android.view.ViewGroup.recomputeViewAttributes(ViewGroup.java:1640)
       at android.view.ViewGroup.recomputeViewAttributes(ViewGroup.java:1640)
       at android.view.ViewGroup.recomputeViewAttributes(ViewGroup.java:1640)
       at android.view.ViewGroup.recomputeViewAttributes(ViewGroup.java:1640)
       at android.view.ViewGroup.recomputeViewAttributes(ViewGroup.java:1640)
       at android.view.ViewGroup.recomputeViewAttributes(ViewGroup.java:1640)
       at android.view.ViewGroup.recomputeViewAttributes(ViewGroup.java:1640)
       at android.view.ViewGroup.recomputeViewAttributes(ViewGroup.java:1640)
       at android.view.ViewGroup.recomputeViewAttributes(ViewGroup.java:1640)
       at android.view.View.setFlags(View.java:15440)
       at android.view.View.setKeepScreenOn(View.java:10242)
       at com.brentvatne.exoplayer.ReactExoplayerView.pausePlayback(ReactExoplayerView.java:625)
       at com.brentvatne.exoplayer.ReactExoplayerView.onAudioFocusChange(ReactExoplayerView.java:682)
       at android.media.AudioManager$ServiceEventHandlerDelegate$1.handleMessage(AudioManager.java:2661)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:219)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:929)
```

## Platform

Which player are you experiencing the problem on:
* Android ExoPlayer

## Environment info

react-native: 0.62.3
react-native-video: 5.1.1

## Steps To Reproduce

I have tried to reproduce the crash but I cannot. I am aware of this due to Crashlytics.
The device is on Android 10 and the model is PPA-LX2.

## Expected behaviour

Running without crashes

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

**Comment by Aleclindner** [comment]
We're seeing the same issue, also unable to reproduce.

**Comment by mym0404** [comment]
![image](https://user-images.githubusercontent.com/33388801/133200298-c5805980-a060-4713-8cbc-e0a6da9657b8.png)
Yes.. `pausePlayback` function seems to a issue.

**Comment by BatRisbec** [comment]
Same here, it's my biggest Crashlytics issue, but no clue about how to reproduce...

**Comment by qburst-subins** [comment]
@thanakij  @BatRisbec @Aleclindner @mym0404  Any updates on this?? I am also facing the same issue.

**Comment by BatRisbec** [comment]
@subinsuresh No updates on my side, but I noticed that the last release (5.2.0-alpha1) was updating ExoPlayer, maybe it fixes the issue, I haven't tried it yet!

**Comment by mym0404** [comment]
@subinsuresh This package is upgraded to `5.2.0` I will try this

**Comment by qburst-subins** [comment]
@BaderSerhan @mym0404 Thanks, will try
