### ISSUE TITLE
DASH Manifest with H265 (hevc) codec does not work

### ISSUE THREAD

**Issue by rohitninawe** [TheWidlarzGroup/react-native-video#2494]
# Bug
Player throws an error when the Dash manifest includes H265.

Affected manifest: https://travelxp.s.llnwi.net/watch1/6130b8c5c66ce2ff85d3f069/manifest_v1.mpd 
Affected Models:
- [Oppo A7](https://www.gsmarena.com/oppo_a7-9394.php)
- [Moto G5S Plus](https://www.gsmarena.com/motorola_moto_g5s_plus-8699.php)

It has HEVC codec adaptation first and H264 codec adaptation second in the DASH manifest. Ideally, if the device is not supporting HEVC, it should have played H264.

https://travelxp.s.llnwi.net/watch1/6130b8c5c66ce2ff85d3f069/manifest_v1.m3u8 has the same codec configuration and this hls is working on the same Android device but not dash manifest.

## Platform
Android Exoplayer

Which player are you experiencing the problem on:
Android ExoPlayer

## Environment info
System:
    OS: Windows 10 10.0.19043
    CPU: (4) ia32 AMD Ryzen 3 3200G with Radeon Vega Graphics    
    Memory: 3.02 GB / 13.95 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files (x86)\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files (x86)\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 31.0.0
      System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-28 | Android TV Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.4.29613.14 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: 0.64.2

React native info output:

Android Studio Logs of Oppo A7:

```bash
2021-09-22 12:30:21.462 16924-17453/com.rohitplayer I/ReactNativeJS: Running "rohitPlayer" with {"rootTag":11}
2021-09-22 12:30:21.790 16924-16924/com.rohitplayer I/ExoPlayerImpl: Init b27c80f [ExoPlayerLib/2.11.4] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.797 16924-16924/com.rohitplayer W/AudioManager: Use of stream types is deprecated for operations other than volume control
2021-09-22 12:30:21.797 16924-16924/com.rohitplayer W/AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
2021-09-22 12:30:21.804 16924-16924/com.rohitplayer D/ReactExoplayerView: onStateChanged: playWhenReady=true, playbackState=idle
2021-09-22 12:30:21.807 16924-16924/com.rohitplayer D/ReactExoplayerView: onStateChanged: playWhenReady=true, playbackState=buffering
2021-09-22 12:30:21.860 16924-17453/com.rohitplayer I/ReactNativeJS: 'onBuffer', { isBuffering: true }
2021-09-22 12:30:21.887 16924-16924/com.rohitplayer I/Choreographer: Skipped 8 frames!  The application may be doing too much work on its main thread.
2021-09-22 12:30:21.901 16924-16924/com.rohitplayer D/AudioManager: dispatching onAudioFocusChange(-1) to android.media.AudioManager@f86d287com.brentvatne.exoplayer.ReactExoplayerView{c5903ee V.E...... ........ 2,2-718,403 #7}
2021-09-22 12:30:21.902 16924-16924/com.rohitplayer W/unknown:ReactNative: Calling JS function after bridge has been destroyed: RCTEventEmitter.receiveEvent([7,"onAudioFocusChanged",{"hasAudioFocus":false}])
2021-09-22 12:30:21.903 16924-16924/com.rohitplayer D/AudioManager: dispatching onAudioFocusChange end 
2021-09-22 12:30:21.927 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.2.4.L120.90, video/hevc] [OMX.google.hevc.decoder, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.929 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.2.4.L90.90, video/hevc] [OMX.google.hevc.decoder, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.931 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 3840x2160x25.0] [OMX.qcom.video.decoder.hevc, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.931 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.2.4.L150.90, video/hevc] [OMX.google.hevc.decoder, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.932 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 3840x2160x25.0] [OMX.qcom.video.decoder.hevc, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.933 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.2.4.L93.90, video/hevc] [OMX.google.hevc.decoder, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.934 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 2560x1440x25.0] [OMX.qcom.video.decoder.hevc, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.934 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.2.4.L150.90, video/hevc] [OMX.google.hevc.decoder, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.934 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 2560x1440x25.0] [OMX.qcom.video.decoder.hevc, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.935 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.2.4.L63.90, video/hevc] [OMX.google.hevc.decoder, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.936 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 3840x2160x25.0] [OMX.qcom.video.decoder.hevc, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.936 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.2.4.L150.90, video/hevc] [OMX.google.hevc.decoder, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.936 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 3840x2160x25.0] [OMX.qcom.video.decoder.hevc, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.937 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.2.4.L120.90, video/hevc] [OMX.google.hevc.decoder, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.939 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.2.4.L90.90, video/hevc] [OMX.google.hevc.decoder, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.941 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 3840x2160x25.0] [OMX.qcom.video.decoder.hevc, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.942 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.2.4.L150.90, video/hevc] [OMX.google.hevc.decoder, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.943 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 3840x2160x25.0] [OMX.qcom.video.decoder.hevc, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.944 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.2.4.L93.90, video/hevc] [OMX.google.hevc.decoder, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.945 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 2560x1440x25.0] [OMX.qcom.video.decoder.hevc, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.945 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.2.4.L150.90, video/hevc] [OMX.google.hevc.decoder, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.946 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 2560x1440x25.0] [OMX.qcom.video.decoder.hevc, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.947 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.2.4.L63.90, video/hevc] [OMX.google.hevc.decoder, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.948 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 3840x2160x25.0] [OMX.qcom.video.decoder.hevc, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.948 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.2.4.L150.90, video/hevc] [OMX.google.hevc.decoder, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.949 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 3840x2160x25.0] [OMX.qcom.video.decoder.hevc, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.950 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 2560x1440x25.0] [OMX.qcom.video.decoder.avc, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.950 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 2560x1440x25.0] [OMX.google.h264.decoder, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.951 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 2560x1440x25.0] [OMX.qcom.video.decoder.avc, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.951 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 2560x1440x25.0] [OMX.qcom.video.decoder.avc, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.951 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 2560x1440x25.0] [OMX.google.h264.decoder, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.951 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 2560x1440x25.0] [OMX.qcom.video.decoder.avc, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.952 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 3840x2160x25.0] [OMX.qcom.video.decoder.avc, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.952 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 3840x2160x25.0] [OMX.google.h264.decoder, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.952 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 3840x2160x25.0] [OMX.qcom.video.decoder.avc, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.956 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 2560x1440x25.0] [OMX.qcom.video.decoder.avc, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.956 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 2560x1440x25.0] [OMX.google.h264.decoder, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.956 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 2560x1440x25.0] [OMX.qcom.video.decoder.avc, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.959 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 2560x1440x25.0] [OMX.qcom.video.decoder.avc, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.959 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 2560x1440x25.0] [OMX.google.h264.decoder, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.960 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 2560x1440x25.0] [OMX.qcom.video.decoder.avc, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.960 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 2560x1440x25.0] [OMX.qcom.video.decoder.avc, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.961 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 2560x1440x25.0] [OMX.google.h264.decoder, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.961 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 2560x1440x25.0] [OMX.qcom.video.decoder.avc, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.961 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 3840x2160x25.0] [OMX.qcom.video.decoder.avc, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.962 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 3840x2160x25.0] [OMX.google.h264.decoder, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.962 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 3840x2160x25.0] [OMX.qcom.video.decoder.avc, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.965 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 2560x1440x25.0] [OMX.qcom.video.decoder.avc, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.966 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 2560x1440x25.0] [OMX.google.h264.decoder, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:21.966 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [sizeAndRate.support, 2560x1440x25.0] [OMX.qcom.video.decoder.avc, video/avc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:22.022 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.2.4.L120.90, video/hevc] [OMX.google.hevc.decoder, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:22.023 16924-17487/com.rohitplayer I/MediaCodec: CreateByComponentName(), name = OMX.qcom.video.decoder.hevc
2021-09-22 12:30:22.023 16924-17487/com.rohitplayer I/MediaCodec: new MediaCodec()
2021-09-22 12:30:22.024 16924-17487/com.rohitplayer I/ACodec: new ACodec()
2021-09-22 12:30:22.026 16924-17493/com.rohitplayer I/ACodec: onAllocateComponent()
2021-09-22 12:30:22.027 16924-17493/com.rohitplayer I/ACodec: ----------------------------------------
2021-09-22 12:30:22.027 16924-17493/com.rohitplayer I/ACodec: matched component [OMX.qcom.video.decoder.hevc]
2021-09-22 12:30:22.027 16924-17493/com.rohitplayer I/ACodec: ----------------------------------------
2021-09-22 12:30:22.030 16924-17493/com.rohitplayer I/OMXClient: Treble IOmx obtained
2021-09-22 12:30:22.180 16924-17493/com.rohitplayer I/ACodec: Successfully allocate component [OMX.qcom.video.decoder.hevc]
2021-09-22 12:30:22.184 16924-17487/com.rohitplayer I/MediaCodec: configure()
2021-09-22 12:30:22.184 16924-17492/com.rohitplayer D/SurfaceUtils: connecting to surface 0x77d564f010, reason connectToSurface
2021-09-22 12:30:22.185 16924-17492/com.rohitplayer I/MediaCodec: [OMX.qcom.video.decoder.hevc] setting surface generation to 17330178
2021-09-22 12:30:22.185 16924-17492/com.rohitplayer D/SurfaceUtils: disconnecting from surface 0x77d564f010, reason connectToSurface(reconnect)
2021-09-22 12:30:22.185 16924-17492/com.rohitplayer D/SurfaceUtils: connecting to surface 0x77d564f010, reason connectToSurface(reconnect)
2021-09-22 12:30:22.186 16924-17493/com.rohitplayer I/ACodec: configureCodec() mime = video/hevc
2021-09-22 12:30:22.187 16924-17493/com.rohitplayer I/ExtendedACodec: setupVideoDecoder()
2021-09-22 12:30:22.195 16924-17493/com.rohitplayer I/ExtendedACodec: Decoder will be in frame by frame mode
2021-09-22 12:30:22.201 16924-17487/com.rohitplayer I/MediaCodec: Video start()
2021-09-22 12:30:22.222 16924-17493/com.rohitplayer D/SurfaceUtils: set up nativeWindow 0x77d564f010 for 1600x900, color 0x7fa30c06, rotation 0, usage 0x20002900
2021-09-22 12:30:22.279 16924-17493/com.rohitplayer E/ACodec: [OMX.qcom.video.decoder.hevc] ERROR(0x80001009)
2021-09-22 12:30:22.279 16924-17493/com.rohitplayer E/ACodec: signalError(omxError 0x80001009, internalError -2147483648)
2021-09-22 12:30:22.279 16924-17492/com.rohitplayer E/MediaCodec: Codec reported err 0x80001009, actionCode 0, while in state 6
2021-09-22 12:30:22.279 16924-17492/com.rohitplayer W/MediaAnalyticsItem: Unable to record: (codec:0:-1:-11:0:12:android.media.mediacodec.codec=OMX.qcom.video.decoder.hevc:android.media.mediacodec.mode=video:android.media.mediacodec.secure=0:android.media.mediacodec.width=1600:android.media.mediacodec.height=900:android.media.mediacodec.rotation-degrees=0:android.media.mediacodec.maxwidth=1600:android.media.mediacodec.maxheight=900:android.media.mediacodec.mime=video/hevc:android.media.mediacodec.bytesin=8543:android.media.mediacodec.errcode=-2147479543:android.media.mediacodec.errstate=6:) [forcenew=0]
2021-09-22 12:30:22.279 16924-17492/com.rohitplayer D/SurfaceUtils: disconnecting from surface 0x77d564f010, reason disconnectFromSurface
2021-09-22 12:30:22.286 16924-17487/com.rohitplayer D/MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.2.4.L120.90, video/hevc] [OMX.google.hevc.decoder, video/hevc] [CPH1901, CPH1901, OPPO, 27]
2021-09-22 12:30:22.290 16924-17487/com.rohitplayer E/ExoPlayerImplInternal: Renderer error: index=0, type=video, format=Format(2fbc0169-d3bf-4898-bad0-3897e1c54f90, null, null, video/hevc, hvc1.2.4.L120.90, 762485, null, [1600, 900, 25.0], [-1, -1]), rendererSupport=YES
      com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException
        at com.google.android.exoplayer2.BaseRenderer.createRendererException(BaseRenderer.java:359)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:735)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:210)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2632)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1520)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:721)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:599) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:329) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:210) 
        at android.os.HandlerThread.run(HandlerThread.java:65) 
2021-09-22 12:30:22.291 16924-17487/com.rohitplayer I/MediaCodec: Video flush()
2021-09-22 12:30:22.295 16924-17487/com.rohitplayer E/ExoPlayerImplInternal: Disable failed.
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_flush(Native Method)
        at android.media.MediaCodec.flush(MediaCodec.java:2114)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:777)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.flushOrReleaseCodec(MediaCodecVideoRenderer.java:724)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:636)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:569)
        at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:168)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1136)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:891)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:850)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:382)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:210)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2021-09-22 12:30:22.295 16924-17487/com.rohitplayer I/MediaCodec: stop()
2021-09-22 12:30:22.296 16924-17487/com.rohitplayer I/MediaCodec: Video release()
2021-09-22 12:30:22.302 16924-17493/com.rohitplayer E/Surface: getSlotFromBufferLocked: unknown buffer: 0x77ea1d9a00
2021-09-22 12:30:22.302 16924-17493/com.rohitplayer W/ACodec: [OMX.qcom.video.decoder.hevc] can not return buffer 26 to native window
2021-09-22 12:30:22.302 16924-17493/com.rohitplayer E/Surface: getSlotFromBufferLocked: unknown buffer: 0x77ea1d9a80
2021-09-22 12:30:22.302 16924-17493/com.rohitplayer W/ACodec: [OMX.qcom.video.decoder.hevc] can not return buffer 25 to native window
2021-09-22 12:30:22.302 16924-17493/com.rohitplayer E/Surface: getSlotFromBufferLocked: unknown buffer: 0x77ea1d9b00
2021-09-22 12:30:22.302 16924-17493/com.rohitplayer W/ACodec: [OMX.qcom.video.decoder.hevc] can not return buffer 24 to native window
2021-09-22 12:30:22.303 16924-17493/com.rohitplayer E/Surface: getSlotFromBufferLocked: unknown buffer: 0x77ea1d9b80
2021-09-22 12:30:22.303 16924-17493/com.rohitplayer W/ACodec: [OMX.qcom.video.decoder.hevc] can not return buffer 23 to native window
2021-09-22 12:30:22.314 16924-17487/com.rohitplayer I/MediaCodec: ~MediaCodec()
2021-09-22 12:30:22.314 16924-17487/com.rohitplayer I/ACodec: ~ACodec()
2021-09-22 12:30:22.318 16924-17487/com.rohitplayer E/ExoPlayerImplInternal: Reset failed.
      java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2067)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:671)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.releaseCodec(MediaCodecVideoRenderer.java:714)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onReset(MediaCodecRenderer.java:643)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onReset(MediaCodecVideoRenderer.java:578)
        at com.google.android.exoplayer2.BaseRenderer.reset(BaseRenderer.java:175)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:900)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:850)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:382)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:210)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2021-09-22 12:30:22.324 16924-16924/com.rohitplayer E/ExoPlayer Exception: com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException
2021-09-22 12:30:22.326 16924-16924/com.rohitplayer D/ReactExoplayerView: onStateChanged: playWhenReady=true, playbackState=idle
2021-09-22 12:30:22.348 16924-17453/com.rohitplayer I/ReactNativeJS: 'onError', { error: 
       { errorException: 'com.google.android.exoplayer2.ExoPlaybackException: java.lang.IllegalStateException',
         errorString: 'ExoPlaybackException type : 1' } }
```

Library version: 5.1.1

**Comment by rohitninawe** [comment]
why this issue has been closed? @hueniverse 
isn't there any fix for this?

**Comment by hueniverse** [comment]
It's been closed because unfortunately we don't have the resources to look into it at this time and we have to close issues to get this project back on track. We are going to be releasing a new major version soon and at that time will be better positioned to review new issues. The new version has so much new code that looking at old issues would not be practical. I know this might not be a satisfying answer but we are working with very limited resources.

**Comment by freeboub** [comment]
@rohitninawe you should try on a standalone exoplayer to investigate this issue. It looks like a device compatibility issue ...
Additionally you didn't pur react native video version. It would be interesting to test with V6 alpha release

**Comment by tpetrew** [comment]
I also have a problem with 265 codec. I compressed video by FFmpeg to 265 codec with command `libx265`. After compressed on IOS video playing without image, just with audio. But its properly working on android

Using `react-native-video alpha 8`

Compressing to 264 codec works to me, but i did not have a lot compression like codec 265

**Comment by notjulian** [comment]
hi @tpetrew,
have you found a solution?

**Comment by tpetrew** [comment]
> hi @tpetrew, have you found a solution?

No, still using 264 codec

**Comment by notjulian** [comment]
> I also have a problem with 265 codec. I compressed video by FFmpeg to 265 codec with command `libx265`. After compressed on IOS video playing without image, just with audio. But its properly working on android
> 
> Using `react-native-video alpha 8`
> 
> Compressing to 264 codec works to me, but i did not have a lot compression like codec 265

react-native-video, under the hood for iOS, uses AVPlayer

maybe this could help [tag the video as hvc1](https://stackoverflow.com/questions/49128084/playing-h-265-video-file-using-avplayer)

I haven't tried yet ...
