### ISSUE TITLE
ANR Android

### ISSUE THREAD

**Issue by UberMC** [TheWidlarzGroup/react-native-video#2502]
API level 29 (10) and 30 (11) only
`at android.media.MediaHTTPConnection.disconnect (MediaHTTPConnection.java:171)
  at android.media.IMediaHTTPConnection$Stub.onTransact (IMediaHTTPConnection.java:132)
  at android.os.Binder.execTransactInternal (Binder.java:1036)
  at android.os.Binder.execTransact (Binder.java:1003)
  at android.media.MediaPlayer._reset (Native method)
  at android.media.MediaPlayer.reset (MediaPlayer.java:2149)
  at com.brentvatne.react.ReactVideoView.setSrc (ReactVideoView.java:273)
  at com.brentvatne.react.ReactVideoView.setSrc (ReactVideoView.java:254)
  at com.brentvatne.react.ReactVideoView.onAttachedToWindow (ReactVideoView.java:725)
  at android.view.View.dispatchAttachedToWindow (View.java:19614)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3439)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3439)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3439)
  at android.view.ViewGroup.addViewInner (ViewGroup.java:5152)
  at android.view.ViewGroup.addView (ViewGroup.java:4938)
  at android.view.ViewGroup.addView (ViewGroup.java:4878)
  at android.view.ViewGroup.addView (ViewGroup.java:4851)
  at androidx.fragment.app.FragmentStateManager.createView (FragmentStateManager.java:326)
  at androidx.fragment.app.FragmentManager.moveToState (FragmentManager.java:1187)
  at androidx.fragment.app.FragmentManager.addAddedFragments (FragmentManager.java:2224)
  at androidx.fragment.app.FragmentManager.executeOpsTogether (FragmentManager.java:1997)
  at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute (FragmentManager.java:1953)
  at androidx.fragment.app.FragmentManager.execPendingActions (FragmentManager.java:1849)
  at androidx.fragment.app.FragmentManager$4.run (FragmentManager.java:413)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:241)
  at android.app.ActivityThread.main (ActivityThread.java:7604)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:941)`

Unknown to reproduce

## Platform
Android

## Environment info

RN 0.63.4
"react-native-video": "^5.1.1",

**Comment by arjun1194** [comment]
I am facing the exact same issue. 99% of ANR are on android 11
my stack trace looks very similar
```
main (unknown): tid=1 systid=6019
       at android.media.MediaHTTPConnection.disconnect(MediaHTTPConnection.java:193)
       at android.media.IMediaHTTPConnection$Stub.onTransact(IMediaHTTPConnection.java:132)
       at android.os.Binder.execTransactInternal(Binder.java:1166)
       at android.os.Binder.execTransact(Binder.java:1130)
       at android.media.MediaPlayer._reset(MediaPlayer.java)
       at android.media.MediaPlayer.reset(MediaPlayer.java:2252)
       at com.yqritc.scalablevideoview.ScalableVideoView.reset(ScalableVideoView.java:248)
       at com.yqritc.scalablevideoview.ScalableVideoView.release(ScalableVideoView.java:252)
       at com.brentvatne.react.ReactVideoView.cleanupMediaPlayerResources(ReactVideoView.java:242)
       at com.brentvatne.react.ReactVideoViewManager.onDropViewInstance(ReactVideoViewManager.java:56)
       at com.brentvatne.react.ReactVideoViewManager.onDropViewInstance(ReactVideoViewManager.java:17)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:635)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:646)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:646)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:646)
       at com.facebook.react.uimanager.NativeViewHierarchyManager.manageChildren(NativeViewHierarchyManager.java:499)
       at com.facebook.react.uimanager.UIViewOperationQueue$ManageChildrenOperation.execute(UIViewOperationQueue.java:217)
       at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:915)
       at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1026)
       at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:47)
       at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1086)
       at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
       at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
       at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1138)
       at android.view.Choreographer.doCallbacks(Choreographer.java:962)
       at android.view.Choreographer.doFrame(Choreographer.java:883)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1125)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:263)
       at android.app.ActivityThread.main(ActivityThread.java:8263)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
       ```

**Comment by arjun1194** [comment]
I read that `ReactVideoView` extends `ScalableVideoView` and so i also created an issue with that library not sure if the issue is because of this library or that one, just in case.
#https://github.com/yqritc/Android-ScalableVideoView/issues/53

**Comment by arjun1194** [comment]
why did you close this ??? can you atleast give some insights?

**Comment by freeboub** [comment]
@arjun1194 it is highly recommended to use exoplayer. Notice that the anr is inside media player. It is not something which can be fixed inside rnv ...

**Comment by UberMC** [comment]
@freeboub How do you "use exoplayer" I've done some searching and am having trouble understanding

**Comment by freeboub** [comment]
@UberMC read the doc ;) https://github.com/react-native-video/react-native-video#android-installation
In next major release old media player should be removed (then exoplayer will be the default player)
