### ISSUE TITLE
Crashes with "unsupported type" error in android when playing either url or local file source

### ISSUE THREAD

**Issue by nateshmbhat** [TheWidlarzGroup/react-native-video#2578]
Here's the component I am using :
```
const RNVideoPlayer = () => {
  return (
    <View style={{height: 200, width: 200}}>
      <Video
        style={{position: 'absolute', top: 0, bottom: 0, left: 0, right: 0}}
        paused={false}
        source={{
          uri: 'https://images-sgex.sadhguru.org/sgapp/assets/en/media/infinity-meditation_en.mp4',
        }}
      />
    </View>
  );
};
```
When I include this component as part of any screen, the app is crashing.

Here's the error stack track : 
```
2022-01-19 13:40:45.957 15640-15640/com.ishafoundation.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ishafoundation.app, PID: 15640
    java.lang.IllegalStateException: Unsupported type: 4
        at com.brentvatne.exoplayer.ReactExoplayerView.buildMediaSource(ReactExoplayerView.java:533)
        at com.brentvatne.exoplayer.ReactExoplayerView.access$2700(ReactExoplayerView.java:84)
        at com.brentvatne.exoplayer.ReactExoplayerView$6.run(ReactExoplayerView.java:449)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8010)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

**Comment by mtuguldurb** [comment]
Have you found anything on this issue? I just encountered it and there is noting on the internet about this one.

**Comment by freeboub** [comment]
I have strange warning when playing with VLC.
cannot be played with sample on 6.0 alpha.1.
I think the video have an issue :/
If you need to go forward, you should ensure it plays with exoplayer sample.

**Comment by managlia** [comment]
Natesh, I'm getting the same thing. How did you resolve the issue?
