### ISSUE TITLE
 unexpected error occurred when yarn add

### ISSUE THREAD

**Issue by jesuasir007** [TheWidlarzGroup/react-native-video#2603]
An unexpected error occurred: "https://registry.npmjs.org/colors/-/colors-1.4.2.tgz: Request failed \"404 Not Found\""

cmd->yarn add react-native-video

**Comment by jesuasir007** [comment]
Trace: 
  Error: https://registry.npmjs.org/colors/-/colors-1.4.2.tgz: Request failed "404 Not Found"
      at ResponseError.ExtendableBuiltin (/opt/homebrew/Cellar/yarn/1.22.17_2/libexec/lib/cli.js:696:66)
      at new ResponseError (/opt/homebrew/Cellar/yarn/1.22.17_2/libexec/lib/cli.js:802:124)
      at Request.<anonymous> (/opt/homebrew/Cellar/yarn/1.22.17_2/libexec/lib/cli.js:67099:16)
      at Request.emit (node:events:390:28)
      at Request.module.exports.Request.onRequestResponse (/opt/homebrew/Cellar/yarn/1.22.17_2/libexec/lib/cli.js:141760:10)
      at ClientRequest.emit (node:events:390:28)
      at HTTPParser.parserOnIncomingClient (node:_http_client:618:27)
      at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
      at TLSSocket.socketOnData (node:_http_client:482:22)
      at TLSSocket.emit (node:events:390:28)

**Comment by jesuasir007** [comment]
yarn config set registry https://registry.npmjs.org
rm yarn.lock
yarn

**Comment by jesuasir007** [comment]
fix that issues.

**Comment by freeboub** [comment]
Seems ok, let's close the ticket
