### ISSUE TITLE
 Android App Crash

### ISSUE THREAD

**Issue by ehab-qadah** [TheWidlarzGroup/react-native-video#2685]
# Bug

 Android App Crash: 

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/video/VideoListener;
        at com.brentvatne.exoplayer.ReactExoplayerView.createViews(ReactExoplayerView.java:226)
        at com.brentvatne.exoplayer.ReactExoplayerView.<init>(ReactExoplayerView.java:202)
        at com.brentvatne.exoplayer.ReactExoplayerViewManager.createViewInstance(ReactExoplayerViewManager.java:87)
        at com.brentvatne.exoplayer.ReactExoplayerViewManager.createViewInstance(ReactExoplayerViewManager.java:28)
        at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:139)
        at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:76)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1110)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1081)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.video.VideoListener" on path: DexPathList[[zip file "/data/app/~~mPVx7Acrt2RKSgoqw1Ogbw==/io.almahealth.dev-ddStX5PRmd627EPKE5GftQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~mPVx7Acrt2RKSgoqw1Ogbw==/io.almahealth.dev-ddStX5PRmd627EPKE5GftQ==/lib/x86, /data/app/~~mPVx7Acrt2RKSgoqw1Ogbw==/io.almahealth.dev-ddStX5PRmd627EPKE5GftQ==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

## Platform

Which player are you experiencing the problem on:
* Android

## Environment info

React native info output:

```bash
info Fetching system and libraries information...
System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 25.99 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - /var/folders/lx/7ytk2ysd5xl07wt0cpv3tfsm0000gn/T/yarn--1652782463366-0.2977010355823537/node
    Yarn: 1.22.11 - /var/folders/lx/7ytk2ysd5xl07wt0cpv3tfsm0000gn/T/yarn--1652782463366-0.2977010355823537/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1 - /usr/local/opt/openjdk/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.4 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
✨  Done in 12.41s.
```

Library version: 5.2.1

## Steps To Reproduce
const VIDEO_LINK = '
 <Video
            repeat
            paused={!focused}
            volume={mute ? 0 : 1}
            muted={mute}
            source={{
             VIDEO_LINK,
            }}
            resizeMode="cover"
            posterResizeMode="cover"
            ignoreSilentSwitch="ignore"
            style={{
              width: scaled(375),
              height: scaled(211),
            }}
          />

app crash on view
1.
2.
...

## Expected behaviour

1.
2.

## Video sample
https://media.almahealth.io/videos/alma.mp4

**Comment by phuocantd** [comment]
same here

**Comment by hueniverse** [comment]
Are you able to build and run the examples or the test repo at https://github.com/react-native-video/react-native-video-test?

**Comment by freeboub** [comment]
looks like a link issue ...
I think you have an issue with exoplayer integration.
do you well configure exoplayer usage ?
Thank you

**Comment by hueniverse** [comment]
Closing due to lack of response. Feel free to reply back if you still need help with this.

**Comment by yasir128** [comment]
We are still facing this issue for videos in list like tiktok in version 5.2.1

**Comment by mittalkamal29** [comment]
> We are still facing this issue for videos in list like tiktok in version 5.2.1

Hi @yasir128 Did you find any solution for same?

**Comment by yasir128** [comment]
yes i change the video player in native code @mittalkamal29
