### ISSUE TITLE
NoSuchMethodError on Android (React Native 0.69.4)

### ISSUE THREAD

**Issue by egealpay** [TheWidlarzGroup/react-native-video#2818]
# Bug

I am testing this library on React Native 0.69.4 and when I render this component, I get the following error:

```
java.lang.NoSuchMethodError: No virtual method buildOrThrow()Lcom/google/common/collect/ImmutableMap; in class Lcom/google/common/collect/ImmutableMap$Builder; or its super classes (declaration of 'com.google.common.collect.ImmutableMap$Builder' appears in /data/app/~~tNqEIh9S3GENoly_joqmuA==/albert.health-EWai5l08jr0b3VCE2sm-9Q==/base.apk!classes10.dex)
        at com.google.android.exoplayer2.analytics.DefaultAnalyticsCollector$MediaPeriodQueueTracker.updateMediaPeriodTimelines(DefaultAnalyticsCollector.java:1130)
        at com.google.android.exoplayer2.analytics.DefaultAnalyticsCollector$MediaPeriodQueueTracker.onTimelineChanged(DefaultAnalyticsCollector.java:1092)
        at com.google.android.exoplayer2.analytics.DefaultAnalyticsCollector.onTimelineChanged(DefaultAnalyticsCollector.java:467)
        at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$12(ExoPlayerImpl.java:1850)
        at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda10.invoke(Unknown Source:6)
        at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:281)
        at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:190)
        at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda1.run(Unknown Source:6)
        at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:211)
        at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1947)
        at com.google.android.exoplayer2.ExoPlayerImpl.setMediaSourcesInternal(ExoPlayerImpl.java:2159)
        at com.google.android.exoplayer2.ExoPlayerImpl.setMediaSources(ExoPlayerImpl.java:575)
        at com.google.android.exoplayer2.ExoPlayerImpl.setMediaSource(ExoPlayerImpl.java:563)
        at com.google.android.exoplayer2.ExoPlayerImpl.prepare(ExoPlayerImpl.java:531)
        at com.brentvatne.exoplayer.ReactExoplayerView.initializePlayerSource(ReactExoplayerView.java:651)
        at com.brentvatne.exoplayer.ReactExoplayerView.access$2100(ReactExoplayerView.java:113)
        at com.brentvatne.exoplayer.ReactExoplayerView$6$1$1.run(ReactExoplayerView.java:544)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

## Platform
* Android (Real Device) (Both Debug and Release)

## Environment info

React native info output:

```bash
System:
    OS: macOS 12.5
    CPU: (8) x64 Apple M1
    Memory: 22.79 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.19.3/bin/yarn
    npm: 8.12.1 - ~/.nvm/versions/node/v14.19.3/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 26, 28, 29, 30, 31
      Build Tools: 27.0.3, 28.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      System Images: android-24 | ARM 64 v8a, android-24 | Google APIs ARM 64 v8a, android-28 | Google APIs ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-31 | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8139111
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.4 => 0.69.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 6.0.0-alpha.1

## Steps To Reproduce

Try to render the component with the following snippet
```
<Video
            source={{uri: "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"}}   // Can be a URL or a local file.
            ref={(ref) => {
                this.player = ref
            }}                                      // Store reference
            onBuffer={this.onBuffer}                // Callback when remote video is buffering
            style={{
                position: 'absolute',
                top: 0,
                left: 0,
                bottom: 0,
                right: 0,
            }}/>
```

## Expected behaviour

* To see the video playing without crashing

## Reproducible sample code

Added above.

## Video sample

`http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4`

**Comment by freeboub** [comment]
can you provide a full sample to reproduce the issue please ?

**Comment by gramound** [comment]
The method ```buildOrThrow``` is relatively new in ```ImmutableMap```. Make sure you have guava >= 31
