### ISSUE TITLE
Can't reinstall react-native-video on android (no variant found for :react-native-video

### ISSUE THREAD

**Issue by jrhager84** [TheWidlarzGroup/react-native-video#2821]
# Bug

## Platform

Which player are you experiencing the problem on:
* Android

## Environment info

React native info output:

```bash
 System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.04 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.18.0 - /opt/homebrew/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1 - /opt/homebrew/opt/openjdk/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 5.2.0

## Steps To Reproduce

1. Have issue with react-native-video after gradle clean (no variant found for :react-native-video)
2. uninstall / invalidate cache / delete node_modules/yarn.lock 
3. reinstall
4. issue persists (app builds and syncs without react-native-video. Fails with it included
...

## Expected behaviour

1. Successful Gradle sync/build
2.

## Reproducible sample code

I'm not sure what else will be helpful, but I will provide anything I can to help. I'm not exactly sure what the issue is. Every other package installed fine after the clean except for react-native-video. I'm unsure of where the problem originated or how to fix it. Thanks!

**Comment by freeboub** [comment]
can you send a log of the output ?
which version version of react-native-video do you install ?

**Comment by OlivierFreyssinet** [comment]
EDIT: I found a workaround, see my next comment https://github.com/react-native-video/react-native-video/issues/2821#issuecomment-1222435572

Hello, I have the same issue, on react-native-video `5.2.0`.

### Android build logs:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.android.exoplayer:exoplayer:2.13.2.
     Searched in the following locations:
       - file:/Users/olivier.freyssinet/.m2/repository/com/google/android/exoplayer/exoplayer/2.13.2/exoplayer-2.13.2.pom
       - file:/Users/olivier.freyssinet/Workspace/ledger-live/apps/ledger-live-mobile/node_modules/react-native/android/com/google/android/exoplayer/exoplayer/2.13.2/exoplayer-2.13.2.pom
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/exoplayer/2.13.2/exoplayer-2.13.2.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/exoplayer/2.13.2/exoplayer-2.13.2.pom
       - https://jitpack.io/com/google/android/exoplayer/exoplayer/2.13.2/exoplayer-2.13.2.pom
       - file:/Users/olivier.freyssinet/Workspace/ledger-live/apps/ledger-live-mobile/node_modules/detox/Detox-android/com/google/android/exoplayer/exoplayer/2.13.2/exoplayer-2.13.2.pom
       - file:/Users/olivier.freyssinet/Workspace/ledger-live/apps/ledger-live-mobile/node_modules/expo-camera/android/maven/com/google/android/exoplayer/exoplayer/2.13.2/exoplayer-2.13.2.pom
     Required by:
         project :app > project :react-native-video
   > Could not find com.google.android.exoplayer:extension-okhttp:2.13.2.
     Searched in the following locations:
       - file:/Users/olivier.freyssinet/.m2/repository/com/google/android/exoplayer/extension-okhttp/2.13.2/extension-okhttp-2.13.2.pom
       - file:/Users/olivier.freyssinet/Workspace/ledger-live/apps/ledger-live-mobile/node_modules/react-native/android/com/google/android/exoplayer/extension-okhttp/2.13.2/extension-okhttp-2.13.2.pom
       - https://repo.maven.apache.org/maven2/com/google/android/exoplayer/extension-okhttp/2.13.2/extension-okhttp-2.13.2.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/exoplayer/extension-okhttp/2.13.2/extension-okhttp-2.13.2.pom
       - https://jitpack.io/com/google/android/exoplayer/extension-okhttp/2.13.2/extension-okhttp-2.13.2.pom
       - file:/Users/olivier.freyssinet/Workspace/ledger-live/apps/ledger-live-mobile/node_modules/detox/Detox-android/com/google/android/exoplayer/extension-okhttp/2.13.2/extension-okhttp-2.13.2.pom
       - file:/Users/olivier.freyssinet/Workspace/ledger-live/apps/ledger-live-mobile/node_modules/expo-camera/android/maven/com/google/android/exoplayer/extension-okhttp/2.13.2/extension-okhttp-2.13.2.pom
     Required by:
         project :app > project :react-native-video

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

    at makeError (/Users/olivier.freyssinet/Workspace/ledger-live/node_modules/.pnpm/execa@1.0.0/node_modules/execa/index.js:174:9)
    at /Users/olivier.freyssinet/Workspace/ledger-live/node_modules/.pnpm/execa@1.0.0/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/olivier.freyssinet/Workspace/ledger-live/node_modules/.pnpm/@react-native-community+cli-platform-android@7.0.1/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/olivier.freyssinet/Workspace/ledger-live/node_modules/.pnpm/@react-native-community+cli@7.0.4_oxdc6pm5g5rdvpaycf2kzdj6te/node_modules/@react-native-community/cli/build/index.js:192:9)
```

### `react-native info` output:

```
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 173.02 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 30, 31, 32
      Build Tools: 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      System Images: android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, chromeos-67 | Chrome OS 67
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^7.0.1 => 7.0.4 
    react: ^17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by OlivierFreyssinet** [comment]
This is the same issue as https://github.com/react-native-video/react-native-video/issues/2611.

### Workaround:

You can either apply the patch mentioned in the issue #2611 or put this in `android/build.gradle` and it builds and seems to run fine (videos work in our app):

```groovy
allprojects {
    /* (...) */
    configurations.all {
        resolutionStrategy {
            /**
             * the following exoplayer config is for react-native-video
             * cf:
             *  https://github.com/react-native-video/react-native-video/issues/2611
             *  https://github.com/react-native-video/react-native-video/issues/2821
             * 
             */
            force 'com.google.android.exoplayer:exoplayer:2.13.3'
            force 'com.google.android.exoplayer:extension-okhttp:2.13.3'
        }
    }
}

```

**Comment by freeboub** [comment]
release 5.2.1 should fix this issue, let me  know if it is ok ?
