### ISSUE TITLE
Duration is wrong in android and video cannot be played or start.

### ISSUE THREAD

**Issue by ahmedelsayed11233** [TheWidlarzGroup/react-native-video#2902]
# Bug

## Platform

Which player are you experiencing the problem on:
* Android

## Environment info

React native info output:

```bash
 System:
    OS: macOS 12.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 42.51 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.10.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/Desktop/ReactNativeApps/MobileX/node_modules/.bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: 2022.09.26.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: /Users/ahmedelsayed/Library/Android/sdk
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: ^6.0.0-alpha.2

## Expected behaviour

1. get duration correct and can play the audio
2. get duration like -9223372036854776 

## Video Component
`  <Video
            muted={false}
            paused={pause ? pause : true}
            source={{ uri: currentMessage?.audio }} // Can be a URL or a local file.
            ref={video} // Store reference
            onLoad={handleOnLoad}
            onProgress={handleProgress}
            onBuffer={onBuffer} // Callback when remote video is buffering
            onError={videoError} // Callback when video cannot be loaded
            onEnd={onEnd}
            controls={false}
            audioOnly={true}
            playInBackground={false}
            // resizeMode={'contain'}
            // disableFocus={true}
            // playWhenInactive={false}
            ignoreSilentSwitch={'ignore'}
            // progressUpdateInterval={250.0}
            useTextureView={false}
            // playInBackground={true}
            disableFocus={true}
            // maxBitRate={2000000}
            resizeMode='cover'
         />`

## Video sample
If possible, include a link to the video that has the problem that can be streamed or downloaded from.

https://firebasestorage.googleapis.com/v0/b/mazadat-firebase.appspot.com/o/voiceNotes%2F25-9-2022-2-18.mp4?alt=media&token=a9e79549-99cb-455f-8ce6-76e2f1bfab70

**Comment by freeboub** [comment]
I did a very small check, I think it comes from this file server. If you download the file and integrate it in your app, are you able to read it correctly?

**Comment by ahmedelsayed11233** [comment]
> I did a very small check, I think it comes from this file server. If you download the file and integrate it in your app, are you able to read it correctly?

When downloading the file and try to open it in QuickTimePlayer it cannot be opened but its working when open it in the browser.

**Comment by ahmedelsayed11233** [comment]
Its working fine in iOS and get the exact duration but why in android doesn't retrieve the duration ? @freeboub
Also when trying to download a test file .mp4 file and pass it to the video it doesn't work on both android and iOS?

**Comment by ahmedelsayed11233** [comment]
## I am getting this error in android but duration has been come correctly.

`{"errorCode": "25001", "errorException": "com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(null, null, null, audio/raw, null, -1, null, [-1, -1, -1.0], [1, 48000]), format_supported=YES", "errorStackTrace": "com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(null, null, null, audio/raw, null, -1, null, [-1, -1, -1.0], [1, 48000]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(48000, 4, 24000)
	at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2092)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrack(DefaultAudioSink.java:1070)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrackWithRetry(DefaultAudioSink.java:1049)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:846)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:929)
	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:703)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1894)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:792)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
	... 4 more
	Suppressed: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(48000, 4, 24000)
		... 14 more
	Caused by: java.lang.UnsupportedOperationException: Cannot create AudioTrack
		at android.media.AudioTrack$Builder.build(AudioTrack.java:1308)
		at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.createAudioTrackV29(DefaultAudioSink.java:2141)
		at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.createAudioTrack(DefaultAudioSink.java:2119)
		at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2084)
		... 13 more
Caused by: java.lang.UnsupportedOperationException: Cannot create AudioTrack
	at android.media.AudioTrack$Builder.build(AudioTrack.java:1308)
	at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.createAudioTrackV29(DefaultAudioSink.java:2141)
	at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.createAudioTrack(DefaultAudioSink.java:2119)
	at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2084)
	... 13 more
", "errorString": "ExoPlaybackException: ERROR_CODE_AUDIO_TRACK_INIT_FAILED"}}
 LOG  🚀 ~ file: MessageAudioMessage.js ~ line 22 ~ videoError ~ error {"error": {"errorCode": "25001", "errorException": "com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(null, null, null, audio/raw, null, -1, null, [-1, -1, -1.0], [1, 48000]), format_supported=YES", "errorStackTrace": "com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(null, null, null, audio/raw, null, -1, null, [-1, -1, -1.0], [1, 48000]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(48000, 4, 24000)
	at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2092)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrack(DefaultAudioSink.java:1070)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrackWithRetry(DefaultAudioSink.java:1049)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:846)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:929)
	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:703)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1894)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:792)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
	... 4 more
	Suppressed: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(48000, 4, 24000)
		... 14 more
	Caused by: java.lang.UnsupportedOperationException: Cannot create AudioTrack
		at android.media.AudioTrack$Builder.build(AudioTrack.java:1308)
		at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.createAudioTrackV29(DefaultAudioSink.java:2141)
		at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.createAudioTrack(DefaultAudioSink.java:2119)
		at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2084)
		... 13 more
Caused by: java.lang.UnsupportedOperationException: Cannot create AudioTrack
	at android.media.AudioTrack$Builder.build(AudioTrack.java:1308)
	at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.createAudioTrackV29(DefaultAudioSink.java:2141)
	at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.createAudioTrack(DefaultAudioSink.java:2119)
	at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2084)
	... 13 more
", "errorString": "ExoPlaybackException: ERROR_CODE_AUDIO_TRACK_INIT_FAILED"}}`

**Comment by AChevallier** [comment]
I've got the same problem. I am using m3u8 stream :(

**Comment by ahmedelsayed11** [comment]
I resolved this issue in android by adding this code in android/settings.gradle
`include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')`

You have to put this at the end of the file before `include ':app'`

<img width="1334" alt="Screen Shot 2022-11-15 at 10 39 22 AM" src="https://user-images.githubusercontent.com/35149957/201871273-fc13ca21-8ff0-4e75-a398-0fa66da2a0da.png">

**Comment by freeboub** [comment]
Thanks for the update, let's close this issue
