### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/Player$EventListener

### ISSUE THREAD

**Issue by dylancolin** [TheWidlarzGroup/react-native-video#3061]
# Bug

 Failed to create NativeModule "UIManager"
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/Player$EventListener;
 	at com.brentvatne.react.ReactVideoPackage.createViewManagers(ReactVideoPackage.java:42)
 	at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:925)
 	at com.swmansion.reanimated.ReanimatedPackage.createUIManager(ReanimatedPackage.java:73)
 	at com.swmansion.reanimated.ReanimatedPackage.getModule(ReanimatedPackage.java:33)
 	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:161)
 	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:149)
 	at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:191)
 	at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:156)
 	at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:170)
 	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:493)
 	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:469)
 	at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:89)
 	at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:47)
 	at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1241)
 	at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1183)
 	at com.facebook.react.ReactInstanceManager.access$1600(ReactInstanceManager.java:135)
 	at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:1137)
 	at android.os.Handler.handleCallback(Handler.java:942)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
 	at android.os.Looper.loopOnce(Looper.java:201)
 	at android.os.Looper.loop(Looper.java:288)
 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
 	at java.lang.Thread.run(Thread.java:1012)
 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.Player$EventListener" on path: DexPathList[[zip file "/data/app/~~nCwm1gLRoNfToUcmimTSqQ==/com.myapp.app-U476pPQWzn7d0x02daQrYQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~nCwm1gLRoNfToUcmimTSqQ==/com.myapp.app-U476pPQWzn7d0x02daQrYQ==/lib/arm64, /data/app/~~nCwm1gLRoNfToUcmimTSqQ==/com.myapp.app-U476pPQWzn7d0x02daQrYQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
 	... 24 more
E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
E AndroidRuntime: Process: com.myapp.app, PID: 2649
E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/Player$EventListener;
E AndroidRuntime: 	at com.brentvatne.react.ReactVideoPackage.createViewManagers(ReactVideoPackage.java:42)
E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.getOrCreateViewManagers(ReactInstanceManager.java:925)
E AndroidRuntime: 	at com.swmansion.reanimated.ReanimatedPackage.createUIManager(ReanimatedPackage.java:73)
E AndroidRuntime: 	at com.swmansion.reanimated.ReanimatedPackage.getModule(ReanimatedPackage.java:33)
E AndroidRuntime: 	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:161)
E AndroidRuntime: 	at com.facebook.react.TurboReactPackage$ModuleHolderProvider.get(TurboReactPackage.java:149)
E AndroidRuntime: 	at com.facebook.react.bridge.ModuleHolder.create(ModuleHolder.java:191)
E AndroidRuntime: 	at com.facebook.react.bridge.ModuleHolder.getModule(ModuleHolder.java:156)
E AndroidRuntime: 	at com.facebook.react.bridge.NativeModuleRegistry.getModule(NativeModuleRegistry.java:170)
E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:493)
E AndroidRuntime: 	at com.facebook.react.bridge.CatalystInstanceImpl.getNativeModule(CatalystInstanceImpl.java:469)
E AndroidRuntime: 	at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:89)
E AndroidRuntime: 	at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:47)
E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.attachRootViewToInstance(ReactInstanceManager.java:1241)
E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:1183)
E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.access$1600(ReactInstanceManager.java:135)
E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$5$2.run(ReactInstanceManager.java:1137)
E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.Player$EventListener" on path: DexPathList[[zip file "/data/app/~~nCwm1gLRoNfToUcmimTSqQ==/com.myapp.app-U476pPQWzn7d0x02daQrYQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~nCwm1gLRoNfToUcmimTSqQ==/com.myapp.app-U476pPQWzn7d0x02daQrYQ==/lib/arm64, /data/app/~~nCwm1gLRoNfToUcmimTSqQ==/com.myapp.app-U476pPQWzn7d0x02daQrYQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E AndroidRuntime: 	... 24 more

## Platform

Which player are you experiencing the problem on:
* Android

## Environment info

React native info output:
System:
    OS: macOS 13.0.1
    CPU: (8) x64 Apple M1 Pro
    Memory: 17.05 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.20.0/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
    Watchman: 2022.08.22.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 5.2.1

...

**Comment by freeboub** [comment]
An issue with proguard ?

**Comment by dylancolin** [comment]
> An issue with proguard ?

Don't think so. The app crashes in debug too (proguard not enabled). 
Also, tried adding "-keep class com.google.android.exoplayer.** { *; }" in proguard-rules.pro , still same error.

**Comment by dylancolin** [comment]
> An issue with proguard ?

Update: 
Have resolved it for now. We were using the "intercom/intercom-react-native" package in our project too, removing it solved the crash.
Another thing, the error trace mentions "reanimated" package too. Sill don't know the root cause and connection between these packages. Understanding the cause will be helpful.

**Comment by adelbeke** [comment]
+1

The proguard rule doesn't fix it

**Comment by adelbeke** [comment]
But it happens on a project with very few dependencies so I don't know if the problem comes from a conflict 

```
{
  "name": "my-app",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~48.0.5",
    "expo-av": "~13.2.1",
    "expo-splash-screen": "~0.18.1",
    "expo-status-bar": "~1.4.4",
    "react": "18.2.0",
    "react-native": "0.71.3",
    "react-native-fs": "^2.20.0",
    "react-native-video": "^5.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.0.14",
    "@types/react-native-video": "^5.0.14",
    "typescript": "^4.9.4"
  },
  "private": true
}
```

**Comment by freeboub** [comment]
@adscud did you enable exoplayer in react native video ? Because expo-av also use exoplayer.

**Comment by adelbeke** [comment]
Yes it happens after enabling exoplayer from gradles.settings

**Comment by freeboub** [comment]
> Yes it happens after enabling exoplayer from gradles.settings 

You have a conflict between both exoplayer version! I just check expo-av now use exoplayer 2.18.1. if you upgrade rnv to 6.0.0 alpha, it should work as it is the same exoplayer version used

**Comment by freeboub** [comment]
@dylancolin do you have the same issue ? Do you also use expo-av ?

**Comment by adelbeke** [comment]
I simply remove `expo-av`, didn't test the upgrade to 6.0.0 but it works now.
Thans you (again) :)

**Comment by gridphp** [comment]
+1, Having same issue. I'm using react-native-track-player as well.

**Comment by vorontsovanady** [comment]
I have the same issue after upgrade `@intercom/intercom-react-native`  library from v3 to v4. And I can't remove itercom from the project. Did anybody resolve this?
