### ISSUE TITLE
Cannot read .m3u8 video on Android

### ISSUE THREAD

**Issue by adelbeke** [TheWidlarzGroup/react-native-video#3070]
# Bug

I can't read a `.m3u8` video on android with this following error : `{"extra": -1007, "what": 1}`.
It works fine on iOS without error.

The video url is : `https://d6disd5akhup9.cloudfront.net/post_media/da26162b26d6366e78d37b44/videos/DvHQgG6yShVw7fHyzfQVw9hA/index-1679061656817.m3u8`

With Postman I have the video without specifying headers, so the player should be able to.

<details>
  <summary>See Postman</summary>

  ![Screenshot 2023-03-17 at 15 26 38](https://user-images.githubusercontent.com/34245352/225932879-0c96507f-b8e9-40d7-9639-8390e5c526a9.png)
</details>

## Platform

Which player are you experiencing the problem on:
* Android

## Environment info

React native info output:

```bash
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 602.03 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 
    Yarn: 1.22.17 
    npm: 8.19.2 
    Watchman: 2022.11.14.00 
  Managers:
    CocoaPods: 1.11.3
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 14.2/14C18 
  Languages:
    Java: 11.0.15 
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.5 => 0.70.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

```

Library version: 5.2.1

## Expected behaviour

1. Being able to play the `.m3u8` video on Android like on iOS

## Reproducible sample code

```tsx
<Video
        source={{uri: 'https://d6disd5akhup9.cloudfront.net/post_media/da26162b26d6366e78d37b44/videos/DvHQgG6yShVw7fHyzfQVw9hA/index-1679061656817.m3u8', type: 'm3u8'}}
        style={{width: 300, height: 300, borderColor: 'red', borderWidth: 1}}
        paused={false}
        onLoadStart={() => console.log('onLoadStart')}
        onLoad={(data: OnLoadData) => console.log('onLoad', data)}
        onBuffer={(data: OnBufferData) => console.log('onBuffer', data)}
        onError={(data: LoadError) => console.log('onError', data)}
        onBandwidthUpdate={(data: OnBandwidthUpdateData) => console.log('onBandwidthUpdate', data)}
        onSeek={(data: OnSeekData) => console.log('onSeek', data)}
        onEnd={() => console.log('onEnd')}
      />
```

**Comment by freeboub** [comment]
You can check in more details the logcat please ? I think the exoplayer (are you using exoplayer? ) Error is more explicit than the RNV error

**Comment by adelbeke** [comment]
@freeboub Yes you right.

I hope this trace will helps

```
03-17 18:43:24.017 24815 24815 W MediaPlayer: Couldn't open https://d6disd5akhup9.cloudfront.net/...
03-17 18:43:24.017 24815 24815 W MediaPlayer: java.io.FileNotFoundException: No content provider: https://d6disd5akhup9.cloudfront.net/post_media/da26162b26d6366e78d37b44/videos/DvHQgG6yShVw7fHyzfQVw9hA/index-1679061656817.m3u8
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1687)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1517)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1434)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at android.media.MediaPlayer.attemptDataSource(MediaPlayer.java:1180)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1152)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1176)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at com.yqritc.scalablevideoview.ScalableVideoView.setDataSource(ScalableVideoView.java:143)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at com.brentvatne.react.ReactVideoView.setSrc(ReactVideoView.java:300)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at com.brentvatne.react.ReactVideoView.setSrc(ReactVideoView.java:254)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at com.brentvatne.react.ReactVideoViewManager.setSrc(ReactVideoViewManager.java:98)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at java.lang.reflect.Method.invoke(Native Method)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:93)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:136)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:56)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:86)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:188)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:115)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:281)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:194)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:1110)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:1081)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:997)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at android.view.Choreographer.doCallbacks(Choreographer.java:797)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at android.view.Choreographer.doFrame(Choreographer.java:728)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at android.os.Handler.handleCallback(Handler.java:883)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at android.os.Looper.loop(Looper.java:237)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at java.lang.reflect.Method.invoke(Native Method)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
03-17 18:43:24.017 24815 24815 W MediaPlayer: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
03-17 18:43:24.018 24815 24815 V MediaHTTPService: MediaHTTPService(android.media.MediaHTTPService@e59b183): Cookies: null
03-17 18:43:24.025   783   783 V MediaPlayerService: Create new client(235) from pid 24815, uid 10333,
03-17 18:43:24.029   783   783 V MediaPlayerService: player type = 4
03-17 18:43:24.032   783   783 D NuPlayerDriver: NuPlayerDriver(0xf1f31c00) created, clientPid(24815)
03-17 18:43:24.047   783   783 I Codec2Client: Creating a Codec2 client to service "software"
03-17 18:43:24.063   783   783 I Codec2Client: Client to Codec2 service "software" created
03-17 18:43:24.070   783   783 I Codec2Client: Creating a Codec2 client to service "default"
03-17 18:43:24.074   783   783 I Codec2Client: Client to Codec2 service "default" created
```

**Comment by freeboub** [comment]
You use MediaPlayer implementation... You should switch to exoplayer as mediaplayer is deprecated

**Comment by adelbeke** [comment]
@freeboub Okay didn't aware about several providers, my bad.
Can u tell me where I can found a way to switch to exoplayer from the documentation ?

**Comment by freeboub** [comment]
This is it : https://github.com/react-native-video/react-native-video/blob/v5.2.0/README.md#Android-installation

**Comment by adelbeke** [comment]
Merci ;)
