### ISSUE TITLE
App crashes on Android

### ISSUE THREAD

**Issue by vaibhavgadekar** [TheWidlarzGroup/react-native-video#3170]
# Bug
The app is crashing in Production with the below error

`Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String c8.p.a' on a null object reference in method 'void com.brentvatne.exoplayer.f.M(j7.t)'
       at com.brentvatne.exoplayer.ReactExoplayerView.onPlayerError(ReactExoplayerView.java:36)
       at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$9(ExoPlayerImpl.java:2)
       at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:17)
       at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:16)
       at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:66)
       at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:376)
       at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:127)
       at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$1(ExoPlayerImpl.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:233)
       at android.os.Looper.loop(Looper.java:344)
       at android.app.ActivityThread.main(ActivityThread.java:8204)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)`

## Platform
Which player are you experiencing the problem on:
* Android

**Comment by freeboub** [comment]
which version of the library ? 
can you reproduce on V6.0.0 ?

**Comment by vaibhavgadekar** [comment]
Thanks @freeboub After upgrading to V6.0.0, Video is able to play in all devices
