### ISSUE TITLE
java.lang.IndexOutOfBoundsException: index=1 count=0

### ISSUE THREAD

**Issue by joachimwedin** [TheWidlarzGroup/react-native-video#3192]
# Bug
After swapping over to using ExoPlayer some of our uses are getting a crash:

```
java.lang.IndexOutOfBoundsException: index=1 count=0
        at android.view.ViewGroup.addInArray(ViewGroup.java:5606)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5499)
        at android.view.ViewGroup.addView(ViewGroup.java:5296)
        at com.brentvatne.exoplayer.ReactExoplayerView.addPlayerControl(ReactExoplayerView.java:375)
        at com.brentvatne.exoplayer.ReactExoplayerView.setControls(ReactExoplayerView.java:1389)
        at com.brentvatne.exoplayer.ReactExoplayerView$6.run(ReactExoplayerView.java:475)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8757)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

## Platform

- Android

## Environment info
Library version: 5.2.1
Device:
- Motorola Moto G Play (2021)
- OnePlus Nord N200 5G (DE2118)
- Samsung Galaxy A13 (SM-A135U)
- Samsung Galaxy S22 (SM-S901U)
- Samsung Galaxy A53 5G (SM-A536U)
- Samsung Galaxy A14 5G (SM-A146U)
- Samsung Galaxy A13 5G (SM-S136DL)

**Comment by freeboub** [comment]
Is this something reproduced on V6.0.0.alpha ? you also need to provide a sample if reproduced on V6 please

**Comment by joachimwedin** [comment]
After upgrading to V6.0.0-alpha.7 the problem no longer exists
