### ISSUE TITLE
Error 24003 on Android 11 when paused

### ISSUE THREAD

**Issue by nicolaosm** [TheWidlarzGroup/react-native-video#3237]
# Bug

## Platform
Android 11

## Environment info
Library version: V6 - Beta 4

Device: 
Pixel 4

Emulator Screenshot: 
https://cln.sh/6HzmH2Db

## Steps To Reproduce
1. Build Basic example on device.
2. Pause video then wait few seconds. We get an error and we can not play video anymore.

After that, we can not play video anymore unless we press on play button multiple times, and we get `"ExoPlaybackException: ERROR_CODE_DECODING_FAILED"` with error 24003.

## Expected behaviour
1. Pausing video should not cause error
2. Playing video after pause should work immediately from first click.

## Reproducible sample code
Just use Basic Example provided by repo.

## Video sample
https://cln.sh/kr2r5PGR

## Error Log
```
Video Stream Error:  {"error": {"errorCode": "24003", "errorException": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(3, null, null, video/avc, avc1.4D401F, 2800000, null, [1280, 720, -1.0, null], [-1, -1]), format_supported=YES", "errorStackTrace": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(3, null, null, video/avc, avc1.4D401F, 2800000, null, [1280, 720, -1.0, null], [-1, -1]), format_supported=YES

```

**Comment by nicolaosm** [comment]
Over 20% of android users are still on Android 11. I believe this issue is critical for release @freeboub 
Thanks!

**Comment by GhayoorUlHaq** [comment]
Getting same issue 🙁

**Comment by freeboub** [comment]
Can you provide a sample stream please ?

**Comment by nicolaosm** [comment]
Its the repo base example. It will happen on any video in that project.

In my [screen recording above](https://cln.sh/kr2r5PGR) i showed it happening on the first video in the base example. (Broadchurch.mp4 i think)

**Comment by freeboub** [comment]
Ok, sorry, but is it happening on real device also ?

**Comment by nicolaosm** [comment]
I don't have any physical Android 11. But it happens every time on simulator. Can you try it on Android 11 emulator on your end please?

**Comment by nicolaosm** [comment]
This has been really problematic as its breaking the whole video functionality on any Android 11 version.
More than 20% of android users are on this version. Android 11 is only from 2020.

Any suggestions @KrzysztofMoch @freeboub ?

Thanks

**Comment by nicolaosm** [comment]
I tested again with the latest beta version and added error log in my initial bug report above. Hope that helps.

**Comment by GhayoorUlHaq** [comment]
yea issue still happening 😞, any update ?

**Comment by KrzysztofMoch** [comment]
I was able to reproduce this but I am not sure what is the source of it 🙁

**Comment by freeboub** [comment]
I merged yesterday following PR: https://github.com/react-native-video/react-native-video/pull/3416
It can fix the issue, please let me know if you still reproduce the issue

**Comment by AlexIkonnikov** [comment]
@freeboub Hi! I use code from PR [#3416](https://github.com/react-native-video/react-native-video/pull/3416) as patch but error persisted.
Android 11

**Comment by AlexIkonnikov** [comment]
Hmm. I have almost the same problem:

```
{
   "error":{
      "errorStackTrace":"androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640033, -1, null, [1920, 1920, 50.0, null], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:601)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loop(Looper.java:223)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: OMX.MS.AVC.Decoder\n\tat androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1862)\n\tat androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:837)\n\tat androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:852)\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1047)\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:522)\n\t... 3 more\nCaused by: android.media.MediaCodec$CodecException: Error 0x90000002\n",
      "errorCode":"24003",
      "errorException":"androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.640033, -1, null, [1920, 1920, 50.0, null], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES",
      "errorString":"ExoPlaybackException: ERROR_CODE_DECODING_FAILED"
   }
}
```

but value in `format_supported` is `NO_EXCEEDS_CAPABILITIES`. This is not the same as stated in the original issue.

Android 11, react-native-video@v6.0.0-beta.8

FYI @freeboub

**Comment by freeboub** [comment]
@AlexIkonnikov your video is 1920x1920 50fps. It is a strange format, that's why you have this error I think... Device is not able to decode it...
I don't think that is the same issue that the original issue ...

**Comment by joshuaben** [comment]
Is there a resolution to this issue?
Its a bit of a show stopper.


`ExoPlaybackException: ERROR_CODE_DECODING_FAILED`

```
androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(3, null, null, video/avc, avc1.640029, 1638566, null, [640, 360, 29.97003, null], [-1, -1]), format_supported=YES
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:601)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:223)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: c2.android.avc.decoder
	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1862)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:837)
	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:852)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1047)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:522)
	... 3 more
Caused by: java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
	at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2855)
	at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:101)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1224)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:818)
	... 6 more
```

**Comment by chienvuvan99** [comment]
Getting same issue 🙁

react-native-video": "^6.0.0

**Comment by KrzysztofMoch** [comment]
This issue is hard one 🥲 - I tried to debug and fix it but without success ...

**Comment by freeboub** [comment]
I am wondering if useTextureView={false} can fix the issue ?

**Comment by KrzysztofMoch** [comment]
It should be reproduced in our sample - so You or I can check

**Comment by freeboub** [comment]
Can you try this patch on your side please ?

```diff
diff --git a/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java b/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
index 5392a9ae..d1ef3977 100644
--- a/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
+++ b/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java
@@ -1160,6 +1160,9 @@ public class ReactExoplayerView extends FrameLayout implements
 
     private void resumePlayback() {
         if (player != null) {
+            if (playerNeedsSource) {
+                reloadSource();
+            }
             if (!player.getPlayWhenReady()) {
                 setPlayWhenReady(true);
             }
```

I checked exoplayer sample on emulator / android 11. The decoder error also happens during pause.
This patch allow to restart the playback when we resume the playback and a playback error happened.
It looks like a workaround, but it will be hard to do better... and I am not 100% sure of the side effects.

Note: I had `useTextureView={false}` activated

**Comment by NguyenHoangMinhkkkk** [comment]
hi. im using 

"react-native-video": "^6.1.2"
"react-native": "0.68.7"
"itsnubix/react-native-video-controls"

Device: Real device Pixel 3a (OS Android 12)

// source picked from device -> state.videoSource.path => "content://media/external/video/media/1000000066"
// the video picked also have real path (don't know it it usable or not ?) "realPath": 

```
        <VideoPlayer
          key={String(state.videoSource.path)}
          disableBack
          controlTimeoutDelay={3000}
          playInBackground={false}
          source={{uri: String(state.videoSource.path)}}
          showOnStart
          showOnEnd
          isFullscreen={false}
          playWhenInactive={false}
          paused
          containerStyle={styles.videoPlayer}
          useTextureView
          renderToHardwareTextureAndroid
          onError={e => {
            console.log(
              '==========number-logName=======',
              JSON.stringify(e, undefined, 2),
            );
          }}
        />
```
and here is the error stacktrace.

```
  "error": {
    "errorStackTrace": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/hevc, hvc1.1.6.L153.B0, -1, null, [1920, 1080, 30.061201, ColorInfo(BT601, Full range, SDR SMPTE 170M, false)], [-1, -1]), format_supported=YES\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:601)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loopOnce(Looper.java:201)\n\tat android.os.Looper.loop(Looper.java:288)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: c2.qti.hevc.decoder\n\tat androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1862)\n\tat androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:837)\n\tat androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:852)\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1047)\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:522)\n\t... 4 more\nCaused by: android.media.MediaCodec$CodecException: Error 0x1\n\tat android.media.MediaCodec.native_queueInputBuffer(Native Method)\n\tat android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2634)\n\tat androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecBufferEnqueuer.doQueueInputBuffer(AsynchronousMediaCodecBufferEnqueuer.java:227)\n\tat androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecBufferEnqueuer.doHandleMessage(AsynchronousMediaCodecBufferEnqueuer.java:200)\n\tat androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecBufferEnqueuer.access$000(AsynchronousMediaCodecBufferEnqueuer.java:47)\n\tat androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecBufferEnqueuer$1.handleMessage(AsynchronousMediaCodecBufferEnqueuer.java:96)\n\tat android.os.Handler.dispatchMessage(Handler.java:106)\n\t... 3 more\n",
    "errorCode": "24003",
    "errorException": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/hevc, hvc1.1.6.L153.B0, -1, null, [1920, 1080, 30.061201, ColorInfo(BT601, Full range, SDR SMPTE 170M, false)], [-1, -1]), format_supported=YES",
    "errorString": "ExoPlaybackException: ERROR_CODE_DECODING_FAILED"
  }
}
```

**Comment by freeboub** [comment]
@NguyenHoangMinhkkkk did you try useTextureView={false} ?

**Comment by NguyenHoangMinhkkkk** [comment]
> @NguyenHoangMinhkkkk did you try useTextureView={false} ?

not yet try it. but without useTextureView, just rebuild the app work fine again (reload or yarn start again not fix the problem). or the error comming just randomly ?

**Comment by freeboub** [comment]
> > @NguyenHoangMinhkkkk did you try useTextureView={false} ?
> 
> not yet try it. but without useTextureView, just rebuild the app work fine again (reload or yarn start again not fix the problem). or the error comming just randomly ?

No, it was 100% reproducible on the emulator when I tried... Also reproducible with media3 sample 🤷

**Comment by quang8122000** [comment]
I has the same this error in android 11 when I pause video 
 ```typescript
          <Video
            repeat={true}
            muted={isMute}
            ref={refVideo}
            controls={__DEV__ ? true : false}
            disableFocus={true}
            hideShutterView={true}
            source={{uri: "https://alta-s3.dev-altamedia.com/sta-as-mtc/qc/Medias/TuLanh_Aquafina.1721030613a4cf000085c0028db01508dca4a49f31.172119962397eb00003e9cfa16d5f508dca62e212f.mp4?AWSAccessKeyId=MxmWebApi&Expires=1722307098&Signature=OMohgBPkqEqMtZfV8TzSwEutH8E%3D"}}
            onLoadStart={() => {
              setLoading(true);
            }}
            onReadyForDisplay={() => {
              setLoading(false);
            }}
            onError={err => {
              console.log('play video error', err);
              console.log('play video source error', sourceVideo);
            }}
            style={{
              height: _style.height,
              width: _style.width,
            }}
            resizeMode={resizeMode}
          />
  ```
 And this is my code error :
  ```typescript
   "error": {
    "errorStackTrace": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/hevc, hvc1.1.6.L153.B0, -1, null, [1920, 1080, 30.061201, ColorInfo(BT601, Full range, SDR SMPTE 170M, false)], [-1, -1]), format_supported=YES\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:601)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loopOnce(Looper.java:201)\n\tat android.os.Looper.loop(Looper.java:288)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: c2.qti.hevc.decoder\n\tat androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1862)\n\tat androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:837)\n\tat androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:852)\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1047)\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:522)\n\t... 4 more\nCaused by: android.media.MediaCodec$CodecException: Error 0x1\n\tat android.media.MediaCodec.native_queueInputBuffer(Native Method)\n\tat android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2634)\n\tat androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecBufferEnqueuer.doQueueInputBuffer(AsynchronousMediaCodecBufferEnqueuer.java:227)\n\tat androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecBufferEnqueuer.doHandleMessage(AsynchronousMediaCodecBufferEnqueuer.java:200)\n\tat androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecBufferEnqueuer.access$000(AsynchronousMediaCodecBufferEnqueuer.java:47)\n\tat androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecBufferEnqueuer$1.handleMessage(AsynchronousMediaCodecBufferEnqueuer.java:96)\n\tat android.os.Handler.dispatchMessage(Handler.java:106)\n\t... 3 more\n",
    "errorCode": "24003",
    "errorException": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(2, null, null, video/hevc, hvc1.1.6.L153.B0, -1, null, [1920, 1080, 30.061201, ColorInfo(BT601, Full range, SDR SMPTE 170M, false)], [-1, -1]), format_supported=YES",
    "errorString": "ExoPlaybackException: ERROR_CODE_DECODING_FAILED"
  }
}
