### ISSUE TITLE
Vide  is not playing in Play Store build

### ISSUE THREAD

**Issue by za-rakib** [TheWidlarzGroup/react-native-video#3240]
##Description:
I'm facing an issue where React Native Video plays correctly during local testing but fails to play in a Play Store build.

Environment:

React Native: 0.66
React Native Video:5.2.0

Build and publish the app to the Play Store.
Install it from the Play Store.
Open the app and try to play a video.
Expected Behavior:
Video should play smoothly when installed from the Play Store, similar to local testing.

Actual Behavior:
Video doesn't play when installed from the Play Store, showing a blank screen. 
I am even trying to give free video links. The video doesn't play either. But the video link is getting fine.

Additional Info:

com.google.android.exoplayer2.ExoPlaybackException: Source error
onStateChanged: playWhenReady=false, playbackState=idle
Playback error
 com.google.android.exoplayer2.ExoPlaybackException: Source error
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loopOnce(Looper.java:226)

**Comment by freeboub** [comment]
Can you give a longer logcat, there is maybe other clue before. (Can I suspect http issue video url ? )

**Comment by za-rakib** [comment]
## full error
onStateChanged: playWhenReady=true, playbackState=idle
 { e: undefined }
 onStateChanged: playWhenReady=true, playbackState=buffering


Playback error     

com.google.android.exoplayer2.ExoPlaybackException: Source error
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by:com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404
at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:317)
at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201)
at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64)
at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:177)
at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:415)

## my video url 

 source={{
               uri: `https://customer-${Config.CUSTOMER_ID}.cloudflarestream.com/${videoId}/manifest/video.${
             Platform.OS === 'ios' ? 'm3u8' : 'mpd'
             }`,
           }}

**Comment by freeboub** [comment]
You receive an error 404... Like if the url is not correct. Nothing can be done in react native video.
I think you should display the url used to debug the issue.

**Comment by za-rakib** [comment]
Thanks , solved
