### ISSUE TITLE
Video not getting play in FlatList

### ISSUE THREAD

**Issue by HemangiVekaria** [TheWidlarzGroup/react-native-video#3272]
# Bug

1. Videos is not get play in flatList. I have main screen which has one FlatList and that flatlist contain multiple horizontal flatlist. that horizontal flatlist has video component. I am using react-native-video. Videos are from AWS. I can see thumbnail of that videos but videos are not getting play

## Platform

* iOS
* Android

## Environment info

   "react-native-video": "^6.0.0-alpha.6",
Device: All android and ios devices

## Expected behaviour
I want to play all videos from AWS to <Video> inside flatlist

this is my video component
` <Video
                hideShutterView={true}
                resizeMode={"stretch"}
                ref={videoRef}
                style={{ width: 175, height: 300, borderRadius: 10 }}
                source={{ uri: displayVideoUri }}
                repeat={true}
                paused={false}
              />`

and this is my flatlist 
`
   <FlatList
        style={styles.section_one_scroll}
        data={props.sectionData.items}
        numColumns={1}
        horizontal={true}
        showsHorizontalScrollIndicator={false}
        renderItem={(item) => {
return // here video component
}`

sometime it return this error:

 _

### {"error": {"errorCode": "24001", "errorException": "com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.42C028, -1, null, [1920, 1080, 25.0], [-1, -1]), format_supported=YES", "errorStackTrace": "com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.42C028, -1, null, [1920, 1080, 25.0], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: c2.qti.avc.decoder, Format(1, null, null, video/avc, avc1.42C028, -1, null, [1920, 1080, 25.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1030)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1450)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:877)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:963)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
        ... 4 more
Caused by: android.media.MediaCodec$CodecException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2322)
        at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:160)
        at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:50)
        at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:103)
        at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:108)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1108)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1019)
        ... 11 more
", "errorString": "ExoPlaybackException: ERROR_CODE_DECODER_INIT_FAILED"}}
 LOG  load errror :::  {"error": {"errorCode": "24001", "errorException": "com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.42C028, -1, null, [1920, 1080, 30.000967], [-1, -1]), format_supported=YES", "errorStackTrace": "com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.42C028, -1, null, [1920, 1080, 30.000967], [-1, -1]), format_supported=YES
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: c2.qti.avc.decoder, Format(1, null, null, video/avc, avc1.42C028, -1, null, [1920, 1080, 30.000967], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1030)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1450)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:877)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:963)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
        ... 4 more
Caused by: android.media.MediaCodec$CodecException: start failed
        at android.media.MediaCodec.native_start(Native Method)
        at android.media.MediaCodec.start(MediaCodec.java:2322)
        at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:160)
        at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:50)
        at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:103)
        at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:108)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1108)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1019)
        ... 11 more
", "errorString": "ExoPlaybackException: ERROR_CODE_DECODER_INIT_FAILED"}}

_`
`

**Comment by HemangiVekaria** [comment]
I updated react-native-video to 5.2.1 and now videos are getting played in Flatlist.

Now facing another issue like i have Horizontal flatlist so when i scroll horizontally to the 3rd or 4th video and then back to first video then video start loading. 

I want is i don't want to load videos on horizontal scroll. Once it load then it should play until navigate to different screen even when scroll it should not load again

Can anyone please help with this?

**Comment by sumitGupta101993** [comment]
it will happening in android as soon as the renderitem goes out of the visible area it unmount the view and while returning it reload. 
there is a hack on this but after applying cross check memory consumption
there is a props in flatlist removeSubclippedView set it false 
In IOS, it is false that why this issue happen in android 

Note: please test on Android 13 properly

**Comment by HemangiVekaria** [comment]
By setting removeClippedSubviews={false} for android is not event loading content in views. It shows blank views

**Comment by nawalpro** [comment]
Same problem for me but only on IOS emulator, the hack you told with FlatList element does not work for me, any advice pls ? 
I try to play audio local files when a button is pressed in carousel component. I use react-native-video : 5.2.1.

**Comment by freeboub** [comment]
Here is a flatList sample which seems working fine with V6.2.0: https://github.com/freeboub/react-native-video-flatlist-sample

**Comment by freeboub** [comment]
I close this ticket, let me know if I need to reopen it.
