### ISSUE TITLE
Version 6.0.0.beta.0 crash android (No static method registerReceiver)

### ISSUE THREAD

**Issue by angelos3lex** [TheWidlarzGroup/react-native-video#3379]
# Bug
Trace:
```
java.lang.NoSuchMethodError: No static method registerReceiver(Landroid/content/Context;Landroid/content/BroadcastReceiver;Landroid/content/IntentFilter;I)Landroid/content/Intent; in class Landroidx/core/content/ContextCompat; or its super classes (declaration of 'androidx.core.content.ContextCompat' appears in /data/app/~~EuPfbquf3gOXwXBheHoBag==/com.mypackage.name-rZ4OpXoUVbKkJP0POmF1ag==/base.apk)
    at com.brentvatne.receiver.AudioBecomingNoisyReceiver.setListener(AudioBecomingNoisyReceiver.java:30)
    at com.brentvatne.exoplayer.ReactExoplayerView.initializePlayerCore(ReactExoplayerView.java:635)
    at com.brentvatne.exoplayer.ReactExoplayerView.lambda$initializePlayer$6$com-brentvatne-exoplayer-ReactExoplayerView(ReactExoplayerView.java:547)
    at com.brentvatne.exoplayer.ReactExoplayerView$$ExternalSyntheticLambda11.run(Unknown Source:6)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7656)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
This is tested and happening even when I'm presenting a video through native assets or through a file. Not happening on 5.x version.

## Platform
Which player are you experiencing the problem on:
* Android

## Environment info

Library version: 6.0.0-beta.0
Device: Samsung tab A8, android 10
React-Native: 0.72.6
buildToolsVersion = "33.0.0"
minSdkVersion = 22
compileSdkVersion = 33
targetSdkVersion = 33
kotlinVersion = "1.7.20"
ndkVersion = "21.3.6528147"
 implementation 'androidx.appcompat:appcompat:1.0.0'
newArchEnabled: false
hermesEnabled: true
 
## Reproducible sample code

Just rendering a video:
```
<Video  
  controls={false}
  repeat={false}
  rate={1}
  paused={false}
  resizeMode={ResizeMode.CONTAIN}
  source={...}
  onEnd={this.onVideoEnd}
  onError={this.onVideoError}
/>
```

## Expected behaviour
Video should be displayed, not crashing

**Comment by freeboub** [comment]
did you saw following discussion ?  https://github.com/react-native-video/react-native-video/issues/3343

**Comment by angelos3lex** [comment]
nice the fix mentioned in [comment](https://github.com/react-native-video/react-native-video/issues/3343#issuecomment-1813962778) fixed my side too !
