### ISSUE TITLE
Example build failed on android

### ISSUE THREAD

**Issue by Kavosh-m** [TheWidlarzGroup/react-native-video#3469]
# Bug

## Platform
* Android

## Environment info
* OS: windows

Library version: 6.0.0-beta.3
Device: SAMSUNG A546E - android 14

## Steps To Reproduce

1. Clone project from github
2.  In the root directory run `yarn xbasic install` then, `yarn xbasic android`

## Expected behaviour

1. project successfully built

## Error

```
transform[stderr]: Could not resolve "E:\ReactNative\react-native-video\src\index" in file E:\ReactNative\react-native-video\examples\basic\src\VideoPlayer.tsx.
transform[stderr]: Could not resolve "E:\ReactNative\react-native-video\src\index" in file E:\ReactNative\react-native-video\examples\basic\src\MultiValueControl.tsx.
 BUNDLE  src/index.js

error: Error: Unable to resolve module @babel/runtime/helpers/interopRequireDefault from E:\ReactNative\react-native-video\src\index.ts: @babel/runtime/helpers/interopRequireDefault could not be found within the project.
> 1 | import Video from './Video';
    | ^
  2 | export {VideoDecoderProperties} from './VideoNativeComponent';
  3 | export * from './types';
  4 | export type {VideoRef} from './Video';
    at ModuleResolver.resolveDependency (E:\ReactNative\react-native-video\examples\basic\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:153:15)
    at DependencyGraph.resolveDependency (E:\ReactNative\react-native-video\examples\basic\node_modules\metro\src\node-haste\DependencyGraph.js:279:43)
    at E:\ReactNative\react-native-video\examples\basic\node_modules\metro\src\lib\transformHelpers.js:176:21
    at resolveDependencies (E:\ReactNative\react-native-video\examples\basic\node_modules\metro\src\DeltaBundler\buildSubgraph.js:56:25)
    at visit (E:\ReactNative\react-native-video\examples\basic\node_modules\metro\src\DeltaBundler\buildSubgraph.js:107:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 8)
    at async visit (E:\ReactNative\react-native-video\examples\basic\node_modules\metro\src\DeltaBundler\buildSubgraph.js:116:5)
    at async Promise.all (index 2)
    at async visit (E:\ReactNative\react-native-video\examples\basic\node_modules\metro\src\DeltaBundler\buildSubgraph.js:116:5)
```

**Comment by freeboub** [comment]
You need to do a yarn build is the root folder to ensure ts is well transpiled ! Documentation to be updated

**Comment by Kavosh-m** [comment]
> You need to do a yarn build is the root folder to ensure ts is well transpiled ! Documentation to be updated

So I did the following in root directory:

1. `yarn install`
2. `yarn build`
3. `yarn xbasic install`
4. `yarn xbasic android`

and unfortunately the issue still exists

**Comment by coofzilla** [comment]
Having the same issue; but, on `ios`

**Comment by freeboub** [comment]
Issue comes from this line : https://github.com/react-native-video/react-native-video/blob/6a49cba273fa0a47e106f4abb8caeb4ab6dbe4c8/examples/basic/metro.config.js#L33

If you remove it it should fix the issue.

No need to patch the project as https://github.com/react-native-video/react-native-video/pull/3470 doesn't have the issue !

**Comment by freeboub** [comment]
I just cloned and build sample on android, It should be fixed now, let's close the issue. ping me if I should reopen it.
