### ISSUE TITLE
Video error on Android 11

### ISSUE THREAD

**Issue by nicolaosm** [TheWidlarzGroup/react-native-video#3491]
# Bug

## Platform
Which player are you experiencing the problem on:
* Android Version 11

## Environment info
Library version: v6 - Beta 4
Device: Google Pixel

## Steps To Reproduce
Just play any video on Android 11.0
It gives an error:
`ExoPlaybackException: ERROR_CODE_DECODING_FAILED"`

## Expected behaviour
It should work normally without and error.

## Reproducible sample code
Any video on Android 11 will cause the issue.

**Comment by nicolaosm** [comment]
@freeboub @KrzysztofMoch I believe this is critical for release! Thanks

**Comment by KrzysztofMoch** [comment]
Will check this 👀

**Comment by nicolaosm** [comment]
**Update after further testing**

Issue Happens in the examples/basic as well.
To replicate the issue, just pause the video and wait few seconds. The error will appear, and the video will not play anymore.

**Comment by KrzysztofMoch** [comment]
Hey @nicolaosm, I was able to reproduce this - after some debugging it seems that source of crash is ExoPlayer issue with codec. Unfortunately I am not able to fix/do something about this 😕

@freeboub maybe you will had some idea ?

**Comment by nicolaosm** [comment]
Just a quick update @KrzysztofMoch @freeboub . I purchased two android devices from ebay, one with android 11 and one with android 12. Im waiting for them to be delivered next week. As soon as I get them ill confirm if this issue and the one in #3499 are happening on real device.

**Comment by coofzilla** [comment]
> Hey @nicolaosm, I was able to reproduce this - after some debugging it seems that source of crash is ExoPlayer issue with codec. Unfortunately I am not able to fix/do something about this 😕
> 
> @freeboub maybe you will had some idea ?

I believe there is a related playback issue for `hls` due to [ffmpeg](https://trac.ffmpeg.org/ticket/10786) hard coding the codec. I've only seen this issue on `android`. but I got this error:

```json
  "error": {
    "errorStackTrace": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(7, null, null, video/avc, avc1.4D4033, 10285391, null, [4096, 1744, -1.0, null], [-1, -1]), format_supported=YES\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:601)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loopOnce(Looper.java:201)\n\tat android.os.Looper.loop(Looper.java:288)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: androidx.media3.exoplayer.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: c2.goldfish.h264.decoder, Format(7, null, null, video/avc, avc1.4D4033, 10285391, null, [4096, 1744, -1.0, null], [-1, -1])\n\tat androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1055)\n\tat androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:556)\n\tat androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1504)\n\tat androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:997)\n\tat androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:988)\n\tat androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:803)\n\tat androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:852)\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1047)\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:522)\n\t... 4 more\nCaused by: java.lang.IllegalArgumentException\n\tat android.media.MediaCodec.native_configure(Native Method)\n\tat android.media.MediaCodec.configure(MediaCodec.java:2215)\n\tat android.media.MediaCodec.configure(MediaCodec.java:2131)\n\tat androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:156)\n\tat androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:50)\n\tat androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:103)\n\tat androidx.media3.exoplayer.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:113)\n\tat androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1134)\n\tat androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1044)\n\t... 12 more\n",
    "errorCode": "24001",
    "errorException": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(7, null, null, video/avc, avc1.4D4033, 10285391, null, [4096, 1744, -1.0, null], [-1, -1]), format_supported=YES",
    "errorString": "ExoPlaybackException: ERROR_CODE_DECODER_INIT_FAILED"
  }
  ```
  
  using this `https://bitmovin-a.akamaihd.net/content/sintel/hls/playlist.m3u8`

**Comment by nicolaosm** [comment]
Confirmed: Issue is only on simulator and does not happen on real device.

**Comment by vatsal1302** [comment]
Hello @nicolaosm i am using Android 9 in that i have this URL
=> http://192.168.1.254/Movie/20240429182812_000029.MP4

and i got this error 

{
errorCode: "22004"
errorException: "androidx.media3.exoplayer.ExoPlaybackException: Source error"
errorStackTrace: "androidx.media3.exoplayer.ExoPlaybackException: Source error"
errorString: "ExoPlaybackException: ERROR_CODE_IO_BAD_HTTP_STATUS"
}

can you provide me the solution for this mp4 File??

**Comment by joshuaben** [comment]
This is happening on Fire TV, so a real device (adb connected to Fire TV) via:
`"react-native-video": "6.0.0-rc.0"`

`errorCode: "24003"`
```
androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(3, null, null, video/avc, avc1.640029, 1638566, null, [640, 360, 29.97003, null], [-1, -1]), format_supported=YES
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:601)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:223)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: c2.android.avc.decoder
	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1862)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:837)
	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:852)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1047)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:522)
	... 3 more
Caused by: java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
	at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2855)
	at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:101)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1224)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:818)
	... 6 more

**Comment by YasirAliSmit** [comment]
i am facing this issues on phyical devices android 12 how to fix it? {"error": {"errorCode": "24001", "errorException": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.42C033, -1, null, [3412, 1920, 25.0, ColorInfo(BT709, Limited range, Unset color transfer, false)], [-1, -1])

**Comment by transli** [comment]
got the same issue, physical device android 11 
 {"error": {"errorCode": "24003", "errorException": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64002A, -1, null, [1080, 1920, 29.971592, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false)], [-1, -1]), format_supported=YES", "errorStackTrace": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64002A, -1, null, [1080, 1920, 29.971592, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false)], [-1, -1]), format_supported=YES
        at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:601)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: c2.android.avc.decoder
        at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1862)
        at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:837)
        at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:852)
        at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1047)
        at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:522)
        ... 3 more
Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2855)
        at androidx.media3.exoplayer.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:101)
        at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1224)
        at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:818)
        ... 6 more
", "errorString": "ExoPlaybackException: ERROR_CODE_DECODING_FAILED"}}

**Comment by freeboub** [comment]
Can you please try with useTextureView={false} ?

**Comment by PadovaY** [comment]
Facing similar issue when returning from background, samsung device, a `FlatList` of videos.
Using `useTextureView={false}` doesn't help.

error: 
```
{"error": {"errorCode": "24003", "errorException": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.42C01F, -1, null, [480, 600, 59.99917, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false)], [-1, -1]), format_supported=YES", "errorStackTrace": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.42C01F, -1, null, [480, 600, 59.99917, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false)], [-1, -1]), format_supported=YES
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:601)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: c2.qti.avc.decoder
	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1862)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:837)
	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:852)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1047)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:522)
	... 4 more
Caused by: android.media.MediaCodec$CodecException: Error 0xffffffe0
", "errorString": "ExoPlaybackException: ERROR_CODE_DECODING_FAILED"},
```

**Comment by ardacmen** [comment]
useTextureView={false} doesn't help me either, any suggestion for issue?

**Comment by quangtuan28200** [comment]
same issue, i got this:

> {"errorStackTrace":"androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64002A, -1, null, [1920, 1080, 59.988518, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false)], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:601)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loopOnce(Looper.java:223)\n\tat android.os.Looper.loop(Looper.java:324)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: OMX.qcom.video.decoder.avc\n\tat androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1862)\n\tat androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:837)\n\tat androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:852)\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1047)\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:522)\n\t... 4 more\nCaused by: android.media.MediaCodec$CodecException: Error 0xffffffe0\n","errorCode":"24003","errorException":"androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64002A, -1, null, [1920, 1080, 59.988518, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false)], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES","errorString":"ExoPlaybackException: ERROR_CODE_DECODING_FAILED"}
![image](https://github.com/TheWidlarzGroup/react-native-video/assets/74997976/8e000141-8a1a-49ee-a064-2973251c31c0)

**Comment by vvdodiya** [comment]
Any solution?
I am getting the same error. I am using react-native-video version: "6.4.3" 
Thanks in advance.

**Comment by mfapproach** [comment]
Same issue, my use case is for digital signage. react-native-video version 6.4.3

`Video error occured {"errorCode": "24003", "errorException": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64001F, -1, null, [720, 1280, 29.997833, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES", "errorStackTrace": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64001F, -1, null, [720, 1280, 29.997833, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:623)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: OMX.amlogic.avc.decoder.awesome2
	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1915)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:848)
	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:940)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1112)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:544)
	... 4 more
Caused by: android.media.MediaCodec$CodecException: Error 0x80001000
", "errorString": "ExoPlaybackException: ERROR_CODE_DECODING_FAILED"}`


Seems to happen at random, always when more than 1 video is rendered on the screen.

**Comment by seyedmostafahasani** [comment]
I noticed we have an issue on Android 11.
I will try to find out what the problem is.

**Comment by mfapproach** [comment]
Even when i created a custom native module, I was running into the same problems with exoplayer. I thought maybe something with a memory issue, but it doesnt seem to be after monitoring.

**Comment by polaris018** [comment]
+1

**Comment by dipankur007** [comment]
This should not be closed. I am still facing this issue.
