### ISSUE TITLE
[BUG]: souce params not loading network resource， but local resource can be loaded

### ISSUE THREAD

**Issue by 18482048531** [TheWidlarzGroup/react-native-video#3517]
### Version

v5 (Stable)

### What platforms are you having the problem on?

iOS, Android

### Architecture

Old architecture

### What happened?

 <Video
              source={{ uri: url }}
              // source={require('../../assets/bef411bbacfe6c1a304091d71de382de.mp4')}
              // source={{ uri: item.content }}
              style={{
                width: '100%',
                height,
                paddingHorizontal: 0,
                position: 'absolute',
              }}
            />

### Reproduction

fisrt source，loading failed.
but local source ，example the second，it is successful.
 what is question ,who konw thanks very much!!!   I have crashed

**Comment by KrzysztofMoch** [comment]
Hey @18482048531, cloud you try v6 ? v5 is currently unsupported

**Comment by KrzysztofMoch** [comment]
With `^6.0.0-beta.5` loading network resource is working

**Comment by 18482048531** [comment]
There are also issues with 6.0.0-beta.5 
error：{"error": {"errorCode": "22001", "errorException": "androidx.media3.exoplayer.ExoPlaybackException: Source error", "errorStackTrace": "androidx.media3.exoplayer.ExoPlaybackException: Source error
        at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:684)
        at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:656)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:224)
        at android.os.Looper.loop(Looper.java:318)
        at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.datasource.HttpDataSource$HttpDataSourceException: java.io.IOException: java.util.concurrent.ExecutionException: java.net.SocketException: Connection reset
        at androidx.media3.datasource.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:321)
        at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:272)
        at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
        at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1006)
        at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.IOException: java.util.concurrent.ExecutionException: java.net.SocketException: Connection reset
        at androidx.media3.datasource.okhttp.OkHttpDataSource.executeCall(OkHttpDataSource.java:489)
        at androidx.media3.datasource.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:316)
        ... 7 more
Caused by: java.util.concurrent.ExecutionException: java.net.SocketException: Connection reset
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:588)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:567)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:113)
        at androidx.media3.datasource.okhttp.OkHttpDataSource.executeCall(OkHttpDataSource.java:484)
        ... 8 more
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:191)
        at java.net.SocketInputStream.read(SocketInputStream.java:143)
        at okio.InputStreamSource.read(JvmOkio.kt:94)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
        at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:180)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        ... 3 more
", "errorString": "ExoPlaybackException: ERROR_CODE_IO_NETWORK_CONNECTION_FAILED"}}

**Comment by mittalkamal29** [comment]
Hi 
I am facing same issue in 6.0.0

`{"error": {"errorCode": "22001", "errorException": "androidx.media3.exoplayer.ExoPlaybackException: Source error", "errorStackTrace": "androidx.media3.exoplayer.ExoPlaybackException: Source error
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:717)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:689)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.datasource.HttpDataSource$HttpDataSourceException: java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: unexpected end of stream on http://127.0.0.1:37289/...
	at androidx.media3.datasource.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:321)
	at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:275)
	at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
	at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1029)
	at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: unexpected end of stream on http://127.0.0.1:37289/...
	at androidx.media3.datasource.okhttp.OkHttpDataSource.executeCall(OkHttpDataSource.java:489)
	at androidx.media3.datasource.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:316)
	... 7 more
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: unexpected end of stream on http://127.0.0.1:37289/...
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:592)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:571)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:111)
	at androidx.media3.datasource.okhttp.OkHttpDataSource.executeCall(OkHttpDataSource.java:484)
	... 8 more
Caused by: java.io.IOException: unexpected end of stream on http://127.0.0.1:37289/...
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:210)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	... 3 more
Caused by: java.io.EOFException: \\n not found: limit=0 content=…
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:339)
	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:180)
	... 16 more
", "errorString": "ExoPlaybackException: ERROR_CODE_IO_NETWORK_CONNECTION_FAILED"}}`

**Comment by freeboub** [comment]
"unexpected end of stream"  your local server doesn't behave as expected I think

**Comment by mittalkamal29** [comment]
@freeboub Yes, you are correct. i found my issue, and it is working fine now. Issue was related to path which i was passing.
