### ISSUE TITLE
[BUG]: Cannot get UIManager because the context doesn't contain an active CatalystInstance.

### ISSUE THREAD

**Issue by timothy-pham** [TheWidlarzGroup/react-native-video#3864]
### Version

6.1.2

### What platforms are you having the problem on?

Android

### Architecture

Old architecture

### What happened?

Cannot play Video with uri string
"react-native": "0.70.6",

It is working fine with require(...) but with uri string, Video just show black screen.

```
function useFileDownload(uri: string) {
  const [path, setPath] = useState<any>(null)
  const askPermission = async () => {
    await requestPermissionWriteAndRead()
  }
  useEffect(() => {
    askPermission()
    RNFetchBlob.config({
      fileCache: true,
      appendExt: 'mp4',
    })
      .fetch('GET', uri)
      .progress((received, total) => {
        console.log('progress', received / total)
      })
      .then((res) => {
        setPath(res.path())
      })
      .catch((error) => {
        console.log('downfile error', error)
      })
  }, [])

  if (path) {
    return path
  }
}

export default useFileDownload

 const videoUrl = useFileDownload(video)

const videoRef = useRef<VideoRef>(null)
  const background = {
    uri: 'http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4',
  }
  // const background = { uri: videoUrl, type: 'mp4' }
  // const background = require('@@/assets/videos/bannerdamsen.mp4')

<Video
        source={background}
        // Store reference
        ref={videoRef}
        // Callback when remote video is buffering
        onBuffer={(buffer) => {
          console.log('buffer', buffer)
        }}
        // Callback when video cannot be loaded
        onError={(error) => {
          console.log('error', error)
        }}
        style={styles.backgroundVideo}
/>
```

ERROR:
 Unhandled SoftException
                                                                                                    com.facebook.react.bridge.ReactNoCrashSoftException: Cannot get UIManager because the context doesn't contain an active CatalystInstance.
                                                                                                    	at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:77)
                                                                                                    	at com.facebook.react.uimanager.UIManagerHelper.getUIManager(UIManagerHelper.java:47)
                                                                                                    	at com.brentvatne.common.react.VideoEventEmitter.receiveEvent(VideoEventEmitter.java:471)
                                                                                                    	at com.brentvatne.common.react.VideoEventEmitter.playbackRateChange(VideoEventEmitter.java:400)
                                                                                                    	at com.brentvatne.exoplayer.ReactExoplayerView.onEvents(ReactExoplayerView.java:1282)
                                                                                                    	at androidx.media3.exoplayer.ExoPlayerImpl.lambda$new$0$androidx-media3-exoplayer-ExoPlayerImpl(ExoPlayerImpl.java:281)
                                                                                                    	at androidx.media3.exoplayer.ExoPlayerImpl$$ExternalSyntheticLambda17.invoke(Unknown Source:4)
                                                                                                    	at androidx.media3.common.util.ListenerSet$ListenerHolder.iterationFinished(ListenerSet.java:350)
                                                                                                    	at androidx.media3.common.util.ListenerSet.handleMessage(ListenerSet.java:294)
                                                                                                    	at androidx.media3.common.util.ListenerSet.$r8$lambda$bio3pd12v5B_9b5UeFaPn9XBQ90(Unknown Source:0)
                                                                                                    	at androidx.media3.common.util.ListenerSet$$ExternalSyntheticLambda0.handleMessage(Unknown Source:2)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6669)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are: 
1. Fix react-native.config.js
module.exports = {
    dependencies: {
        'react-native-vector-icons': {
            platforms: {
                ios: null,
            },
        },
        "react-native-video": {
            platforms: {
                android: {
                    sourceDir: "../node_modules/react-native-video/android"
                }
            }
        }
    },
};
2. add android:largeHeap="true" to application AndroidManifest.xml
3. update     "react-native-reanimated": "^3.11.0"

**Comment by freeboub** [comment]
@tiendat0811 can you try to remove:
```
"react-native-video": {
platforms: {
android: {
sourceDir: "../node_modules/react-native-video/android"
}
}
}
},
};
```

This is no more necessary on 6.0.0

more generally, upgrade documentation is available here: https://thewidlarzgroup.github.io/react-native-video/updating

**Comment by freeboub** [comment]
no feedback since 2 weeks, let's close this issue
