### ISSUE TITLE
Exception: Malformed URL (RTSP)

### ISSUE THREAD

**Issue by 1280103995** [TheWidlarzGroup/react-native-video#3884]
### Version

6.1.1

### What platforms are you having the problem on?

Android

### System Version

Android 13

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

```
Playback error
     androidx.media3.exoplayer.ExoPlaybackException: Source error
         at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:717)
         at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:689)
         at android.os.Handler.dispatchMessage(Handler.java:102)
         at android.os.Looper.loopOnce(Looper.java:226)
         at android.os.Looper.loop(Looper.java:313)
         at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: androidx.media3.datasource.HttpDataSource$HttpDataSourceException: Malformed URL
         at androidx.media3.datasource.okhttp.OkHttpDataSource.makeRequest(OkHttpDataSource.java:418)
         at androidx.media3.datasource.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:311)
         at androidx.media3.datasource.DefaultDataSource.open(DefaultDataSource.java:275)
         at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
         at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1029)
         at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
         at java.lang.Thread.run(Thread.java:1012)
```
At first I thought it was an ExoPlayer issue, so I filed an [issue](https://github.com/androidx/media/issues/1427) in [androidx/media](https://github.com/androidx/media).

### Reproduction

repository link

### Reproduction

I just play like: 
```
<Video
        videoAspectRatio="16:9"
        source={{ uri: 'rtsp://192.168.43.1:1338?auth=************'}} 
      />
```

**Comment by freeboub** [comment]
Not sure how I can help with the sample stream, but you should check inside function:

`
private MediaSource buildMediaSource(Uri uri, String overrideExtension, DrmSessionManager drmSessionManager, long cropStartMs, long cropEndMs) {
`

Can you check that :
```
type = Util.inferContentType(!TextUtils.isEmpty(overrideExtension) ? "." + overrideExtension
                    : uri.getLastPathSegment());

```
return correctly CONTENT_TYPE_RTSP

an easier test would be to for rtsp type with following source:
```
<Video
        videoAspectRatio="16:9"
        source={{ uri: 'rtsp://192.168.43.1:1338?auth=************', type: 'rtsp' }} 
      />
```

**Comment by 1280103995** [comment]
> type: 'rtsp'

This property works, but I ran into other problems. Looking at ```OPTIONS 404```, it seems that this still requires some configuration?
```
09:45:37.965  E  Playback error
                   androidx.media3.exoplayer.ExoPlaybackException: Source error
                       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:684)
                       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:660)
                       at android.os.Handler.dispatchMessage(Handler.java:102)
                       at android.os.Looper.loopOnce(Looper.java:226)
                       at android.os.Looper.loop(Looper.java:313)
                       at android.os.HandlerThread.run(HandlerThread.java:67)
                   Caused by: java.io.IOException: OPTIONS 404
                       at androidx.media3.exoplayer.rtsp.RtspMediaPeriod$InternalListener.onSessionTimelineRequestFailed(RtspMediaPeriod.java:689)
                       at androidx.media3.exoplayer.rtsp.RtspClient.dispatchRtspError(RtspClient.java:322)
                       at androidx.media3.exoplayer.rtsp.RtspClient.access$700(RtspClient.java:76)
                       at androidx.media3.exoplayer.rtsp.RtspClient$MessageListener.handleRtspResponse(RtspClient.java:607)
                       at androidx.media3.exoplayer.rtsp.RtspClient$MessageListener.handleRtspMessage(RtspClient.java:515)
                       at androidx.media3.exoplayer.rtsp.RtspClient$MessageListener.lambda$onRtspMessageReceived$0$androidx-media3-exoplayer-rtsp-RtspClient$MessageListener(RtspClient.java:508)
                       at androidx.media3.exoplayer.rtsp.RtspClient$MessageListener$$ExternalSyntheticLambda0.run(Unknown Source:4)
                       at android.os.Handler.handleCallback(Handler.java:942)
                       at android.os.Handler.dispatchMessage(Handler.java:99)
                       at android.os.Looper.loopOnce(Looper.java:226) 
                       at android.os.Looper.loop(Looper.java:313) 
                       at android.os.HandlerThread.run(HandlerThread.java:67) 
                   Caused by: androidx.media3.exoplayer.rtsp.RtspMediaSource$RtspPlaybackException: OPTIONS 404
                       at androidx.media3.exoplayer.rtsp.RtspClient$MessageListener.handleRtspResponse(RtspClient.java:609)
                       at androidx.media3.exoplayer.rtsp.RtspClient$MessageListener.handleRtspMessage(RtspClient.java:515) 
                       at androidx.media3.exoplayer.rtsp.RtspClient$MessageListener.lambda$onRtspMessageReceived$0$androidx-media3-exoplayer-rtsp-RtspClient$MessageListener(RtspClient.java:508) 
                       at androidx.media3.exoplayer.rtsp.RtspClient$MessageListener$$ExternalSyntheticLambda0.run(Unknown Source:4) 
                       at android.os.Handler.handleCallback(Handler.java:942) 
                       at android.os.Handler.dispatchMessage(Handler.java:99) 
                       at android.os.Looper.loopOnce(Looper.java:226) 
                       at android.os.Looper.loop(Looper.java:313) 
                       at android.os.HandlerThread.run(HandlerThread.java:67) 
09:45:37.977  I  'onError', { error: 
                    { errorStackTrace: 'androidx.media3.exoplayer.ExoPlaybackException: Source error\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:684)\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:660)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loopOnce(Looper.java:226)\n\tat android.os.Looper.loop(Looper.java:313)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: java.io.IOException: OPTIONS 404\n\tat androidx.media3.exoplayer.rtsp.RtspMediaPeriod$InternalListener.onSessionTimelineRequestFailed(RtspMediaPeriod.java:689)\n\tat androidx.media3.exoplayer.rtsp.RtspClient.dispatchRtspError(RtspClient.java:322)\n\tat androidx.media3.exoplayer.rtsp.RtspClient.access$700(RtspClient.java:76)\n\tat androidx.media3.exoplayer.rtsp.RtspClient$MessageListener.handleRtspResponse(RtspClient.java:607)\n\tat androidx.media3.exoplayer.rtsp.RtspClient$MessageListener.handleRtspMessage(RtspClient.java:515)\n\tat androidx.media3.exoplayer.rtsp.RtspClient$MessageListener.lambda$onRtspMessageReceived$0$androidx-media3-exoplayer-rtsp-RtspClient$MessageListener(RtspClient.java:508)\n\tat androidx.media3.exoplayer.rtsp.RtspClient$MessageListener$$ExternalSyntheticLambda0.run(Unknown Source:4)\n\tat android.os.Handler.handleCallback(Handler.java:942)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\t... 3 more\nCaused by: androidx.media3.exoplayer.rtsp.RtspMediaSource$RtspPlaybackException: OPTIONS 404\n\tat androidx.media3.exoplayer.rtsp.RtspClient$MessageListener.handleRtspResponse(RtspClient.java:609)\n\t... 8 more\n',
                      errorCode: '22000',
                      errorException: 'androidx.media3.exoplayer.ExoPlaybackException: Source error',
                      errorString: 'ExoPlaybackException: ERROR_CODE_IO_UNSPECIFIED' } }
```

**Comment by freeboub** [comment]
Ok, thank you for the feedback, regarding to new issue, I am afraid you will need to do a network trace to analyze what is happening, but it seems to be a server issue or something like a missing header (for cors ? )

**Comment by 1280103995** [comment]
I tried to investigate this issue yesterday and found out that the custom RtspMediaSource didn't implement anything. I also tried using the official RtspMediaSource but also got OPTIONS 404 error.

Finally, I had to use [react-native-vlc-media-player](https://github.com/razorRun/react-native-vlc-media-player) again to play RTSP and it solved my problem. Throughout, my link was rtsp://192.168.43.1:1338?auth=************, so it doesn't seem to be related to missing headers.

**Comment by freeboub** [comment]
OK ... so can we close the issue ?
I think this is an exoplayer/media3 issue then ...

**Comment by umar4911** [comment]
Bump, any way to solve this
