### ISSUE TITLE
[BUG]: ERROR_CODE_DECODER_INIT_FAILED

### ISSUE THREAD

**Issue by amitkumarcoding** [TheWidlarzGroup/react-native-video#3887]
### Version

6.1.2

### What platforms are you having the problem on?

Android

### System Version

Android Sumulator

### On what device are you experiencing the issue?

Simulator

### Architecture

Old architecture

### What happened?

When I play a `video`, I get an error after a few seconds of playing

`
{"error": {"errorCode": "24001", "errorException": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(1/129, null, null, audio/ac3, null, 384000, null, [-1, -1, -1.0, null], [6, 48000]), format_supported=NO_UNSUPPORTED_TYPE", "errorStackTrace": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(1/129, null, null, audio/ac3, null, 384000, null, [-1, -1, -1.0, null], [6, 48000]), format_supported=NO_UNSUPPORTED_TYPE
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:601)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.exoplayer.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: [-49999], Format(1/129, null, null, audio/ac3, null, 384000, null, [-1, -1, -1.0, null], [6, 48000])
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1021)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:556)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:2196)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.processEndOfStream(MediaCodecRenderer.java:2059)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1889)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:816)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1047)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:522)
	... 4 more
", "errorString": "ExoPlaybackException: ERROR_CODE_DECODER_INIT_FAILED"}}
`

### Reproduction

- open the app
- I am using m3u8 stream URL
- switch the app to 4G network or bellow network (Working fine with 5G network)
- Play the video
- after few seconds of playing video stuck in between

This happend in Android Simulator and real device both (if theri network is 4G or low network)

**Comment by amitkumarcoding** [comment]
Duplicate

https://github.com/TheWidlarzGroup/react-native-video/issues/3888
