### ISSUE TITLE
[BUG]: ERROR_CODE_DECODER_INIT_FAILED

### ISSUE THREAD

**Issue by amitkumarcoding** [TheWidlarzGroup/react-native-video#3888]
### Version

6.1.2

### What platforms are you having the problem on?

Android

### System Version

Android Sumulator, Android 12 or below

### On what device are you experiencing the issue?

Simulator

### Architecture

Old architecture

### What happened?

When I play a `video`, I get an error after a few seconds of playing

`
{"error": {"errorCode": "24001", "errorException": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(1/129, null, null, audio/ac3, null, 384000, null, [-1, -1, -1.0, null], [6, 48000]), format_supported=NO_UNSUPPORTED_TYPE", "errorStackTrace": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(1/129, null, null, audio/ac3, null, 384000, null, [-1, -1, -1.0, null], [6, 48000]), format_supported=NO_UNSUPPORTED_TYPE
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:601)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.exoplayer.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: [-49999], Format(1/129, null, null, audio/ac3, null, 384000, null, [-1, -1, -1.0, null], [6, 48000])
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1021)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:556)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:2196)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.processEndOfStream(MediaCodecRenderer.java:2059)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1889)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:816)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1047)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:522)
	... 4 more
", "errorString": "ExoPlaybackException: ERROR_CODE_DECODER_INIT_FAILED"}}
`

### Reproduction

- open the app
- I am using m3u8 stream URL
- switch the app to 4G network or bellow network (Working fine with 5G network)
- Play the video
- after few seconds of playing video stuck in between

This happend in Android Simulator and real device both (if theri network is 4G or low network)

**Comment by amitkumarcoding** [comment]
This issue is also there on android 13 Sumulator

**Comment by freeboub** [comment]
Do you have a sample url ?

**Comment by KrzysztofMoch** [comment]
No activity nor response - I am closing this

**Comment by KaungHtetHein116** [comment]
i had to reduce the video size and quality in order to make it work

**Comment by rahulnainwal107** [comment]
This is a valid bug: When we play a stream with multiple audio codes and AC3 audio as a default, this error appears when we play a stream on an unsupported device.

This bug needs to be opened.

**Comment by rahulnainwal107** [comment]
[#4398](https://github.com/TheWidlarzGroup/react-native-video/pull/4398)

**Comment by rahulnainwal107** [comment]
Manifest - 

```
<?xml version="1.0" encoding="utf-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mpeg:dash:schema:mpd:2011" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd" type="dynamic" availabilityStartTime="1970-01-01T00:00:00Z" publishTime="2025-01-30T07:26:11.437341Z" minimumUpdatePeriod="PT2S" timeShiftBufferDepth="PT30S" maxSegmentDuration="PT3S" minBufferTime="PT2S" profiles="urn:mpeg:dash:profile:isoff-live:2011">
    <Period id="1" start="PT0S">
        <BaseURL>dash/</BaseURL>
        <AdaptationSet id="1" group="1" contentType="audio" segmentAlignment="true" audioSamplingRate="48000" mimeType="audio/mp4" codecs="ac-3" startWithSAP="1">
            <AudioChannelConfiguration schemeIdUri="tag:dolby.com,2014:dash:audio_channel_configuration:2011" value="F801"/>
            <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
            <SegmentTemplate timescale="48000" initialization="182-$RepresentationID$.dash" media="182-$RepresentationID$-$Time$.dash">
                <!-- 2025-01-30T07:25:41.058645Z / 1738221941 - 2025-01-30T07:26:11.074645Z -->
                <SegmentTimeline>
                    <S t="83434653170815" d="96768"/>
                    <S d="95232"/>
                    <S d="96768"/>
                    <S d="95232"/>
                    <S d="96768"/>
                    <S d="95232"/>
                    <S d="96768"/>
                    <S d="95232"/>
                    <S d="96768"/>
                    <S d="95232"/>
                    <S d="96768"/>
                    <S d="95232"/>
                    <S d="96768"/>
                    <S d="95232"/>
                    <S d="96768"/>
                </SegmentTimeline>
            </SegmentTemplate>
            <Representation id="audio_400081_und=400000" bandwidth="400000">
      </Representation>
        </AdaptationSet>
        <AdaptationSet id="2" group="1" contentType="audio" segmentAlignment="true" audioSamplingRate="48000" mimeType="audio/mp4" codecs="mp4a.40.5" startWithSAP="1">
            <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
            <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
            <SegmentTemplate timescale="48000" initialization="182-$RepresentationID$.dash" media="182-$RepresentationID$-$Time$.dash">
                <!-- 2025-01-30T07:25:39.097291Z / 1738221939 - 2025-01-30T07:26:11.097291Z -->
                <SegmentTimeline>
                    <S t="83434653076670" d="94208"/>
                    <S d="96256" r="6"/>
                    <S d="94208"/>
                    <S d="96256" r="6"/>
                </SegmentTimeline>
            </SegmentTemplate>
            <Representation id="audio_40080_und=40000" bandwidth="40000">
      </Representation>
        </AdaptationSet>
        <AdaptationSet id="3" group="2" contentType="video" par="16:9" minBandwidth="410000" maxBandwidth="1350000" maxWidth="1280" maxHeight="720" minFrameRate="25/2" maxFrameRate="25" segmentAlignment="true" mimeType="video/mp4" startWithSAP="1">
            <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
            <SegmentTemplate timescale="600" initialization="182-$RepresentationID$.dash" media="182-$RepresentationID$-$Time$.dash">
                <!-- 2025-01-30T07:25:41.058333Z / 1738221941 - 2025-01-30T07:26:11.058333Z -->
                <SegmentTimeline>
                    <S t="1042933164635" d="1200" r="14"/>
                </SegmentTimeline>
            </SegmentTemplate>
            <Representation id="video=410000" bandwidth="410000" width="480" height="270" sar="1:1" frameRate="25/2" codecs="avc1.428015" scanType="progressive">
      </Representation>
            <Representation id="video=660000" bandwidth="660000" width="480" height="270" sar="1:1" frameRate="25" codecs="avc1.428016" scanType="progressive">
      </Representation>
            <Representation id="video=860000" bandwidth="860000" width="640" height="480" sar="4:3" frameRate="25" codecs="avc1.4D401F" scanType="progressive">
      </Representation>
            <Representation id="video=1030000" bandwidth="1030000" width="960" height="540" sar="1:1" frameRate="25" codecs="avc1.4D4020" scanType="progressive">
      </Representation>
            <Representation id="video=1350000" bandwidth="1350000" width="1280" height="720" sar="1:1" frameRate="25" codecs="avc1.640028" scanType="progressive">
      </Representation>
        </AdaptationSet>
    </Period>
    <UTCTiming schemeIdUri="urn:mpeg:dash:utc:http-iso:2014" value="https://time.akamai.com/?iso"/>
</MPD>
```

**Comment by CesarRivasP** [comment]
> This is a valid bug: When we play a stream with multiple audio codes and AC3 audio as a default, this error appears when we play a stream on an unsupported device.
> 
> This bug needs to be opened.

I have the same issue in a Google Chromecast with Android TV. The react-native-video version is `react-native-video@6.11.0`

**Comment by threeinto3** [comment]
> Manifest -
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mpeg:dash:schema:mpd:2011" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd" type="dynamic" availabilityStartTime="1970-01-01T00:00:00Z" publishTime="2025-01-30T07:26:11.437341Z" minimumUpdatePeriod="PT2S" timeShiftBufferDepth="PT30S" maxSegmentDuration="PT3S" minBufferTime="PT2S" profiles="urn:mpeg:dash:profile:isoff-live:2011">
>     <Period id="1" start="PT0S">
>         <BaseURL>dash/</BaseURL>
>         <AdaptationSet id="1" group="1" contentType="audio" segmentAlignment="true" audioSamplingRate="48000" mimeType="audio/mp4" codecs="ac-3" startWithSAP="1">
>             <AudioChannelConfiguration schemeIdUri="tag:dolby.com,2014:dash:audio_channel_configuration:2011" value="F801"/>
>             <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
>             <SegmentTemplate timescale="48000" initialization="182-$RepresentationID$.dash" media="182-$RepresentationID$-$Time$.dash">
>                 
>                 <SegmentTimeline>
>                     <S t="83434653170815" d="96768"/>
>                     <S d="95232"/>
>                     <S d="96768"/>
>                     <S d="95232"/>
>                     <S d="96768"/>
>                     <S d="95232"/>
>                     <S d="96768"/>
>                     <S d="95232"/>
>                     <S d="96768"/>
>                     <S d="95232"/>
>                     <S d="96768"/>
>                     <S d="95232"/>
>                     <S d="96768"/>
>                     <S d="95232"/>
>                     <S d="96768"/>
>                 </SegmentTimeline>
>             </SegmentTemplate>
>             <Representation id="audio_400081_und=400000" bandwidth="400000">
>       </Representation>
>         </AdaptationSet>
>         <AdaptationSet id="2" group="1" contentType="audio" segmentAlignment="true" audioSamplingRate="48000" mimeType="audio/mp4" codecs="mp4a.40.5" startWithSAP="1">
>             <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
>             <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
>             <SegmentTemplate timescale="48000" initialization="182-$RepresentationID$.dash" media="182-$RepresentationID$-$Time$.dash">
>                 
>                 <SegmentTimeline>
>                     <S t="83434653076670" d="94208"/>
>                     <S d="96256" r="6"/>
>                     <S d="94208"/>
>                     <S d="96256" r="6"/>
>                 </SegmentTimeline>
>             </SegmentTemplate>
>             <Representation id="audio_40080_und=40000" bandwidth="40000">
>       </Representation>
>         </AdaptationSet>
>         <AdaptationSet id="3" group="2" contentType="video" par="16:9" minBandwidth="410000" maxBandwidth="1350000" maxWidth="1280" maxHeight="720" minFrameRate="25/2" maxFrameRate="25" segmentAlignment="true" mimeType="video/mp4" startWithSAP="1">
>             <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
>             <SegmentTemplate timescale="600" initialization="182-$RepresentationID$.dash" media="182-$RepresentationID$-$Time$.dash">
>                 
>                 <SegmentTimeline>
>                     <S t="1042933164635" d="1200" r="14"/>
>                 </SegmentTimeline>
>             </SegmentTemplate>
>             <Representation id="video=410000" bandwidth="410000" width="480" height="270" sar="1:1" frameRate="25/2" codecs="avc1.428015" scanType="progressive">
>       </Representation>
>             <Representation id="video=660000" bandwidth="660000" width="480" height="270" sar="1:1" frameRate="25" codecs="avc1.428016" scanType="progressive">
>       </Representation>
>             <Representation id="video=860000" bandwidth="860000" width="640" height="480" sar="4:3" frameRate="25" codecs="avc1.4D401F" scanType="progressive">
>       </Representation>
>             <Representation id="video=1030000" bandwidth="1030000" width="960" height="540" sar="1:1" frameRate="25" codecs="avc1.4D4020" scanType="progressive">
>       </Representation>
>             <Representation id="video=1350000" bandwidth="1350000" width="1280" height="720" sar="1:1" frameRate="25" codecs="avc1.640028" scanType="progressive">
>       </Representation>
>         </AdaptationSet>
>     </Period>
>     <UTCTiming schemeIdUri="urn:mpeg:dash:utc:http-iso:2014" value="https://time.akamai.com/?iso"/>
> </MPD>
> ```

can you explain about this xml
