### ISSUE TITLE
[BUG]: androidx.media3.exoplayer.ExoPlaybackException: Unexpected runtime error

### ISSUE THREAD

**Issue by Ahsanch11** [TheWidlarzGroup/react-native-video#4063]
### What happened?

`androidx.media3.exoplayer.ExoPlaybackException: Unexpected runtime error` is thrown during playback on Android.

The original report did not include a usable description (only "A bug happened!"), the screenshot failed to upload, and no reproduction repository or steps were provided. The issue was nonetheless confirmed and accepted by the maintainers team (labels: `bug`, `Accepted`, `Platform: Android`, `V6`).

### react-native-video version

6.4.3

### Platforms

Android

### OS version

Android 12

### Device

Real device, Simulator / Emulator

### Architecture

Old Architecture

**Comment by seyedmostafahasani** [comment]
@Ahsanch11 would you please upload the image again?

**Comment by Ahsanch11** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/a67eabfb-0ba8-4d72-9c72-d7ab894b7bfc)

**Comment by Ahsanch11** [comment]
I am building a video reels app and use react-native-video in Flatlist.
Working fine on ios but on android the issue is after some time the app crash without notifying any issue and sometimes it shows the above error on first video.

**Comment by paul-rinaldi** [comment]
I'd suggest also posting the `adb logcat` log
You can create a log file by running:

0. `adb logcat -c` (clears the log)
1. Once you're app is running, `adb logcat > bug4063.log`
2. When you notice this playback exception, CTRL+C to quit the logging
3. Upload the log here

I would be suspicious of the memory usage. Android generally gives more responsibility to us the software developers to write performant code I'd say than Apple. I have seen high memory usage alerts from logcat before using react-native-video and suspect some crashes I've had are when I've used RNV playing in the background and using many other apps as well (physical device).

**Comment by moskalakamil** [comment]
@Ahsanch11 Could you also attach your video component usage? It would be easier to reproduce this error, thanks!

**Comment by Ahsanch11** [comment]
`
import Video from 'react-native-video';
import { StyleSheet, Platform } from 'react-native';
import React, { useRef, useCallback, useState } from 'react';
import { useFocusEffect } from '@react-navigation/native';

const VideoPlayer = React.memo(({ item, isStop, activeVideo }) => {
  const videoRef = useRef(null);
  const [videoUrl, setVideoUrl] = useState(item.url || '');

  useFocusEffect(
    useCallback(() => {
      if (!videoRef.current) {
        return;
      }
      if (activeVideo === item._id) {
        videoRef.current.resume();
      } else {
        videoRef?.current?.pause();
      }
      return () => {
        if (videoRef.current) {
          videoRef.current.pause();
        }
      };
    }, [activeVideo, item])
  );

  const handleBuffer = useCallback((b) => {
    console.log("Buffering...", b)
  },[])

  return (
    <Video
      source={{ uri: videoUrl }}
      ref={videoRef}
      onBuffer={handleBuffer}
      onError={e => console.log("error in video", e)}
      style={styles.backgroundVideo}
      resizeMode="cover"
      repeat={true}
      paused={isStop || activeVideo !== item._id}
      fullscreen={Platform.OS == "ios"}
      fullscreenAutorotate={false}
      fullscreenOrientation="portrait"
      // debug={{
      //   enable: true,
      //   thread: true,
      // }}
      bufferConfig={{
        minBufferMs: 10000,
        maxBufferMs: 50000,
        bufferForPlaybackMs: 2500,
        bufferForPlaybackAfterRebufferMs: 5000,
        backBufferDurationMs: 20000,
        cacheSizeMB: 200,
      }}
    />
  );
});

const styles = StyleSheet.create({
  backgroundVideo: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
    backgroundColor: 'transparent',
    zIndex: 101,
  },
});

export default VideoPlayer;
`
this is my video component

**Comment by Ahsanch11** [comment]
` <FlatList
        data={data}
        pagingEnabled
        showsVerticalScrollIndicator={false}
        onViewableItemsChanged={handleItemChanged}
        viewabilityConfig={{
          itemVisiblePercentThreshold: 50,
        }}
        keyExtractor={item => item._id}
        onEndReached={loadMoreData}
        onEndReachedThreshold={0.7}
        renderItem={props => {
          activeVideoUser.current = props.item;
          return (
            <View
              style={{
                height:
                  Platform.OS == 'ios' ? screenHeight - 80 : screenHeight - 40,
                width,
              }}>
              <VideoPlayer
                isStop={isStop}
                item={props.item}
                activeVideo={activeVideo}
              />
            </View>
          );
        }}`

**Comment by Ahsanch11** [comment]
bufferConfig={{
minBufferMs: 10000,
maxBufferMs: 50000,
bufferForPlaybackMs: 2500,
bufferForPlaybackAfterRebufferMs: 5000,
backBufferDurationMs: 20000,
cacheSizeMB: 200,
}}  removed this buffeConfig and the i didn't see the crash.

**Comment by Ahsanch11** [comment]
@moskalakamil @paul-rinaldi the issue resolved of instantly crashing when i removed the buffer config on android but now the app crash after 1 minute almost wothout logging any information.

**Comment by freeboub** [comment]
@Ahsanch11 Not sure of the status of this ticket on your side... don't you overload the RAM memory ?
Not that I wrote a sample with flatlist here: https://github.com/freeboub/react-native-video-flatlist-sample

**Comment by freeboub** [comment]
I close the issue because there are too much mixed information.
Please reopen a new issue with a sample and / all the information in the ticket description.

**Comment by angelos3lex** [comment]
I have the same issue randomly appearing on android too. We record video using react-native-vision-camera latest version and use the latest version (6.5.0) of this lib too. (Also happened with 6.0.0). Then we crop the video using ffmpeg kit. The video is indeed rendered inside multiple scrollviews. As soon as i restart the app, the problem is not there, and i can see the video. Seems like something random. I will come back if i find something more to add to the conversation.

**Comment by freeboub** [comment]
@angelos3lex I suspect you have too much <Video views mounted in the same time. each time you mount a <Video it allocates new decoder. Can you check how much views are mounted ?
More than 6 is too much. 4 should be OK on modern phones.

**Comment by freeboub** [comment]
I would saw more than 6 is too much (4 should already be enough)

**Comment by angelos3lex** [comment]
```
{"errorStackTrace":"androidx.media3.exoplayer.ExoPlaybackException: Unexpected runtime error\n\t
at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:701)\n\t
at android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loopOnce(Looper.java:230)\n\t
at android.os.Looper.loop(Looper.java:319)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\n
Caused by: java.lang.IllegalStateException: flush() is valid only at Executing states; currently at Released state\n\n\t
at android.media.MediaCodec.native_flush(Native Method)\n\t
at android.media.MediaCodec.flush(MediaCodec.java:2504)\n\t
at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.flush(AsynchronousMediaCodecAdapter.java:248)\n\t
at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:912)\n\t
at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:905)\n\t
at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushOrReinitializeCodec(MediaCodecRenderer.java:868)\n\t
at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onPositionReset(MediaCodecRenderer.java:719)\n\t
at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onPositionReset(MediaCodecVideoRenderer.java:654)\n\t
at androidx.media3.exoplayer.BaseRenderer.resetPosition(BaseRenderer.java:202)\n\t
at androidx.media3.exoplayer.BaseRenderer.resetPosition(BaseRenderer.java:195)\n\t
at androidx.media3.exoplayer.ExoPlayerImplInternal.resetRendererPosition(ExoPlayerImplInternal.java:1445)\n\t
at androidx.media3.exoplayer.ExoPlayerImplInternal.seekToPeriodPosition(ExoPlayerImplInternal.java:1423)\n\t
at androidx.media3.exoplayer.ExoPlayerImplInternal.seekToPeriodPosition(ExoPlayerImplInternal.java:1362)\n\t
at androidx.media3.exoplayer.ExoPlayerImplInternal.seekToInternal(ExoPlayerImplInternal.java:1332)\n\t
at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:547)\n\t
... 4 more\n","errorCode":"21004","errorException":"androidx.media3.exoplayer.ExoPlaybackException: Unexpected runtime error","errorString":"ExoPlaybackException: ERROR_CODE_FAILED_RUNTIME_CHECK"}
```
That's my error log.
@freeboub nope that's not the case as we only display 1 video each time. After pressing some button we replace the displayed video with another, but it's always 1.

**Comment by angelos3lex** [comment]
I can see in the logs the key word 'seek' and we indeed seek really soon after mounting, so i will disable this to retest.

**Comment by freeboub** [comment]
@angelos3lex Yes you are right ! you can use source.startPosition to handle it automatically !

**Comment by freeboub** [comment]
maybe we should block seeking before really available ?! there is maybe a bug in RNV here !

**Comment by angelos3lex** [comment]
Nice, I'm checking with startPosition. indeed could be a nice addition to not break the player but just ignore the seek or queue it for when it's available

**Comment by freeboub** [comment]
ticket reopen to fix the early seek issue. thank you @angelos3lex, let me know the result

**Comment by angelos3lex** [comment]
indeed its not reproduced anymore after i used the source.startPosition and removed seek on mount.

**Comment by freeboub** [comment]
@angelos3lex Thank you for the feedback, I will to fix the exception anyway ! :)

**Comment by Makhdoom-Sharif** [comment]
<img width="1189" alt="Screenshot 2025-01-15 at 1 14 51 pm" src="https://github.com/user-attachments/assets/fa03c84c-b419-4ff1-857f-0a38bd3f211f" />
 I am getting the error mentioned above when running this package on Android. When I remove the `repeat` flag, this package seems to be working fine, but when I add it, the app crashes after a few seconds.

**Comment by ReactNativ** [comment]
### Error
```
{"error": {"errorCode": "24003", "errorException": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(0, null, null, video/avc, null, -1, null, [32, 32, -1.0, null], [-1, -1]), format_supported=YES", "errorStackTrace": "..."}}
```

### Cause
The error is due to the video being encoded in H.264 High 4:4:4 Profile, which is not widely supported on mobile devices. These devices typically work better with:
- **H.264 Baseline Profile**

---

## Solution: Convert Video to Mobile-Friendly Format

To resolve this issue, use `FFmpegKit React Native` to re-encode the video into a more compatible format before playback.

### Input Format
- `.avi` (H.264 High 4:4:4 Profile)

### Output Format
- `.mp4` (H.264 Baseline Profile, yuv420p)

---

## Prerequisites
1. Install the necessary dependencies in your React Native project:
   ```bash
   yarn add ffmpeg-kit-react-native react-native-fs
   ```
2. If you are using iOS, ensure native modules are linked by running:
   ```bash
   cd ios && pod install
   ```

---

## Implementation

### Video Conversion Example
The following code downloads a video, converts it to a mobile-friendly format using FFmpeg, and returns the path to the converted video:

```tsx
import { FFmpegKit } from 'ffmpeg-kit-react-native';
import RNFS from 'react-native-fs';

async function convertVideo() {
  try {
    const videoUrl = 'https://example-video.avi'; // Input video URL
    const videoPath = `${RNFS.CachesDirectoryPath}/temp_input.avi`; // Temporary input path
    const outputPath = `${RNFS.CachesDirectoryPath}/temp_output.mp4`; // Temporary output path

    // Step 1: Download the video to a temporary file
    await RNFS.downloadFile({
      fromUrl: videoUrl,
      toFile: videoPath,
    }).promise;

    // Step 2: FFmpeg command to convert the video
    const command = `-y -i ${videoPath} -c:v libx264 -profile:v baseline -level 3.0 -pix_fmt yuv420p -c:a aac -b:a 128k ${outputPath}`;
    const session = await FFmpegKit.execute(command);
    const returnCode = await session.getReturnCode();

    if (returnCode.isValueSuccess()) {
      console.log('Video conversion successful!');
      return outputPath; // Converted video path
    } else {
      console.error('Video conversion failed:', await session.getFailStackTrace());
      return null;
    }
  } catch (error) {
    console.error('Error during video conversion:', error);
    return null;
  }
}
```

### Playback the Converted Video
Once the video is converted, use its `outputPath` for playback in your app.

---

## Troubleshooting

### Error: "Unknown Encoder 'libx264'"
If you encounter the following error during conversion:
```
Unknown encoder 'libx264'
```

#### Solution:
1. Open the `android/build.gradle` file in the `ffmpeg-kit-react-native` package:
   ```
   node_modules/ffmpeg-kit-react-native/android/build.gradle
   ```
2. Update the `dependencies` section to include:
   ```gradle
   implementation 'com.arthenica:ffmpeg-kit-full-gpl:6.0-2'
   ```

---


## FAQ

### Why does this issue occur?
The H.264 High 4:4:4 Profile and unsupported pixel formats (`yuv444p`) are not compatible with many mobile hardware decoders, causing playback failures.

### Can this solution handle other video formats?
Yes, FFmpeg can handle a wide variety of input formats. Update the input file extension (`.avi`, `.mkv`, `.mov`, etc.) and ensure the desired output format is specified.

### Are there other profiles or formats I can use?
For maximum compatibility, stick to:
- **H.264 Baseline Profile**
- **H.264 Main Profile**
- **Pixel format: yuv420p**

**Comment by saeidtkh** [comment]
any updates?

**Comment by TWG-AI** [comment]
Thanks for the follow-up information — this helped narrow down the root cause significantly.

Two separate issues were identified in this thread:

**1. Crash from seeking too early (library bug):** Calling `.seek()` via a ref immediately on mount, before ExoPlayer is in the `READY` state, causes the crash. A safer alternative is to use `source.startPosition` (in milliseconds) instead of calling `seek()` on mount — this lets the player seek natively during initialization:
```jsx
<Video
  source={{ uri: '...', startPosition: 30000 /* ms */ }}
  ...
/>
```
We've tracked this as a bug to properly queue seek requests until the player is ready.

**2. Crash from too many concurrent Video instances:** Android hardware video decoders are limited (typically 4–6 simultaneous). Mounting more Video components than this limit crashes ExoPlayer. In a FlatList/reel layout, keep at most 3–4 Video instances mounted at once using `removeClippedSubviews` and conservative `windowSize` values.

> [!NOTE]
> This response was generated by TWG-AI, the TheWidlarzGroup automated triage assistant.
