### ISSUE TITLE
[BUG]: Error 24003 on Android 12

### ISSUE THREAD

**Issue by m-cartmell** [TheWidlarzGroup/react-native-video#4164]
### Version

6.5.0

### What platforms are you having the problem on?

Android

### System Version

Android 12

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

```plaintext
LOG  video error: {
  "error": {
    "errorCode": "24003", 
    "errorException": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D4029, -1, null, [1920, 1080, 24.999998, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES",
    "errorStackTrace": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.4D4029, -1, null, [1920, 1080, 24.999998, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES
    at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:623)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.os.HandlerThread.run(HandlerThread.java:67)
    Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: c2.rk.avc.decoder
    at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1915)
    at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:848)
    at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:940)
    at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1112)
    at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:544)
    ... 4 more
    Caused by: java.lang.IllegalStateException
    at android.media.MediaCodec.native_queueInputBuffer(Native Method)
    at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2769)
    at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecBufferEnqueuer.doQueueInputBuffer(AsynchronousMediaCodecBufferEnqueuer.java:220)
    at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecBufferEnqueuer.doHandleMessage(AsynchronousMediaCodecBufferEnqueuer.java:189)
    at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecBufferEnqueuer.access$000(AsynchronousMediaCodecBufferEnqueuer.java:45)
    at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecBufferEnqueuer$1.handleMessage(AsynchronousMediaCodecBufferEnqueuer.java:91)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    ... 3 more
    ",
    "errorString": "ExoPlaybackException: ERROR_CODE_DECODING_FAILED"
  }
}
```

### Expected behaviour

Consistently play MP4s after rendering a new screen without issue.

### Reproduction Link

https://github.com/m-cartmell/react-native-video-test

### Reproduction

With the minimal repo, reload the application or tap next until an error is reported. The erroring is inconsistent.

**Comment by vmsilva** [comment]
same problem here!

{"error": {"errorCode": "24003", "errorException": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64001E, 608000, null, [640, 360, -1.0, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES", "errorStackTrace": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64001E, 608000, null, [640, 360, -1.0, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:623)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: c2.goldfish.h264.decoder
	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1915)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:848)
	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:940)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1112)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:544)
	... 4 more
Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff3
	at android.media.MediaCodec.releaseOutputBuffer(Native Method)
	at android.media.MediaCodec.releaseOutputBufferInternal(MediaCodec.java:3651)
	at android.media.MediaCodec.releaseOutputBuffer(MediaCodec.java:3572)
	at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.releaseOutputBuffer(AsynchronousMediaCodecAdapter.java:202)
	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.skipOutputBuffer(MediaCodecVideoRenderer.java:1528)
	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.processOutputBuffer(MediaCodecVideoRenderer.java:1330)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:2010)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:827)
	... 7 more
", "errorString": "ExoPlaybackException: ERROR_CODE_DECODING_FAILED"}}

**Comment by freeboub** [comment]
Looks like a DECODER issue, It means that playing the 2 videos in the same time causes issues on your device.
I try to reproduce with the emulator, I have no issue.
You should try to stop (set source to undefined) or pause the video when the screen is not visible with [useIsFocused](https://reactnavigation.org/docs/use-is-focused/)

**Comment by m-cartmell** [comment]
> Looks like a DECODER issue, It means that playing the 2 videos in the same time causes issues on your device. I try to reproduce with the emulator, I have no issue. You should try to stop (set source to undefined) or pause the video when the screen is not visible with [useIsFocused](https://reactnavigation.org/docs/use-is-focused/)

If you look at the minimal repo I supplied, I am using the useIsFocused hook to mount/unmount videos. I am experiencing the issue on a real device, not an emulator. The error can also occur when the project is initially rendered or reloaded.

**Comment by freeboub** [comment]
unfortunatelly, I don't reproduce on my device ... Did you try to add a delay before starting the video ?
I am afraid this is a device specific issue while there are 2 videos in the same time (unmount <Video is not an instant action) A delay can improve that.

You can also try to change the [viewType](https://thewidlarzgroup.github.io/react-native-video/component/props#viewtype)

**Comment by freeboub** [comment]
maybe it's also be related to this ticket ? https://github.com/TheWidlarzGroup/react-native-video/issues/3491

**Comment by m-cartmell** [comment]
> unfortunatelly, I don't reproduce on my device ... Did you try to add a delay before starting the video ? I am afraid this is a device specific issue while there are 2 videos in the same time (unmount <Video is not an instant action) A delay can improve that.
> 
> You can also try to change the [viewType](https://thewidlarzgroup.github.io/react-native-video/component/props#viewtype)

I will explore trying to dispose of the instance sooner. As it's triggering an error for me sometimes on initial render or

**Comment by m-cartmell** [comment]
> unfortunatelly, I don't reproduce on my device ... Did you try to add a delay before starting the video ? I am afraid this is a device specific issue while there are 2 videos in the same time (unmount <Video is not an instant action) A delay can improve that.
> 
> You can also try to change the [viewType](https://thewidlarzgroup.github.io/react-native-video/component/props#viewtype)

Thank you for your advice. Setting the video source to null when navigating away from a screen and using useIsFocused and a timeout to select the source when on a screen seems to have resolved the issue. I am closing the report.

**Comment by ReactNativ** [comment]
### Error
```
{"error": {"errorCode": "24003", "errorException": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(0, null, null, video/avc, null, -1, null, [32, 32, -1.0, null], [-1, -1]), format_supported=YES", "errorStackTrace": "..."}}
```

### Cause
The error is due to the video being encoded in H.264 High 4:4:4 Profile, which is not widely supported on mobile devices. These devices typically work better with:
- **H.264 Baseline Profile**

---

## Solution: Convert Video to Mobile-Friendly Format

To resolve this issue, use `FFmpegKit React Native` to re-encode the video into a more compatible format before playback.

### Input Format
- `.avi` (H.264 High 4:4:4 Profile)

### Output Format
- `.mp4` (H.264 Baseline Profile, yuv420p)

---

## Prerequisites
1. Install the necessary dependencies in your React Native project:
   ```bash
   yarn add ffmpeg-kit-react-native react-native-fs
   ```
2. If you are using iOS, ensure native modules are linked by running:
   ```bash
   cd ios && pod install
   ```

---

## Implementation

### Video Conversion Example
The following code downloads a video, converts it to a mobile-friendly format using FFmpeg, and returns the path to the converted video:

```tsx
import { FFmpegKit } from 'ffmpeg-kit-react-native';
import RNFS from 'react-native-fs';

async function convertVideo() {
  try {
    const videoUrl = 'https://example-video.avi'; // Input video URL
    const videoPath = `${RNFS.CachesDirectoryPath}/temp_input.avi`; // Temporary input path
    const outputPath = `${RNFS.CachesDirectoryPath}/temp_output.mp4`; // Temporary output path

    // Step 1: Download the video to a temporary file
    await RNFS.downloadFile({
      fromUrl: videoUrl,
      toFile: videoPath,
    }).promise;

    // Step 2: FFmpeg command to convert the video
    const command = `-y -i ${videoPath} -c:v libx264 -profile:v baseline -level 3.0 -pix_fmt yuv420p -c:a aac -b:a 128k ${outputPath}`;
    const session = await FFmpegKit.execute(command);
    const returnCode = await session.getReturnCode();

    if (returnCode.isValueSuccess()) {
      console.log('Video conversion successful!');
      return outputPath; // Converted video path
    } else {
      console.error('Video conversion failed:', await session.getFailStackTrace());
      return null;
    }
  } catch (error) {
    console.error('Error during video conversion:', error);
    return null;
  }
}
```

### Playback the Converted Video
Once the video is converted, use its `outputPath` for playback in your app.

---

## Troubleshooting

### Error: "Unknown Encoder 'libx264'"
If you encounter the following error during conversion:
```
Unknown encoder 'libx264'
```

#### Solution:
1. Open the `android/build.gradle` file in the `ffmpeg-kit-react-native` package:
   ```
   node_modules/ffmpeg-kit-react-native/android/build.gradle
   ```
2. Update the `dependencies` section to include:
   ```gradle
   implementation 'com.arthenica:ffmpeg-kit-full-gpl:6.0-2'
   ```

---


## FAQ

### Why does this issue occur?
The H.264 High 4:4:4 Profile and unsupported pixel formats (`yuv444p`) are not compatible with many mobile hardware decoders, causing playback failures.

### Can this solution handle other video formats?
Yes, FFmpeg can handle a wide variety of input formats. Update the input file extension (`.avi`, `.mkv`, `.mov`, etc.) and ensure the desired output format is specified.

### Are there other profiles or formats I can use?
For maximum compatibility, stick to:
- **H.264 Baseline Profile**
- **H.264 Main Profile**
- **Pixel format: yuv420p**
