### ISSUE TITLE
[BUG]: sutitles loading error

### ISSUE THREAD

**Issue by YspCoder** [TheWidlarzGroup/react-native-video#4234]
### Version

6.7.0-rc.0

### What platforms are you having the problem on?

Android

### System Version

14

### On what device are you experiencing the issue?

Real device

### Architecture

New architecture with interop layer

### What happened?

{"error": {"errorCode": "21004", "errorException": "androidx.media3.exoplayer.ExoPlaybackException: Unexpected runtime error", "errorStackTrace": "androidx.media3.exoplayer.ExoPlaybackException: Unexpected runtime error
        at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:720)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:219)
        at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.IllegalStateException: Legacy decoding is disabled, can't handle application/x-subrip samples (expected application/x-media3-cues).
        at androidx.media3.common.util.Assertions.checkState(Assertions.java:100)
        at androidx.media3.exoplayer.text.TextRenderer.assertLegacyDecodingEnabledIfRequired(TextRenderer.java:589)
        at androidx.media3.exoplayer.text.TextRenderer.onStreamChanged(TextRenderer.java:212)
        at androidx.media3.exoplayer.BaseRenderer.replaceStream(BaseRenderer.java:151)
        at androidx.media3.exoplayer.BaseRenderer.enable(BaseRenderer.java:125)
        at androidx.media3.exoplayer.ExoPlayerImplInternal.enableRenderer(ExoPlayerImplInternal.java:2773)
        at androidx.media3.exoplayer.ExoPlayerImplInternal.enableRenderers(ExoPlayerImplInternal.java:2747)
        at androidx.media3.exoplayer.ExoPlayerImplInternal.enableRenderers(ExoPlayerImplInternal.java:2728)
        at androidx.media3.exoplayer.ExoPlayerImplInternal.handlePeriodPrepared(ExoPlayerImplInternal.java:2525)
        at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        ... 3 more
", "errorString": "ExoPlaybackException: ERROR_CODE_FAILED_RUNTIME_CHECK"}}

### Reproduction Link

repository link

### Reproduction

selectedTextTrack={item.selectedSub}
source={{uri: item.url, textTracks: item.subTexts, }}

**Comment by freeboub** [comment]
can you share your sample stream and subtitle tracks ?

**Comment by YspCoder** [comment]
Sorry, the video I am using is in a production environment and cannot be shared

**Comment by freeboub** [comment]
cannot be fixed
