### ISSUE TITLE
[BUG]: Android Cache fails on Loaded Resource

### ISSUE THREAD

**Issue by lovegaoshi** [TheWidlarzGroup/react-native-video#4243]
### Version

6.7.0

### What platforms are you having the problem on?

Android

### System Version

any

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

loaded resource `require("./asset/path")` will fail to load in production when cache enables. this is because with cache enabled, RNV will [attempt to load resources as http](https://github.com/TheWidlarzGroup/react-native-video/blob/7c7d83b6e551a7920175047321b02fcace5cbe9e/android/src/main/java/com/brentvatne/exoplayer/ReactExoplayerView.java#L826) and a local res URI will be a malformed URI.

one solution could be an [isUriLocalFile](https://github.com/lovegaoshi/react-native-track-player/blob/70f61ca0e28fd285ba6b4fd1780b62587044c3da/android/src/main/java/com/lovegaoshi/kotlinaudio/utils/Utils.kt#L18) function, and use DefaultDataSource accordingly instead of http.

logs:

```
12526-12691 ExoPlayerImplInternal   com.noxplay.noxplayer                E  Playback error
                                                                                                      androidx.media3.exoplayer.ExoPlaybackException: Source error
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:736)
                                                                                                          at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:708)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                          at android.os.Looper.loop(Looper.java:294)
                                                                                                          at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                      Caused by: androidx.media3.datasource.HttpDataSource$HttpDataSourceException: Malformed URL
                                                                                                          at androidx.media3.datasource.okhttp.OkHttpDataSource.makeRequest(OkHttpDataSource.java:369)
                                                                                                          at androidx.media3.datasource.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:262)
                                                                                                          at androidx.media3.datasource.TeeDataSource.open(TeeDataSource.java:54)
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:802)
                                                                                                          at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:615)
                                                                                                          at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
                                                                                                          at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1045)
```

### Reproduction Link

the example app

### Reproduction

run the example app in production with cache on, and load the local file

**Comment by freeboub** [comment]
@lovegaoshi on js side we already have a property indicating if it is a local file (isAsset if I remember well). It would be easier to use this one !
