### ISSUE TITLE
[BUG]: Crash OutOfMemoryError Android

### ISSUE THREAD

**Issue by florian-deroo** [TheWidlarzGroup/react-native-video#4276]
### Version

6.7.0

### What platforms are you having the problem on?

Android

### System Version

I'm on expo dev client, with Android 13

### On what device are you experiencing the issue?

Simulator, Real device

### Architecture

New architecture with interop layer

### What happened?

The app is crashing:

FATAL EXCEPTION: ExoPlayer:Playback

java.lang.OutOfMemoryError: Failed to allocate a 56 byte allocation with 188352 free bytes and 183KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.

FATAL EXCEPTION: ExoPlayer:Playback
Process: com.test, PID: 8039
java.lang.OutOfMemoryError: Failed to allocate a 56 byte allocation with 188352 free bytes and 183KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at androidx.media3.exoplayer.source.ProgressiveMediaPeriod.onLoadError(ProgressiveMediaPeriod.java:645)
	at androidx.media3.exoplayer.source.ProgressiveMediaPeriod.onLoadError(ProgressiveMediaPeriod.java:77)
	at androidx.media3.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:498)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:234)
	at android.os.Looper.loop(Looper.java:346)
	at android.os.HandlerThread.run(HandlerThread.java:67)

### Reproduction

```
import React from "react";
import {ScrollView, View} from "react-native";
import Video from "react-native-video";

export default function App() {

    return (
        <ScrollView style={{
            flex: 1,
            width: "100%",
        }}>
            <Video
                source={{uri: "https://res.cloudinary.com/shotgun/video/upload/v1699355465/staging/artworks/afterlife-video_sjy9ic.mov"}}
                style={{width: '100%', height: 400}}
                resizeMode="cover"
                paused={false}
                repeat={true}
                maxBitRate={2000000}
                useTextureView={false}
                disableFocus={true}
                muted={false}
            /><Video
                source={{uri: "https://res.cloudinary.com/shotgun/video/upload/v1699355465/staging/artworks/afterlife-video_sjy9ic.mov"}}
                style={{width: '100%', height: 400}}
                resizeMode="cover"
                paused={true}
                repeat={true}
                maxBitRate={2000000}
                useTextureView={false}
                disableFocus={true}
                muted={false}
            /><Video
                source={{uri: "https://res.cloudinary.com/shotgun/video/upload/v1699355465/staging/artworks/afterlife-video_sjy9ic.mov"}}
                style={{width: '100%', height: 400}}
                resizeMode="cover"
                paused={true}
                useTextureView={false}
                disableFocus={true}
                repeat={true}
                maxBitRate={2000000}
                muted={false}
            />
        </ScrollView>

    );
}


```

**Comment by florian-deroo** [comment]
Found solution by adjusting videoBufferConfig

**Comment by freeboub** [comment]
so let's close, thank you

**Comment by florian-deroo** [comment]
> so let's close, thank you

Got the issue again; it's crashing when I have a lot of videos. Lowering default values of videoBufferConfig was not a sustainable fix...

My current config videoBufferConfig (i tried multiple):
```
minBufferMs: 2000,
maxBufferMs: 3000,
bufferForPlaybackMs: 0,
bufferForPlaybackAfterRebufferMs: 1000,
backBufferDurationMs: 0,
maxHeapAllocationPercent: 0.15,
minBackBufferMemoryReservePercent: 0.1,
minBufferMemoryReservePercent: 0.1,
cacheSizeMB: 0, // I tried with different values
```

**Comment by florian-deroo** [comment]
Can do screenshare, GC is doing infinite loop

**Comment by florian-deroo** [comment]
I think my issue is the same as this one: https://github.com/TheWidlarzGroup/react-native-video/issues/2984
6.X versions doesnt fix the issue

**Comment by florian-deroo** [comment]
```11-10 11:25:04.867 23575 23658 I come.test.app: Waiting for a blocking GC Alloc
11-10 11:25:04.867 23575 23724 I come.test.app: Waiting for a blocking GC Alloc
11-10 11:25:04.867 23575 26381 I come.test.app: Waiting for a blocking GC Alloc
11-10 11:25:04.867 23575 26630 I come.test.app: Forcing collection of SoftReferences for 4112B allocation
11-10 11:25:04.867 23575 26630 I come.test.app: Waiting for a blocking GC Alloc
11-10 11:25:04.867 23575 23726 I come.test.app: Waiting for a blocking GC Alloc
11-10 11:25:04.867 23575 25746 I come.test.app: Waiting for a blocking GC Alloc
11-10 11:25:04.868 23575 23721 I come.test.app: Waiting for a blocking GC Alloc
11-10 11:25:04.869 23575 23588 F come.test.app: jni_internal.cc:828] JNI FatalError called: java.lang.Error thrown during binder transaction: java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 130000 free bytes and 126KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
11-10 11:25:05.106 23575 23708 I come.test.app: Waiting for a blocking GC Alloc
11-10 11:25:05.110 23575 26089 I come.test.app: Waiting for a blocking GC Alloc
11-10 11:25:05.110 23575 25874 I come.test.app: Waiting for a blocking GC Alloc
11-10 11:25:05.110 23575 26283 I come.test.app: Waiting for a blocking GC Alloc
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708] Runtime aborting...
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708] All threads:
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708] DALVIK THREADS (399):
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708] "OkHttp http://192.168.1.101:8081/..." prio=5 tid=30 Blocked
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   | group="" sCount=1 ucsCount=0 flags=1 obj=0x1411ef68 self=0xb4000070f7d0a220
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   | sysTid=23635 nice=0 cgrp=top-app sched=0/0 handle=0x6ec96d5cb0
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   | state=S schedstat=( 8817394 10744999 56 ) utm=0 stm=0 core=4 HZ=100
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   | stack=0x6ec95d2000-0x6ec95d4000 stackSize=1039KB
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   | held mutexes=
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #00 pc 0004ea70  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+32) (BuildId: ddbd4d0e63dbd49debac2ca8b8bdd42d)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #01 pc 002bb4e4  /apex/com.android.art/lib64/libart.so (void art::Monitor::Lock<1>+9172) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #02 pc 0024932c  /apex/com.android.art/lib64/libart.so (artLockObjectFromCode+540) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #03 pc 00362c54  /apex/com.android.art/lib64/libart.so (art_quick_lock_object_no_inline+52) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #04 pc 02a455cc  /memfd:jit-cache (deleted) (offset 2000000) (okhttp3.internal.concurrent.TaskQueue.schedule+172)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #05 pc 00362774  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #06 pc 0035bd1c  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>+1928) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #07 pc 0076df64  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>+12208) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #08 pc 0037b5d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #09 pc 01d70c70  /data/app/~~SPglcg5WnYzhLpA6-KpV9w==/come.test.app-RshANX4NgwYmwV7X9wdfRA==/oat/arm64/base.vdex (okhttp3.internal.concurrent.TaskQueue.schedule$default)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #10 pc 0034e21c  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute +428) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #11 pc 0034f868  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge+100) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #12 pc 003489ac  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<true>+792) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #13 pc 0076e058  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>+12452) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #14 pc 0037b5d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #15 pc 01d74e40  /data/app/~~SPglcg5WnYzhLpA6-KpV9w==/come.test.app-RshANX4NgwYmwV7X9wdfRA==/oat/arm64/base.vdex (okhttp3.internal.connection.RealConnectionPool.put)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #16 pc 0034d5a8  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+1932) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #17 pc 00379098  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #18 pc 02a11084  /memfd:jit-cache (deleted) (offset 2000000) (okhttp3.internal.connection.ExchangeFinder.findConnection+1732)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #19 pc 00362774  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #20 pc 0034def0  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke+132) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #21 pc 00348854  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<true>+448) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #22 pc 0076e058  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>+12452) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #23 pc 0037b5d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #24 pc 01d7281c  /data/app/~~SPglcg5WnYzhLpA6-KpV9w==/come.test.app-RshANX4NgwYmwV7X9wdfRA==/oat/arm64/base.vdex (okhttp3.internal.connection.ExchangeFinder.findHealthyConnection)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #25 pc 0034e21c  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute +428) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #26 pc 0034f868  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge+100) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #27 pc 003489ac  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<true>+792) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #28 pc 0076e058  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>+12452) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #29 pc 0037b5d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #30 pc 01d728a0  /data/app/~~SPglcg5WnYzhLpA6-KpV9w==/come.test.app-RshANX4NgwYmwV7X9wdfRA==/oat/arm64/base.vdex (okhttp3.internal.connection.ExchangeFinder.find)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #31 pc 0034d5a8  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+1932) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #32 pc 00379098  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #33 pc 02aa6bcc  /memfd:jit-cache (deleted) (offset 2000000) (okhttp3.internal.connection.RealCall.initExchange$okhttp+348)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #34 pc 00362774  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #35 pc 0035bd1c  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>+1928) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #36 pc 0076df64  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>+12208) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #37 pc 0037b5d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #38 pc 01d71c00  /data/app/~~SPglcg5WnYzhLpA6-KpV9w==/come.test.app-RshANX4NgwYmwV7X9wdfRA==/oat/arm64/base.vdex (okhttp3.internal.connection.ConnectInterceptor.intercept)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #39 pc 0034d5a8  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+1932) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #40 pc 00379098  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #41 pc 0295fe4c  /memfd:jit-cache (deleted) (offset 2000000) (okhttp3.internal.http.RealInterceptorChain.proceed+1068)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #42 pc 02a6b3d8  /memfd:jit-cache (deleted) (offset 2000000) (okhttp3.internal.cache.CacheInterceptor.intercept+1544)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #43 pc 0295fe4c  /memfd:jit-cache (deleted) (offset 2000000) (okhttp3.internal.http.RealInterceptorChain.proceed+1068)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #44 pc 02a04514  /memfd:jit-cache (deleted) (offset 2000000) (okhttp3.internal.http.BridgeInterceptor.intercept+1156)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #45 pc 0295fe4c  /memfd:jit-cache (deleted) (offset 2000000) (okhttp3.internal.http.RealInterceptorChain.proceed+1068)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #46 pc 00362774  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #47 pc 0035bd1c  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>+1928) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #48 pc 0076df64  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>+12208) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #49 pc 0037b5d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #50 pc 01d78fb0  /data/app/~~SPglcg5WnYzhLpA6-KpV9w==/come.test.app-RshANX4NgwYmwV7X9wdfRA==/oat/arm64/base.vdex (okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #51 pc 0034d5a8  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+1932) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #52 pc 00379098  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #53 pc 0295fe4c  /memfd:jit-cache (deleted) (offset 2000000) (okhttp3.internal.http.RealInterceptorChain.proceed+1068)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #54 pc 00362774  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #55 pc 0035bd1c  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false>+1928) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #56 pc 0076df64  /apex/com.android.art/lib64/libart.so (void art::interpreter::ExecuteSwitchImplCpp<false>+12208) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #57 pc 0037b5d8  /apex/com.android.art/lib64/libart.so (ExecuteSwitchImplAsm+8) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #58 pc 00b5fcd0  /data/app/~~SPglcg5WnYzhLpA6-KpV9w==/come.test.app-RshANX4NgwYmwV7X9wdfRA==/oat/arm64/base.vdex (expo.modules.kotlin.devtools.ExpoNetworkInspectOkHttpAppInterceptor.intercept)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #59 pc 0034d5a8  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+1932) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #60 pc 00379098  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #61 pc 0295fe4c  /memfd:jit-cache (deleted) (offset 2000000) (okhttp3.internal.http.RealInterceptorChain.proceed+1068)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #62 pc 029b7b1c  /memfd:jit-cache (deleted) (offset 2000000) (okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp+876)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #63 pc 02a82734  /memfd:jit-cache (deleted) (offset 2000000) (okhttp3.internal.connection.RealCall$AsyncCall.run+420)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #64 pc 0214e68c  /memfd:jit-cache (deleted) (offset 2000000) (java.util.concurrent.ThreadPoolExecutor.runWorker+444)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #65 pc 0214e420  /memfd:jit-cache (deleted) (offset 2000000) (java.util.concurrent.ThreadPoolExecutor$Worker.run+128)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #66 pc 0200b128  /memfd:jit-cache (deleted) (offset 2000000) (java.lang.Thread.run+136)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #67 pc 00362774  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #68 pc 0034def0  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke+132) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #69 pc 00943e28  /apex/com.android.art/lib64/libart.so (art::detail::ShortyTraits<86>::Type art::ArtMethod::InvokeInstance<86>+60) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #70 pc 0063ebd4  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback+1344) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #71 pc 0063e684  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallbackWithUffdGc+8) (BuildId: 1ee2c234829500686eefa384068e67c8)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #72 pc 000ba5d4  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start+208) (BuildId: ddbd4d0e63dbd49debac2ca8b8bdd42d)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   native: #73 pc 00053f3c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: ddbd4d0e63dbd49debac2ca8b8bdd42d)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   at okhttp3.internal.concurrent.TaskQueue.schedule(TaskQueue.kt:62)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   - waiting to lock <0x0a200136> (a okhttp3.internal.concurrent.TaskRunner) held by thread 55
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   at okhttp3.internal.concurrent.TaskQueue.schedule$default(TaskQueue.kt:61)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   at okhttp3.internal.connection.RealConnectionPool.put(RealConnectionPool.kt:98)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:251)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   - locked <@addr=0x1956d948> (a okhttp3.internal.connection.RealConnection)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   at expo.modules.kotlin.devtools.ExpoNetworkInspectOkHttpAppInterceptor.intercept(ExpoNetworkInspectOkHttpInterceptors.kt:60)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
11-10 11:25:05.142 23575 23588 F come.test.app: runtime.cc:708]   at java.lang.Thread.run(Thread.java:1012)```

**Comment by baicuhaha** [comment]
<img width="881" alt="Image" src="https://github.com/user-attachments/assets/852f3b60-07c2-440b-be8e-b561c7180676" />
I also frequently encounter this error on Android. When navigating from the list page to the details page to play a video, then returning to the previous page and entering the details page again to play the video, after repeating this process a few times, the memory usage explodes.
Is there a good way to solve this problem?
