### ISSUE TITLE
[BUG]: Bundled assets won't load in release builds

### ISSUE THREAD

**Issue by m9tdev** [TheWidlarzGroup/react-native-video#4278]
### Version

6.7.0

### What platforms are you having the problem on?

Android

### System Version

API 34

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

When passing a `number` in the `source` property the video won't load on Android release builds. On debug builds it does work, and on iOS it always works.

I've retrieved the number value like this (I've also tried `require('./asset.mp4')`):
```
import VideoAsset from './asset.mp4';
```

Unfortunately, it won't show a video in my app and using Android Studio I'm seeing the following error:
```
Playback error
    androidx.media3.exoplayer.ExoPlaybackException: Source error
        at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:736)
        at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:708)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:205)
        at android.os.Looper.loop(Looper.java:294)
        at android.os.HandlerThread.run(HandlerThread.java:67)
    Caused by: androidx.media3.datasource.HttpDataSource$HttpDataSourceException: Malformed URL
        at androidx.media3.datasource.okhttp.OkHttpDataSource.makeRequest(OkHttpDataSource.java:369)
        at androidx.media3.datasource.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:262)
        at androidx.media3.datasource.TeeDataSource.open(TeeDataSource.java:54)
        at androidx.media3.datasource.cache.CacheDataSource.openNextSource(CacheDataSource.java:802)
        at androidx.media3.datasource.cache.CacheDataSource.open(CacheDataSource.java:615)
        at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
        at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1045)
        at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
        at java.lang.Thread.run(Thread.java:1012)
```

Adding logs in the `getUriFromAssetId` function in `Source.kt` does indicate that it found an identifier:
```
identifier: 2131820554
```
The result of `getUriFromAssetId` is:
```
android.resource:/2131820554
```

Unfortunately, I'm not proficient in Kotlin or Android native stuff, so I don't know how to continue from here. 

I'm 100% sure that the assets are actually bundled with the app, because when passing the `VideoAsset` to the source of an `Image` element from `expo-image` it actually shows the first frame as image.

### Reproduction

Step to reproduce this bug are: 

1. Add an mp4 asset.
2. Import or require the asset by relative path.
3. Use the result of the import or require as `source` parameter.
4. Create an Android **Release** build (Debug works fine)
5. No video is displayed on Android

**Comment by m9tdev** [comment]
Updated to 6.7.0, but the issue persists

**Comment by m9tdev** [comment]
Changed the return of `getUriFromAssetId` to
```
return Uri.Builder().scheme(ContentResolver.SCHEME_ANDROID_RESOURCE).authority(packageName).path(identifier.toString()).build()
```
as in the [Android documentation](https://developer.android.com/reference/androidx/media3/datasource/RawResourceDataSource) the package name is also added optionally, resulting in `android.resource://com.myapp.android/2131820552`, which does look like a more valid URI, but unfortunately it doesn't result in a playing video.

Also tried 
```
return Uri.Builder().scheme(ContentResolver.SCHEME_ANDROID_RESOURCE).authority(packageName).path(uriString).build()
```
resulting in `android.resource://com.myapp.android/src_assetcache_asset_10`, but this also doesn't work.

**Comment by lovegaoshi** [comment]
ur encountering [this](https://github.com/TheWidlarzGroup/react-native-video/issues/4243). its loading ur source as an httpDataSourceFactory and that happens when cache is enabled.

**Comment by m9tdev** [comment]
Ahaa! Thanks, disabling the cache for local assets fixed it indeed!
