### ISSUE TITLE
[BUG]: Android stuck on full screen when click on back the player started

### ISSUE THREAD

**Issue by hizbullaharif** [TheWidlarzGroup/react-native-video#4325]
### Version

6.8.2

### What platforms are you having the problem on?

Android

### System Version

Mac

### On what device are you experiencing the issue?

Real device, Simulator

### Architecture

Old architecture

### What happened?

A bug happened! occur on full screen

{"error": {"errorCode": "1001", "errorException": "java.lang.IndexOutOfBoundsException: index=1 count=0", "errorStackTrace": "java.lang.IndexOutOfBoundsException: index=1 count=0
	at android.view.ViewGroup.addInArray(ViewGroup.java:5385)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5278)
	at android.view.ViewGroup.addView(ViewGroup.java:5085)
	at com.brentvatne.exoplayer.ReactExoplayerView.addPlayerControl(ReactExoplayerView.java:545)
	at com.brentvatne.exoplayer.ReactExoplayerView.setControls(ReactExoplayerView.java:2419)
	at com.brentvatne.exoplayer.ReactExoplayerView.finishPlayerInitialization(ReactExoplayerView.java:981)
	at com.brentvatne.exoplayer.ReactExoplayerView.initializePlayerSource(ReactExoplayerView.java:975)
	at com.brentvatne.exoplayer.ReactExoplayerView.lambda$initializePlayer$9(ReactExoplayerView.java:783)
	at com.brentvatne.exoplayer.ReactExoplayerView.$r8$lambda$RBvrxfYCABPDk1GW_PBMyhbP7c4(Unknown Source:0)
	at com.brentvatne.exoplayer.ReactExoplayerView$$ExternalSyntheticLambda5.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
", "errorString": "java.lang.IndexOutOfBoundsException: index=1 count=0"}}

### Reproduction Link

repository link

### Reproduction

Step to reproduce this bug are: video uri full screen

**Comment by freeboub** [comment]
Is it possible to get a sample to reproduce the issue ?
