### ISSUE TITLE
[BUG]: "errorString": "ExoPlaybackException: ERROR_CODE_AUDIO_TRACK_INIT_FAILED"} in android

### ISSUE THREAD

**Issue by adilkhan2163** [TheWidlarzGroup/react-native-video#4329]
### Version

    "react-native": "0.76.3",     "react-native-video": "^6.8.2",

### What platforms are you having the problem on?

Android

### System Version

in all android devices

### On what device are you experiencing the issue?

Real device

### Architecture

New architecture with interop layer

### What happened?

A bug happened!
we are using react native video in flatlist when we scroll down (fastly or after some items even slowly) then these video that show this error shows blank screen and after that every video that render after that show blank screen.

Video error: {"error": {"errorCode": "25001", "errorException": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(2, null, null, audio/mp4a-latm, mp4a.40.5, 32027, und, [-1, -1, -1.0, null], [1, 44100]), format_supported=YES", "errorStackTrace": "androidx.media3.exoplayer.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(2, null, null, audio/mp4a-latm, mp4a.40.5, 32027, und, [-1, -1, -1.0, null], [1, 44100]), format_supported=YES
at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:623)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loopOnce(Looper.java:210)
at android.os.Looper.loop(Looper.java:299)
at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.exoplayer.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(44100, 12, 56576) Format(2, null, null, audio/raw, null, -1, und, [-1, -1, -1.0, null], [2, 44100])
at androidx.media3.exoplayer.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2198)
at androidx.media3.exoplayer.audio.DefaultAudioSink.buildAudioTrack(DefaultAudioSink.java:1067)
at androidx.media3.exoplayer.audio.DefaultAudioSink.buildAudioTrackWithRetry(DefaultAudioSink.java:1046)
at androidx.media3.exoplayer.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:825)
at androidx.media3.exoplayer.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:924)
at androidx.media3.exoplayer.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:744)
at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:2010)
at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:827)
at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1112)
at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:544)
... 4 more
Suppressed: androidx.media3.exoplayer.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(44100, 12, 56576) Format(2, null, null, audio/raw, null, -1, und, [-1, -1, -1.0, null], [2, 44100])
  ... 14 more
Caused by: java.lang.UnsupportedOperationException: Cannot create AudioTrack
  at android.media.AudioTrack$Builder.build(AudioTrack.java:1308)
  at androidx.media3.exoplayer.audio.DefaultAudioSink$Configuration.createAudioTrackV29(DefaultAudioSink.java:2245)
  at androidx.media3.exoplayer.audio.DefaultAudioSink$Configuration.createAudioTrack(DefaultAudioSink.java:2224)
  at androidx.media3.exoplayer.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2190)
  ... 13 more
Caused by: java.lang.UnsupportedOperationException: Cannot create AudioTrack
at android.media.AudioTrack$Builder.build(AudioTrack.java:1308)
at androidx.media3.exoplayer.audio.DefaultAudioSink$Configuration.createAudioTrackV29(DefaultAudioSink.java:2245)
at androidx.media3.exoplayer.audio.DefaultAudioSink$Configuration.createAudioTrack(DefaultAudioSink.java:2224)
at androidx.media3.exoplayer.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2190)
... 13 more
", "errorString": "ExoPlaybackException: ERROR_CODE_AUDIO_TRACK_INIT_FAILED"}, "target": 674}

we have tested this bug on old and new versions. But in both cases this error occur

### Reproduction Link

repository link

### Reproduction

Step to reproduce this bug are: 
we are using react native video in flatlist when we scroll down (fastly or after some items even slowly) then these video that show this error shows blank screen and after that every video that render after that show blank screen.

we have tested it on old and new react native versions

**Comment by freeboub** [comment]
I think you should limit the number of <Video views displayed in the same time to fix this issue

**Comment by im-alihashmi14** [comment]
@freeboub  I am also facing this issue when videos are mounted in a FlatList. As I scroll, the error starts occurring at some point. I am unmounting the videos and pausing them before unmounting, but the error still persists.

Could you elaborate on how I can properly free the resources of the video, such as releasing the audio and video resources? Unmounting alone doesn't seem to free them completely.

**Comment by piyushpathar** [comment]
error {"error":{"errorString":"ExoPlaybackException: ERROR_CODE_AUDIO_TRACK_INIT_FAILED","errorException":"androidx.media3.exoplayer.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(audio-high:ગુજરાતી, ગુજરાતી, null, audio/mp4a-latm, mp4a.40.2, -1, gu, [-1, -1, -1.0, null], [2, 48000]), format_supported=YES","errorCode":"25001","errorStackTrace":"androidx.media3.exoplayer.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(audio-high:ગુજરાતી, ગુજરાતી, null, audio/mp4a-latm, mp4a.40.2, -1, gu, [-1, -1, -1.0, null], [2, 48000]), format_supported=YES\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:640)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loopOnce(Looper.java:223)\n\tat android.os.Looper.loop(Looper.java:324)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: androidx.media3.exoplayer.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(48000, 12, 61504) Format(audio-high:ગુજરાતી, ગુજરાતી, null, audio/raw, null, -1, gu, [-1, -1, -1.0, null], [2, 48000])\n\tat androidx.media3.exoplayer.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2229)\n\tat androidx.media3.exoplayer.audio.DefaultAudioSink.buildAudioTrack(DefaultAudioSink.java:1070)\n\tat androidx.media3.exoplayer.audio.DefaultAudioSink.buildAudioTrackWithRetry(DefaultAudioSink.java:1049)\n\tat androidx.media3.exoplayer.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:828)\n\tat androidx.media3.exoplayer.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:927)\n\tat androidx.media3.exoplayer.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:773)\n\tat androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:2070)\n\tat androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:873)\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)\n\tat androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)\n\t... 4 more\n\tSuppressed: androidx.media3.exoplayer.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(48000, 12, 61504) Format(audio-high:ગુજરાતી, ગુજરાતી, null, audio/raw, null, -1, gu, [-1, -1, -1.0, null], [2, 48000])\n\t\t... 14 more\n\tCaused by: java.lang.UnsupportedOperationException: Cannot create AudioTrack\n\t\tat android.media.AudioTrack$Builder.build(AudioTrack.java:1390)\n\t\tat androidx.media3.exoplayer.audio.DefaultAudioSink$Configuration.createAudioTrackV29(DefaultAudioSink.java:2276)\n\t\tat androidx.media3.exoplayer.audio.DefaultAudioSink$Configuration.createAudioTrack(DefaultAudioSink.java:2255)\n\t\tat androidx.media3.exoplayer.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2221)\n\t\t... 13 more\nCaused by: java.lang.UnsupportedOperationException: Cannot create AudioTrack\n\tat android.media.AudioTrack$Builder.build(AudioTrack.java:1390)\n\tat androidx.media3.exoplayer.audio.DefaultAudioSink$Configuration.createAudioTrackV29(DefaultAudioSink.java:2276)\n\tat androidx.media3.exoplayer.audio.DefaultAudioSink$Configuration.createAudioTrack(DefaultAudioSink.java:2255)\n\tat androidx.media3.exoplayer.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2221)\n\t... 13 more\n"},"target":9992}
