### ISSUE TITLE
[BUG]: ExoPlaybackException: ERROR_CODE_DECODING_RESOURCES_RECLAIMED

### ISSUE THREAD

**Issue by quangtuan28200** [TheWidlarzGroup/react-native-video#4330]
### What happened?

Using React Native 0.74.3, when the video plays the player throws decoder errors. This started occurring in 6.8.2 (reportedly fine in earlier versions). The source is a local file with type `.m4v`, and the video source can change at runtime.

The errors happen occasionally and include `ERROR_CODE_DECODING_RESOURCES_RECLAIMED` (24006), a `MediaCodecVideoDecoderException` (`Decoder failed`), and an `ERROR_CODE_FAILED_RUNTIME_CHECK` (21004) `start failed` while seeking/setting media items.

**Error 1 — `ERROR_CODE_DECODING_RESOURCES_RECLAIMED` (24006):**

```
androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64002A, -1, null, [1920, 1080, 59.993782, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:640)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: c2.mtk.avc.decoder
	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1982)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:893)
	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1018)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
	... 4 more
Caused by: android.media.MediaCodec$CodecException: Error 0xffffffe0
```

**Error 2 — `MediaCodecVideoDecoderException` with `OMX.qcom.video.decoder.avc`:**

```
androidx.media3.exoplayer.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64002A, -1, null, [1920, 1080, 60.0, ColorInfo(BT709, Limited range, SDR SMPTE 170M, false, 8bit Luma, 8bit Chroma)], [-1, -1]), format_supported=YES
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:640)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:329)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: androidx.media3.exoplayer.video.MediaCodecVideoDecoderException: Decoder failed: OMX.qcom.video.decoder.avc
	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1982)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:893)
	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.render(MediaCodecVideoRenderer.java:1018)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1136)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:561)
	... 4 more
Caused by: android.media.MediaCodec$CodecException: Error 0xffffffe0
	at android.media.MediaCodec.releaseOutputBuffer(Native Method)
	at android.media.MediaCodec.releaseOutputBufferInternal(MediaCodec.java:3651)
	at android.media.MediaCodec.releaseOutputBuffer(MediaCodec.java:3625)
	at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.releaseOutputBuffer(AsynchronousMediaCodecAdapter.java:206)
	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.renderOutputBufferV21(MediaCodecVideoRenderer.java:1716)
	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.maybeReleaseFrame(MediaCodecVideoRenderer.java:1448)
	... (truncated)
```

**Error 3 — `ERROR_CODE_FAILED_RUNTIME_CHECK` (21004), `start failed`:**

```
androidx.media3.exoplayer.ExoPlaybackException: Unexpected runtime error
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:720)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:263)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.IllegalStateException: start failed
	at android.media.MediaCodec.native_start(Native Method)
	at android.media.MediaCodec.start(MediaCodec.java:2234)
	at androidx.media3.exoplayer.mediacodec.AsynchronousMediaCodecAdapter.flush(AsynchronousMediaCodecAdapter.java:249)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushCodec(MediaCodecRenderer.java:960)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.flushOrReleaseCodec(MediaCodecRenderer.java:953)
	at androidx.media3.exoplayer.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:780)
	at androidx.media3.exoplayer.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:794)
	at androidx.media3.exoplayer.BaseRenderer.disable(BaseRenderer.java:220)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:1846)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.seekToPeriodPosition(ExoPlayerImplInternal.java:1439)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.seekToPeriodPosition(ExoPlayerImplInternal.java:1403)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMediaSourceListInfoRefreshed(ExoPlayerImplInternal.java:2066)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.setMediaItemsInternal(ExoPlayerImplInternal.java:819)
	at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:598)
	... 3 more
```

**Component code:**

```jsx
<Video
	ref={videoRef}
	source={video}
	style={[styles.video, stance === 'southpaw' && { transform: [{ rotateY: '180deg' }] }]}
	playWhenInactive={true}
	playInBackground={true}
	ignoreSilentSwitch="ignore"
	mixWithOthers={ducking}
	paused={isPause}
	repeat={isLoop}
	volume={VOICE_VOLUME / 100}
	muted={isMute || isSilent}
	progressUpdateInterval={100}
	onLoadStart={_onLoadStart}
	onProgress={_onProgress}
	onEnd={onEnd}
	onReadyForDisplay={_onReadyForDisplay}
	onError={e => _onError(e.error)}
	disableFocus={true}
	viewType={ViewType.TEXTURE}
	shutterColor="transparent"
/>
```

![image](https://github.com/user-attachments/assets/e0ea8834-5742-49d5-a9e0-05722228479a)

### Steps to reproduce

1. Use react-native-video 6.8.2 on React Native 0.74.3 (Android, old architecture).
2. Render a `<Video>` component with `viewType={ViewType.TEXTURE}` playing a local `.m4v` (H.264/AVC 1920x1080 ~60fps) source.
3. Change the video source at runtime / let playback run on a real device.
4. Observe intermittent decoder failures: `ERROR_CODE_DECODING_RESOURCES_RECLAIMED` (24006), `MediaCodecVideoDecoderException`, and `start failed` / `ERROR_CODE_FAILED_RUNTIME_CHECK` (21004).

### react-native-video version

6.8.2

### react-native version

0.74.3

### Platforms

Android

### OS version

Android 14, Android 10, Android 13

### Device

Real device

### Architecture

Old Architecture

### Media / source type

Local file

**Comment by freeboub** [comment]
you should check this issue in android I think: https://github.com/androidx/media/issues/1825

**Comment by githistory** [comment]
For us, this seems to happen on Android only in recycled views such as FlashList / FlatList whose items can be destroyed but the underlying video player resources supporting those items are not.

**Comment by TWG-AI** [comment]
Thanks for the detailed error logs. The combination of `ERROR_CODE_DECODING_RESOURCES_RECLAIMED` and `FAILED_RUNTIME_CHECK` suggests codec resource contention — the system is taking back the decoder, and a race condition may be occurring when the source changes.

A few things worth trying:
1. **Test with the latest version** (6.19.2) — there have been ExoPlayer updates that improve codec lifecycle management.
2. **Check for multiple players competing for codec resources** — if your app has multiple video instances or another video-heavy app in the foreground, that could trigger reclamation.

This has been logged for the team.

> I'm an automated assistant — my suggestions are based on the error patterns; verify against your specific device and setup.
