### ISSUE TITLE
Crash when moving application to background on android

### ISSUE THREAD

**Issue by kennethlynne** [TheWidlarzGroup/react-native-video#456]
We render multiple videos in a list, and the app sometimes crashes with the following trace:
```
01-16 09:49:03.617: E/AndroidRuntime(15560): java.lang.RuntimeException: Unable to pause activity {com.edtechfoundry.differ/com.edtechfoundry.differ.MainActivity}: java.lang.IllegalStateException
01-16 09:49:03.617: E/AndroidRuntime(15560): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3408)
01-16 09:49:03.617: E/AndroidRuntime(15560): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3367)
01-16 09:49:03.617: E/AndroidRuntime(15560): 	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3342)
01-16 09:49:03.617: E/AndroidRuntime(15560): 	at android.app.ActivityThread.access$1100(ActivityThread.java:157)
01-16 09:49:03.617: E/AndroidRuntime(15560): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
01-16 09:49:03.617: E/AndroidRuntime(15560): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-16 09:49:03.617: E/AndroidRuntime(15560): 	at android.os.Looper.loop(Looper.java:148)
01-16 09:49:03.617: E/AndroidRuntime(15560): 	at android.app.ActivityThread.main(ActivityThread.java:5525)
01-16 09:49:03.617: E/AndroidRuntime(15560): 	at java.lang.reflect.Method.invoke(Native Method)
01-16 09:49:03.617: E/AndroidRuntime(15560): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
01-16 09:49:03.617: E/AndroidRuntime(15560): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
01-16 09:49:03.617: E/AndroidRuntime(15560): Caused by: java.lang.IllegalStateException
01-16 09:49:03.617: E/AndroidRuntime(15560): 	at android.media.MediaPlayer._pause(Native Method)
01-16 09:49:03.617: E/AndroidRuntime(15560): 	at android.media.MediaPlayer.pause(MediaPlayer.java:1250)
01-16 09:49:03.617: E/AndroidRuntime(15560): 	at com.brentvatne.react.ReactVideoView.onHostPause(ReactVideoView.java:504)
01-16 09:49:03.617: E/AndroidRuntime(15560): 	at com.facebook.react.bridge.ReactContext.onHostPause(ReactContext.java:179)
01-16 09:49:03.617: E/AndroidRuntime(15560): 	at com.facebook.react.XReactInstanceManagerImpl.moveToBeforeResumeLifecycleState(XReactInstanceManagerImpl.java:590)
01-16 09:49:03.617: E/AndroidRuntime(15560): 	at com.facebook.react.XReactInstanceManagerImpl.onHostPause(XReactInstanceManagerImpl.java:489)
01-16 09:49:03.617: E/AndroidRuntime(15560): 	at com.facebook.react.XReactInstanceManagerImpl.onHostPause(XReactInstanceManagerImpl.java:500)
01-16 09:49:03.617: E/AndroidRuntime(15560): 	at com.facebook.react.ReactActivityDelegate.onPause(ReactActivityDelegate.java:110)
01-16 09:49:03.617: E/AndroidRuntime(15560): 	at com.facebook.react.ReactActivity.onPause(ReactActivity.java:60)
01-16 09:49:03.617: E/AndroidRuntime(15560): 	at android.app.Activity.performPause(Activity.java:6383)
01-16 09:49:03.617: E/AndroidRuntime(15560): 	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1311)
01-16 09:49:03.617: E/AndroidRuntime(15560): 	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3394)
01-16 09:49:03.617: E/AndroidRuntime(15560): 	... 10 more
```

**Comment by mattapperson** [comment]
Please try the new 1.0 release. We moved to ExoPlayer and that should fix this issue for you
