### ISSUE TITLE
Unable to play on Android. Error while updating property 'src' of a view managed by: RCTVideo

### ISSUE THREAD

**Issue by qpowell** [TheWidlarzGroup/react-native-video#466]
My test app crashes immediately using the following code:

```javascript
import React, { Component } from 'react';
import { View, Text } from 'react-native';

import Video from 'react-native-video';

export default class VideoTest extends Component {
  render() {
    return (
      <View style={{ flex: 1, backgroundColor: '#f7f7f7', alignItems: 'center', paddingVertical: 32 }}>

      <Video
        source={{ uri: 'https://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4' }}
        ref={(ref) => { this.player = ref }}
        rate={1.0}
        style={{ width: 320, height: 180 }}
      />
        <View style={{ backgroundColor: '#29B6F6', padding: 16, marginTop: 32 }}>
          <Text onPress={() => this.player.presentFullscreenPlayer()} style={{ color: '#fff', fontWeight: '500' }}>
            Fullscreen
          </Text>
        </View>
      </View>
    )
  }
}
```

Using `react-native` 0.40 and the master branch for `react-native-video`:

```json
{
  "name": "VideoTest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "15.4.2",
    "react-native": "0.40.0",
    "react-native-video": "git+ssh://git@github.com/react-native-community/react-native-video.git#master"
  },
  "devDependencies": {
    "babel-jest": "18.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "18.1.0",
    "react-test-renderer": "15.4.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

I'm not sure if this is related or not, but I had an issue using this component in iOS as well due to the issue mentioned here: https://github.com/react-native-community/react-native-video/issues/449#issuecomment-272760480 .Is it possible that the `setSrc` issue needs to be addressed on both platforms?

**Comment by chatras** [comment]
I had similar problem with latest version of the library. Downgrading to an older version worked on iOS. Still having some problems with android, it only plays some mo4 vidoes.
{
  "dependencies": {
    "react-native-video": "github:react-native-community/react-native-video#9bcf70cbb513402622bc114f93da751c28f15303"
  }
}

**Comment by qpowell** [comment]
Running `adb logcat` gave me some additional info:

```
01-24 08:25:52.939 17007 17007 E unknown:ViewManager: Caused by: com.facebook.react.bridge.NoSuchKeyException: couldn't find key type in dynamic object
01-24 08:25:52.939 17007 17007 E unknown:ViewManager: 	at com.facebook.react.bridge.ReadableNativeMap.getString(Native Method)
01-24 08:25:52.939 17007 17007 E unknown:ViewManager: 	at com.brentvatne.react.ReactVideoViewManager.setSrc(ReactVideoViewManager.java:94)
01-24 08:25:52.939 17007 17007 E unknown:ViewManager: 	... 22 more
01-24 08:25:52.941 17007 17007 E unknown:React: Exception in native call
01-24 08:25:52.941 17007 17007 E unknown:React: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'src' of a view managed by: RCTVideo
01-24 08:25:52.941 17007 17007 E unknown:React: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:89)
01-24 08:25:52.941 17007 17007 E unknown:React: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:123)
01-24 08:25:52.941 17007 17007 E unknown:React: 	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:42)
01-24 08:25:52.941 17007 17007 E unknown:React: 	at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:36)
01-24 08:25:52.941 17007 17007 E unknown:React: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:227)
01-24 08:25:52.941 17007 17007 E unknown:React: 	at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
01-24 08:25:52.941 17007 17007 E unknown:React: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:890)
01-24 08:25:52.941 17007 17007 E unknown:React: 	at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:863)
01-24 08:25:52.941 17007 17007 E unknown:React: 	at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
01-24 08:25:52.941 17007 17007 E unknown:React: 	at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
01-24 08:25:52.941 17007 17007 E unknown:React: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:869)
01-24 08:25:52.941 17007 17007 E unknown:React: 	at android.view.Choreographer.doCallbacks(Choreographer.java:683)
01-24 08:25:52.941 17007 17007 E unknown:React: 	at android.view.Choreographer.doFrame(Choreographer.java:616)
01-24 08:25:52.941 17007 17007 E unknown:React: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
01-24 08:25:52.941 17007 17007 E unknown:React: 	at android.os.Handler.handleCallback(Handler.java:751)
01-24 08:25:52.941 17007 17007 E unknown:React: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-24 08:25:52.941 17007 17007 E unknown:React: 	at android.os.Looper.loop(Looper.java:154)
01-24 08:25:52.941 17007 17007 E unknown:React: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
01-24 08:25:52.941 17007 17007 E unknown:React: 	at java.lang.reflect.Method.invoke(Native Method)
01-24 08:25:52.941 17007 17007 E unknown:React: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
01-24 08:25:52.941 17007 17007 E unknown:React: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
01-24 08:25:52.941 17007 17007 E unknown:React: Caused by: java.lang.reflect.InvocationTargetException
01-24 08:25:52.941 17007 17007 E unknown:React: 	at java.lang.reflect.Method.invoke(Native Method)
01-24 08:25:52.941 17007 17007 E unknown:React: 	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:77)
01-24 08:25:52.941 17007 17007 E unknown:React: 	... 20 more
01-24 08:25:52.941 17007 17007 E unknown:React: Caused by: com.facebook.react.bridge.NoSuchKeyException: couldn't find key type in dynamic object
01-24 08:25:52.941 17007 17007 E unknown:React: 	at com.facebook.react.bridge.ReadableNativeMap.getString(Native Method)
01-24 08:25:52.941 17007 17007 E unknown:React: 	at com.brentvatne.react.ReactVideoViewManager.setSrc(ReactVideoViewManager.java:94)
01-24 08:25:52.941 17007 17007 E unknown:React: 	... 22 more
```

The `Caused by: com.facebook.react.bridge.NoSuchKeyException: couldn't find key type in dynamic object` caught my attention so I tried updating the source prop to: `{{ uri: 'https://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4', type: 'mp4' }}` and the video plays. My Fullscreen button doesn't change the player size, but I was able to use `this.player.seek(45)` and it works as intended. Any ideas?

**Comment by jhen0409** [comment]
I also have the same problem when I do [#429](https://github.com/react-native-community/react-native-video/pull/429#discussion_r95817460), you can try to set `type` in `source`, maybe it works for you.

**Comment by dmy3k** [comment]
I've encountered the same after upgrade from 0.9. It started working after I've cleaned previous builds
with `cd android && ./gradlew clean` and reset react native-cache with `npm start --reset-cache`.

**Comment by brunoda6** [comment]
i had the same problem i solve it by doing this:

**android/settings.gradle:**
use this one: `project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')` instead of `project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')`

**Comment by sauravexodus** [comment]
> i had the same problem i solve it by doing this:
> 
> **android/settings.gradle:**
> use this one: `project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')` instead of `project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')`

Thanks, it worked! Autolinking doesn't work unfortunately, you have to manually do this

**Comment by emothek** [comment]
You need to comment out all occurences of the following in the two files (ReactVideoView.java , ReactVideoViewManager.java) but on the react-native-video" package which is used to build this package "react-native-af-video-player" , as following :

```
//private ReadableMap mRequestHeaders = null;
...
public void setSrc(final String uriString, final String type, final boolean isNetwork, final boolean isAsset /, final ReadableMap requestHeaders/) {
setSrc(uriString, type, isNetwork, isAsset, /requestHeaders,/ 0, 0);
}

public void setSrc(final String uriString, final String type, final boolean isNetwork, final boolean isAsset, /*final ReadableMap requestHeaders,*/ final int expansionMainVersion, final int expansionPatchVersion) {

    mSrcUriString = uriString;
    mSrcType = type;
    mSrcIsNetwork = isNetwork;
    mSrcIsAsset = isAsset;
    //mRequestHeaders = requestHeaders;
    mMainVer = expansionMainVersion;
    mPatchVer = expansionPatchVersion;
.....

           /* if (mRequestHeaders != null) {
                headers.putAll(toStringMap(mRequestHeaders));
            }*/
.....

   // WritableMap wRequestHeaders = Arguments.createMap();
   // wRequestHeaders.merge(mRequestHeaders);

    src.putString(ReactVideoViewManager.PROP_SRC_URI, uriString);
    src.putString(ReactVideoViewManager.PROP_SRC_TYPE, type);
    //src.putMap(ReactVideoViewManager.PROP_SRC_HEADERS, wRequestHeaders);
....
@override
protected void onAttachedToWindow() {
super.onAttachedToWindow();

    if(mMainVer>0) {
        setSrc(mSrcUriString, mSrcType, mSrcIsNetwork, mSrcIsAsset, /*mRequestHeaders ,*/ mMainVer, mPatchVer);
    }
    else {
        setSrc(mSrcUriString, mSrcType, mSrcIsNetwork, mSrcIsAsset /*,mRequestHeaders*/);
    }
    setKeepScreenOn(true);
}
.....
```


and in ReactVideoViewManager.java :
`... //public static final String PROP_SRC_HEADERS = "requestHeaders"; .... //src.getMap(PROP_SRC_HEADERS), ....`

**Comment by shyamalVixplor** [comment]
> I also have the same problem when I do [#429](https://github.com/react-native-community/react-native-video/pull/429#discussion_r95817460), you can try to set `type` in `source`, maybe it works for you.

Worked!!
