### ISSUE TITLE
[Android] App crash when unmounting video

### ISSUE THREAD

**Issue by kfiroo** [TheWidlarzGroup/react-native-video#492]
Hey,
I have route with a `Video` component, when unmounting the route the app crashes with the following error.
Any ideas?

```
02-13 14:53:42.879  3774  3774 E AndroidRuntime: java.lang.IllegalStateException
02-13 14:53:42.879  3774  3774 E AndroidRuntime: 	at android.media.MediaPlayer.isPlaying(Native Method)
02-13 14:53:42.879  3774  3774 E AndroidRuntime: 	at com.yqritc.scalablevideoview.ScalableVideoView.isPlaying(ScalableVideoView.java:209)
02-13 14:53:42.879  3774  3774 E AndroidRuntime: 	at com.yqritc.scalablevideoview.ScalableVideoView.onDetachedFromWindow(ScalableVideoView.java:84)
02-13 14:53:42.879  3774  3774 E AndroidRuntime: 	at com.brentvatne.react.ReactVideoView.onDetachedFromWindow(ReactVideoView.java:524)
02-13 14:53:42.879  3774  3774 E AndroidRuntime: 	at android.view.View.dispatchDetachedFromWindow(View.java:14555)
02-13 14:53:42.879  3774  3774 E AndroidRuntime: 	at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:4789)
02-13 14:53:42.879  3774  3774 E AndroidRuntime: 	at android.view.ViewGroup.removeAllViews(ViewGroup.java:4735)
02-13 14:53:42.879  3774  3774 E AndroidRuntime: 	at com.facebook.react.views.view.ReactViewManager.removeAllViews(ReactViewManager.java:252)
02-13 14:53:42.879  3774  3774 E AndroidRuntime: 	at com.facebook.react.views.view.ReactViewManager.removeAllViews(ReactViewManager.java:41)
02-13 14:53:42.879  3774  3774 E AndroidRuntime: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:536)
02-13 14:53:42.879  3774  3774 E AndroidRuntime: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:533)
02-13 14:53:42.879  3774  3774 E AndroidRuntime: 	at com.facebook.react.uimanager.NativeViewHierarchyManager.dropView(NativeViewHierarchyManager.java:533)
02-13 14:53:42.879  3774  3774 E AndroidRuntime: 	at com.facebook.react.uimanager.NativeViewHierarchyManager$1.onAnimationEnd(NativeViewHierarchyManager.java:420)
02-13 14:53:42.879  3774  3774 E AndroidRuntime: 	at com.facebook.react.uimanager.layoutanimation.LayoutAnimationController$1.onAnimationEnd(LayoutAnimationController.java:131)
02-13 14:53:42.879  3774  3774 E AndroidRuntime: 	at android.view.animation.Animation$3.run(Animation.java:376)
02-13 14:53:42.879  3774  3774 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
02-13 14:53:42.879  3774  3774 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-13 14:53:42.879  3774  3774 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
02-13 14:53:42.879  3774  3774 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
02-13 14:53:42.879  3774  3774 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-13 14:53:42.879  3774  3774 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-13 14:53:42.879  3774  3774 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Thanks!

**Comment by kfiroo** [comment]
From what I could find in the docs:
```
IllegalStateException if the internal player engine has not been initialized or has been released.
```
My `Video` component is in a background route (i.e. there is a route on top of it) so maybe the video gets release when not visible and that causes the `isPlaying` to throw?

**Comment by kirillpisarev** [comment]
Just got the same error

Seems the error occurs only if a `Video` component is wrapped by a `View` component.

Case with the error raised while unmounting (`props.scene` is not in given values):
```
export default (props: Props) => {
    return props.scene === 'loginInit' || props.scene === 'loginApprove' ?
    (
        <View style={styles.wrapper}><Video {...props} /></View>
    ) : null
}
```

But without the wrapper all works fine:
```
export default (props: Props) => {
    return props.scene === 'loginInit' || props.scene === 'loginApprove' ?
    (
        <Video {...props} />
    ) : null
}
```

**Comment by kfiroo** [comment]
@MaFiaaaaAxD I couldn't remove the wrapping `View` in my case.
I ended up removing the video component manually when navigating away from the route, before the route is disposed

**Comment by kirillpisarev** [comment]
@kfiroo can you please provide an example of a "manual" component removing

**Comment by kfiroo** [comment]
@MaFiaaaaAxD I'll try to explain, 
I have the following routes `login`, `verification` and `main`.

The user starts at the `login` route which has the video in the background.

After he finishes the `login` the `verification` route is entered, so we have the following route stack [`login', 'verification`]. 
At this point the video is in a background route, which I suspect causes it to release the component.

When `verification` was successful the user is redirected to `main` route while clearing the route stack so the new stack is [`main`].

When my navigator is disposing of the `login` route, it tries to unmount the `Video` but it is already released, so calls to `isPlaying` result in `IllegalStateException`.

**My solution:** I have a state variable in `login` that is set to false when moving to `verification` and cases the video to not render
Something like this:
```jsx
{this.state.showVideo ? (
    <Video
        // ... video props
    />
) : null}
```

Hope that helps

**Comment by kirillpisarev** [comment]
@kfiroo Thanks for the explanation! I did something similar: instead of removing the whole component i remove only the `Video`

```
export default (props: Props) => {
    return (
        <View style={styles.videoContainer}>
            {(props.scene === 'loginInit' || props.scene === 'loginApprove') &&
                <Video {...props} />
            }
        </View>
    )
}
```

But still it's look like a temp workaround

**Comment by kfiroo** [comment]
@MaFiaaaaAxD yes, that's what I'm doing :)

I think the bug is with the integration between `react-native-video` and https://github.com/yqritc/Android-ScalableVideoView
