### ISSUE TITLE
[Android, Exoplayer] Loading a video that can't be decoded doesn't trigger `onError`

### ISSUE THREAD

**Issue by bramus** [TheWidlarzGroup/react-native-video#642]
Output from `adb logcat`, when loading a video on Android 5.1 that apparently can't decode said video:

````
D/ReactExoplayerView( 7384): onStateChanged: playWhenReady=true, playbackState=idle
D/ReactExoplayerView( 7384): onStateChanged: playWhenReady=true, playbackState=buffering
E/SoftAVC ( 7384): Decoder failed: -2
E/ACodec  ( 7384): [OMX.google.h264.decoder] ERROR(0x80001001)
E/ACodec  ( 7384): signalError(omxError 0x80001001, internalError -2147483648)
E/MediaCodec( 7384): Codec reported err 0x80001001, actionCode 0, while in state 6
E/ExoPlayerImplInternal( 7384): Internal runtime error.
E/ExoPlayerImplInternal( 7384): java.lang.IllegalStateException
E/ExoPlayerImplInternal( 7384):         at android.media.MediaCodec.native_queueInputBuffer(Native Method)
E/ExoPlayerImplInternal( 7384):         at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:831)
E/ExoPlayerImplInternal( 7384):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:675)
E/ExoPlayerImplInternal( 7384):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:490)
E/ExoPlayerImplInternal( 7384):         at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:464)
E/ExoPlayerImplInternal( 7384):         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
E/ExoPlayerImplInternal( 7384):         at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal( 7384):         at android.os.Looper.loop(Looper.java:135)
E/ExoPlayerImplInternal( 7384):         at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 7384):         at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
E/ExoPlayerImplInternal( 7384): Stop failed.
E/ExoPlayerImplInternal( 7384): java.lang.IllegalStateException
E/ExoPlayerImplInternal( 7384):         at android.media.MediaCodec.native_stop(Native Method)
E/ExoPlayerImplInternal( 7384):         at android.media.MediaCodec.stop(MediaCodec.java:628)
E/ExoPlayerImplInternal( 7384):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.releaseCodec(MediaCodecRenderer.java:450)
E/ExoPlayerImplInternal( 7384):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onDisabled(MediaCodecRenderer.java:405)
E/ExoPlayerImplInternal( 7384):         at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:278)
E/ExoPlayerImplInternal( 7384):         at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:145)
E/ExoPlayerImplInternal( 7384):         at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:673)
E/ExoPlayerImplInternal( 7384):         at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:648)
E/ExoPlayerImplInternal( 7384):         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:352)
E/ExoPlayerImplInternal( 7384):         at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal( 7384):         at android.os.Looper.loop(Looper.java:135)
E/ExoPlayerImplInternal( 7384):         at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 7384):         at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
D/ReactExoplayerView( 7384): onStateChanged: playWhenReady=true, playbackState=idle
````

`ReactExoplayerView` catches the ExoPlayer exception and changes the `playbackState` to `idle`.

For the implementer there's no proper way to catch this scenario, as the `onError` callback isn't triggered with this. Other events (e.g. `onProgress`/`onEnd`) also no longer get called, leaving one _“eventless”_, and thus in a stalled state.

**Comment by manask88** [comment]
I think this https://github.com/react-native-community/react-native-video/pull/799  will help you fix this issue.

**Comment by treemore** [comment]
yes , it is work .thank you .

**Comment by cobarx** [comment]
Fix included in the latest versions.
