### ISSUE TITLE
Android - app crashes when controls visible and activity is closed, when video just started playing

### ISSUE THREAD

**Issue by lucasromanojf** [TheWidlarzGroup/react-native-video#648]
Hi,

on Android, if my video component uses controls={true}, if I start playing the video and quickly close the activity where the video is (when the video just started playing) with the controls visibile, the app crashes. Here is the stack trace:

`java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.MediaPlayer.getCurrentPosition()' on a null object reference
                      at com.yqritc.scalablevideoview.ScalableVideoView.getCurrentPosition(ScalableVideoView.java:200)
                      at android.widget.MediaController.setProgress(MediaController.java:445)
                      at android.widget.MediaController.-wrap0(MediaController.java)
                      at android.widget.MediaController$3.handleMessage(MediaController.java:416)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

Please, can you help me?

**Comment by mactive** [comment]
the same problem on me

**Comment by Caundy** [comment]
Has anyone found a workaround for this aside from conditional rendering of this component (which causes the video to reload on reappearance)?
Experiencing the exact same issue using react-native-navigation when navigating to the next screen when controls are just about to show up initially.

**Comment by dharminderraja** [comment]
@Caundy can you explain with example how you used a workaround for this bug .. i tried multiple things but its still crashing.
Thank you

**Comment by TimP4w** [comment]
Any news about this? The Android-ScalableVideoView does not seem to be maintained at all (https://github.com/react-native-video/react-native-video/blob/master/android/build.gradle#L25)
