### ISSUE TITLE
Android Exoplayer Project Causes DexException

### ISSUE THREAD

**Issue by johndanek** [TheWidlarzGroup/react-native-video#692]
Whenever I try to integrate the `android-exoplayer` project into my React Native project, I can't perform a `./gradlew assembleDebug` which is required by `react-native run-android`

I get the following exception:

```
:app:compileDebugSources
:app:transformClassesWithDexForDebug
Running dex in-process requires build tools 23.0.2.
For faster builds update this project to use the latest build tools.
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/app/NavUtilsJB;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Landroid/support/v4/app/NavUtilsJB;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

:app:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.
```

Steps to reproduce:

1. Create a new React Native project `react-native init Foo`
2. Add `"react-native-video": "git://github.com/react-native-community/react-native-video.git#master"` to package.json `dependencies`
3. Add `compile project(':react-native-video-exoplayer')` to android/app/build.gradle
4. Add 
```
include ':react-native-video-exoplayer'
project(':react-native-video-exoplayer').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
```
to settings.gradle
5. Run `react-native run-android` and get exception.

What can be done to fix this?

**Comment by perttuim** [comment]
I managed to solve a similar issue by adding `compile 'com.android.support:support-v4:25.3.1'` in dependencies section of build.gradle. See: https://github.com/google/ExoPlayer/issues/2744#issuecomment-297858018.

**Comment by cobarx** [comment]
The fix from @perttuim fixed this for me. I'm not seeing this issue on 2.1.1 as we have upgraded ExoPlayer and apparently they fixed this.
