### ISSUE TITLE
Cannot run example project

### ISSUE THREAD

**Issue by RyanMitchellWilson** [TheWidlarzGroup/react-native-video#724]
I just got a brand new clone of this project, but whenever I try to run the packager for the example that is provided I get this error:
```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native-windows
  Paths: /Users/ryanwilson/temp/react-native-video/example/node_modules/react-native-windows/package.json collides with /Users/ryanwilson/temp/react-native-video/example/node_modules/react-native-video/node_modules/react-native-windows/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-windows
  Paths: /Users/ryanwilson/temp/react-native-video/example/node_modules/react-native-windows/package.json collides with /Users/ryanwilson/temp/react-native-video/example/node_modules/react-native-video/node_modules/react-native-windows/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/ryanwilson/temp/react-native-video/example/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:158:13)
    at p.getName.then.name (/Users/ryanwilson/temp/react-native-video/example/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:133:31)
```

And the packager fails to start which is not allowing me to run the example. Any idea on how to fix this?

Steps to reproduce:
`git clone https://github.com/react-native-community/react-native-video.git`
`cd react-native-video/example`
`npm install`
`react-native start`

Using:
npm: 4.4.1
node: 7.5.0

**Comment by RyanMitchellWilson** [comment]
If you don't care about windows-phone, you can just remove `react-native-windows` from the package.json dependencies and completely remove the devDependencies from your package.json and reinstall nodeModules you should be able to run the example now

**Comment by RyanMitchellWilson** [comment]
Closing this now since `react-native-windows` has been removed as a dependency
