### ISSUE TITLE
bundleRelease FAILED

### ISSUE THREAD

**Issue by sljuka** [TheWidlarzGroup/react-native-video#868]
Hey :)
I am getting an error while running `react-native run-android`. Looks like everything is passing except the bundle release. I assume the android bundle is not packaged correctly, but might be wrong.

This is the log:
```
Scanning folders for symlinks in /Users/sljukaa/projects/frontend/node_modules (22ms)
[1] Starting JS server...
[1] Building and installing the app on the device (cd android && ./gradlew installDebug)...
[1] Incremental java compilation is an incubating feature.
[1] :../../../../node_modules/react-native-video:preBuild UP-TO-DATE
[1] :../../../../node_modules/react-native-video:preReleaseBuild UP-TO-DATE
[1] :../../../../node_modules/react-native-video:checkReleaseManifest
[1] :../../../../node_modules/react-native-video:preDebugAndroidTestBuild UP-TO-DATE
[1] :../../../../node_modules/react-native-video:preDebugBuild UP-TO-DATE
[1] :../../../../node_modules/react-native-video:preDebugUnitTestBuild UP-TO-DATE
[1] :../../../../node_modules/react-native-video:preReleaseUnitTestBuild UP-TO-DATE
[1] :../../../../node_modules/react-native-video:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
[1] :../../../../node_modules/react-native-video:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
[1] :../../../../node_modules/react-native-video:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
[1] :../../../../node_modules/react-native-video:prepareComFacebookFrescoDrawee081Library UP-TO-DATE
[1] :../../../../node_modules/react-native-video:prepareComFacebookFrescoFbcore081Library UP-TO-DATE
[1] :../../../../node_modules/react-native-video:prepareComFacebookFrescoFresco081Library UP-TO-DATE
[1] :../../../../node_modules/react-native-video:prepareComFacebookFrescoImagepipeline081Library UP-TO-DATE
[1] :../../../../node_modules/react-native-video:prepareComFacebookFrescoImagepipelineOkhttp081Library UP-TO-DATE
[1] :../../../../node_modules/react-native-video:prepareComFacebookReactReactNative0201Library UP-TO-DATE
[1] :../../../../node_modules/react-native-video:prepareComYqritcAndroidScalablevideoview104Library UP-TO-DATE
[1] :../../../../node_modules/react-native-video:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
[1] :../../../../node_modules/react-native-video:prepareReleaseDependencies
[1] :../../../../node_modules/react-native-video:compileReleaseAidl UP-TO-DATE
[1] :../../../../node_modules/react-native-video:compileReleaseNdk UP-TO-DATE
[1] :../../../../node_modules/react-native-video:compileLint UP-TO-DATE
[1] :../../../../node_modules/react-native-video:copyReleaseLint UP-TO-DATE
[1] :../../../../node_modules/react-native-video:compileReleaseRenderscript UP-TO-DATE
[1] :../../../../node_modules/react-native-video:generateReleaseBuildConfig UP-TO-DATE
[1] :../../../../node_modules/react-native-video:generateReleaseResValues UP-TO-DATE
[1] :../../../../node_modules/react-native-video:generateReleaseResources UP-TO-DATE
[1] :../../../../node_modules/react-native-video:mergeReleaseResources UP-TO-DATE
[1] :../../../../node_modules/react-native-video:processReleaseManifest UP-TO-DATE
[1] :../../../../node_modules/react-native-video:processReleaseResources UP-TO-DATE
[1] :../../../../node_modules/react-native-video:generateReleaseSources UP-TO-DATE
[1] :../../../../node_modules/react-native-video:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
[1] :../../../../node_modules/react-native-video:compileReleaseJavaWithJavac UP-TO-DATE
[1] :../../../../node_modules/react-native-video:extractReleaseAnnotations UP-TO-DATE
[1] :../../../../node_modules/react-native-video:mergeReleaseShaders UP-TO-DATE
[1] :../../../../node_modules/react-native-video:compileReleaseShaders UP-TO-DATE
[1] :../../../../node_modules/react-native-video:generateReleaseAssets UP-TO-DATE
[1] :../../../../node_modules/react-native-video:mergeReleaseAssets UP-TO-DATE
[1] :../../../../node_modules/react-native-video:mergeReleaseProguardFiles UP-TO-DATE
[1] :../../../../node_modules/react-native-video:packageReleaseRenderscript UP-TO-DATE
[1] :../../../../node_modules/react-native-video:packageReleaseResources UP-TO-DATE
[1] :../../../../node_modules/react-native-video:processReleaseJavaRes UP-TO-DATE
[1] :../../../../node_modules/react-native-video:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
[1] :../../../../node_modules/react-native-video:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
[1] :../../../../node_modules/react-native-video:mergeReleaseJniLibFolders UP-TO-DATE
[1] :../../../../node_modules/react-native-video:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
[1] :../../../../node_modules/react-native-video:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
[1] :../../../../node_modules/react-native-video:bundleRelease FAILED
```

react: 16.1.1
react-native: 0.50.4
react-native-video: 2.0.0
Does somebody know how I can fix this?

EDIT:
This is the message from android-studio:
Error:Execution failed for task ':../../../../node_modules/react-native-video:bundleRelease'.
> Could not create ZIP '/Users/sljukaa/projects/frontend/node_modules/react-native-video/android/build/outputs/aar/../../../../node_modules/react-native-video-release.aar'.

**Comment by sljuka** [comment]
Managed to find out what is wrong but, not why it happened
running `./gradlew clean && ./gradlew assembleDebug --stacktrace` for more debug info I got:
```
$ ./gradlew assembleDebug --stacktrace
Incremental java compilation is an incubating feature.
:../../../../node_modules/react-native-video:preBuild UP-TO-DATE
:../../../../node_modules/react-native-video:preDebugBuild UP-TO-DATE
:../../../../node_modules/react-native-video:checkDebugManifest
:../../../../node_modules/react-native-video:preDebugAndroidTestBuild UP-TO-DATE
:../../../../node_modules/react-native-video:preDebugUnitTestBuild UP-TO-DATE
:../../../../node_modules/react-native-video:preReleaseBuild UP-TO-DATE
:../../../../node_modules/react-native-video:preReleaseUnitTestBuild UP-TO-DATE
:../../../../node_modules/react-native-video:prepareComAndroidSupportAppcompatV72301Library
:../../../../node_modules/react-native-video:prepareComAndroidSupportRecyclerviewV72301Library
:../../../../node_modules/react-native-video:prepareComAndroidSupportSupportV42301Library
:../../../../node_modules/react-native-video:prepareComFacebookFrescoDrawee081Library
:../../../../node_modules/react-native-video:prepareComFacebookFrescoFbcore081Library
:../../../../node_modules/react-native-video:prepareComFacebookFrescoFresco081Library
:../../../../node_modules/react-native-video:prepareComFacebookFrescoImagepipeline081Library
:../../../../node_modules/react-native-video:prepareComFacebookFrescoImagepipelineOkhttp081Library
:../../../../node_modules/react-native-video:prepareComFacebookReactReactNative0201Library
:../../../../node_modules/react-native-video:prepareComYqritcAndroidScalablevideoview104Library
:../../../../node_modules/react-native-video:prepareOrgWebkitAndroidJscR174650Library
:../../../../node_modules/react-native-video:prepareDebugDependencies
:../../../../node_modules/react-native-video:compileDebugAidl
:../../../../node_modules/react-native-video:compileDebugNdk UP-TO-DATE
:../../../../node_modules/react-native-video:compileLint
:../../../../node_modules/react-native-video:copyDebugLint UP-TO-DATE
:../../../../node_modules/react-native-video:compileDebugRenderscript
:../../../../node_modules/react-native-video:generateDebugBuildConfig
:../../../../node_modules/react-native-video:generateDebugResValues
:../../../../node_modules/react-native-video:generateDebugResources
:../../../../node_modules/react-native-video:mergeDebugResources
:../../../../node_modules/react-native-video:processDebugManifest
:../../../../node_modules/react-native-video:processDebugResources
:../../../../node_modules/react-native-video:generateDebugSources
:../../../../node_modules/react-native-video:incrementalDebugJavaCompilationSafeguard
:../../../../node_modules/react-native-video:compileDebugJavaWithJavac
:../../../../node_modules/react-native-video:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: /Users/sljukaa/projects/frontend/node_modules/react-native-video/android/src/main/java/com/brentvatne/react/ReactVideoViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:../../../../node_modules/react-native-video:extractDebugAnnotations
:../../../../node_modules/react-native-video:mergeDebugShaders
:../../../../node_modules/react-native-video:compileDebugShaders
:../../../../node_modules/react-native-video:generateDebugAssets
:../../../../node_modules/react-native-video:mergeDebugAssets
:../../../../node_modules/react-native-video:mergeDebugProguardFiles
:../../../../node_modules/react-native-video:packageDebugRenderscript UP-TO-DATE
:../../../../node_modules/react-native-video:packageDebugResources
:../../../../node_modules/react-native-video:processDebugJavaRes UP-TO-DATE
:../../../../node_modules/react-native-video:transformResourcesWithMergeJavaResForDebug
:../../../../node_modules/react-native-video:transformClassesAndResourcesWithSyncLibJarsForDebug
:../../../../node_modules/react-native-video:mergeDebugJniLibFolders
:../../../../node_modules/react-native-video:transformNative_libsWithMergeJniLibsForDebug
:../../../../node_modules/react-native-video:transformNative_libsWithSyncJniLibsForDebug
:../../../../node_modules/react-native-video:bundleDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':../../../../node_modules/react-native-video:bundleDebug'.
> Could not create ZIP '/Users/sljukaa/projects/frontend/node_modules/react-native-video/android/build/outputs/aar/../../../../node_modules/react-native-video-debug.aar'.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':../../../../node_modules/react-native-video:bundleDebug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:239)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:212)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:205)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.gradle.api.GradleException: Could not create ZIP '/Users/sljukaa/projects/frontend/node_modules/react-native-video/android/build/outputs/aar/../../../../node_modules/react-native-video-debug.aar'.
        at org.gradle.api.internal.file.archive.ZipCopyAction.execute(ZipCopyAction.java:58)
        at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator.execute(NormalizingCopyActionDecorator.java:52)
        at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator.execute(DuplicateHandlingCopyActionDecorator.java:42)
        at org.gradle.api.internal.file.copy.CopyActionExecuter.execute(CopyActionExecuter.java:38)
        at org.gradle.api.tasks.AbstractCopyTask.copy(AbstractCopyTask.java:83)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 60 more
Caused by: java.io.FileNotFoundException: /Users/sljukaa/projects/frontend/node_modules/react-native-video/android/build/outputs/aar/../../../../node_modules/react-native-video-debug.aar (No such file or directory)
        at org.apache.tools.zip.ZipOutputStream.<init>(ZipOutputStream.java:358)
        at org.gradle.api.internal.file.copy.DefaultZipCompressor.createArchiveOutputStream(DefaultZipCompressor.java:36)
        at org.gradle.api.internal.file.archive.ZipCopyAction.execute(ZipCopyAction.java:56)
        ... 72 more
```

The no such directory is `.../android/builds/outputs` this directory doesn't get created in build. I added it manually and the build passed. I am still not sure why this directory was not created by the build.

**Comment by sljuka** [comment]
Bad build path was generated for android durring linking because we have a bit unconventional project structure. Fixing the path in gradle fixed the issue.

**Comment by NiraliRadadiya** [comment]
> Bad build path was generated for android durring linking because we have a bit unconventional project structure. Fixing the path in gradle fixed the issue.

dfdsfa
