### ISSUE TITLE
403 on exoplayer

### ISSUE THREAD

**Issue by rogerkerse** [TheWidlarzGroup/react-native-video#904]
When stream url returns 403, then no callback is called. onError, etc. nothing.

On android logcat I can see error:
```
01-15 14:48:22.838 30855-1423/com.app E/ExoPlayerImplInternal: Source error.
                                                                  com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
                                                                      at com.google.android.exoplayer2.ext.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:165)
                                                                      at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:123)
                                                                      at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:102)
                                                                      at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:82)
                                                                      at com.google.android.exoplayer2.upstream.DataSourceInputStream.read(DataSourceInputStream.java:76)
                                                                      at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:123)
                                                                      at javax.crypto.CipherInputStream.read(CipherInputStream.java:249)
                                                                      at com.google.android.exoplayer2.source.hls.Aes128DataSource.read(Aes128DataSource.java:96)
                                                                      at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromDataSource(DefaultExtractorInput.java:257)
                                                                      at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:59)
                                                                      at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:221)
                                                                      at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:264)
                                                                      at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:200)
                                                                      at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:295)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                      at java.lang.Thread.run(Thread.java:764)
```

**Comment by p4vlos** [comment]
Did you manage to fix this issue?

**Comment by rogerkerse** [comment]
@cobarx the issue is not about "url" being a problem. Problem is that the component fails inside without triggering onError callback.

**Comment by rogerkerse** [comment]
but it seems with the newer versions of the player this error is fixed

**Comment by prashantAndroidApplify** [comment]
How to resolved this problem. i am facing this issues.
