### ISSUE TITLE
Android Nexus 5x & 6p: FATAL EXCEPTION: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/brentvatne/react/ReactVideoPackage

### ISSUE THREAD

**Issue by karthiganesan90** [TheWidlarzGroup/react-native-video#918]
Hi Team, 

We have set up everything on Android as the react-native-video documentation suggested, but we are getting the crash exception below on nexus 5x -android version 8.0 and 6p  - android version 7.0. 

` java.lang.NoClassDefFoundError: Failed resolution of: Lcom/brentvatne/react/ReactVideoPackage;
                                                       at com.bgmobilenga.MainApplication$1.getPackages(MainApplication.java:54)
                                                       at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:74)
                                                       at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:41)
                                                       at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:111)
                                                       at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:100)
                                                       at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:54)
                                                       at com.bgmobilenga.MainActivity.onCreate(MainActivity.java:26)
                                                       at android.app.Activity.performCreate(Activity.java:6679)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)`

Please help on this issue. Thanks.

**Comment by karthiganesan90** [comment]
Found the solution - just do clean gradle cache - `./gradlew clean`

Thanks.
