### ISSUE TITLE
<Android> Video doesn't load

### ISSUE THREAD

**Issue by RCTnativeapp** [TheWidlarzGroup/react-native-video#975]
Video is not loading in Android device:

  "react-native-video": "2.0.0",
    "react-native-video-controls": "2.0.1",

03-20 10:34:43.444 23748-23748/? E/MediaPlayer: isPlaying: called in state MEDIA_PLAYER_STATE_ERROR
03-20 10:35:02.614 3693-25025/? E/GenericSource: [application/octet-stream]
03-20 10:35:02.689 3693-25028/? E/GenericSource: [video/quicktime]
03-20 10:35:05.399 3693-25028/? E/GenericSource: Failed to init from data source!
03-20 10:35:05.399 23748-23926/? E/MediaPlayer: error (1, -2147483648)
03-20 10:35:05.404 23748-23748/? E/MediaPlayer: Error (1,-2147483648)
03-20 10:35:07.114 4122-4946/? E/Watchdog: !@Sync 1129 [03-20 10:35:07.123]

Any clue please.

**Comment by joebochill** [comment]
+1
Seeing the same issue using react-native version 0.52.0. Silently fails and does not render anything.

**Comment by VitaliiK91** [comment]
Same here. react-native 0.49.5 react-native-video 2.0.0

**Comment by joebochill** [comment]
I think my issue was with the Emulator. I got my hands on a real device and was able to get the videos to play. They still show up blank until you play them, unless you use the poster property though.

**Comment by cobarx** [comment]
@RCTnativeapp I'd suggest switching to using the ExoPlayer version and seeing if that fixes it. Also test with multiple devices, some devices don't have the right codecs installed to handle certain videos.

**Comment by ThisaraGitHub** [comment]
I have tested in Samsung s6 its works fine

**Comment by iagormoraes** [comment]
I tested an emulator with android 5 and the video is not playing. I have this logs:
EDIT: package is "react-native-video": "4.4.0"

```
02-20 10:13:51.947 1531-1700/system_process W/AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client
02-20 10:13:51.948 1185-1185/? E/AudioMixer: AudioMixer::getTrackName out of available tracks
02-20 10:13:51.948 1185-1185/? E/AudioFlinger: no more track names available
02-20 10:13:51.948 1185-1185/? E/AudioFlinger: createTrack_l() initCheck failed -12; no control block?
02-20 10:13:51.948 1531-1700/system_process E/AudioTrack: AudioFlinger could not create track, status: -12
02-20 10:13:51.949 1531-1700/system_process E/SoundPool: Error creating AudioTrack
02-20 10:13:51.952 18538-18538/com.app.video D/ReactExoplayerView: onStateChanged: playWhenReady=false, playbackState=buffering
02-20 10:13:54.663 18538-18855/com.app.video I/OMXClient: Using client-side OMX mux.
02-20 10:13:54.667 18538-18855/com.app.video E/OMXNodeInstance: OMX_GetExtensionIndex OMX.google.android.index.storeMetaDataInBuffers failed
02-20 10:13:54.667 18538-18855/com.app.video E/ACodec: [OMX.google.h264.decoder] storeMetaDataInBuffers failed w/ err -2147483648
02-20 10:13:54.673 18538-18858/com.app.video I/OMXClient: Using client-side OMX mux.
02-20 10:13:54.678 18538-18859/com.app.video I/SoftAAC2: limiting to stereo output
02-20 10:13:54.936 18538-18856/com.app.video E/SoftAVC: Decoder failed: -2
02-20 10:13:54.936 18538-18855/com.app.video E/ACodec: [OMX.google.h264.decoder] ERROR(0x80001001)
02-20 10:13:54.936 18538-18855/com.app.video E/ACodec: signalError(omxError 0x80001001, internalError -2147483648)
02-20 10:13:54.937 18538-18854/com.app.video E/MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 6
02-20 10:13:54.939 18538-18859/com.app.video I/SoftAAC2: Reconfiguring decoder: 0->48000 Hz, 0->2 channels
02-20 10:13:54.945 18538-18822/com.app.video E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
        at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1033)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1287)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:663)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:536)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:303)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
02-20 10:13:54.965 18538-18538/com.app.video D/ReactExoplayerView: onStateChanged: playWhenReady=false, playbackState=idle
02-20 10:13:57.395 18538-18634/com.app.video W/unknown:ReactNative: Calling JS function after bridge has been destroyed: RCTDeviceEventEmitter.emit(["websocketMessage",{"data":"#1","type":"text","id":1}])
```

**Comment by iagormoraes** [comment]
On android 6 emulator I got a crash with this logs:
EDIT: package is "react-native-video": "4.4.0"

```
02-20 10:19:38.654 1674-1674/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-20 10:19:38.654 1674-1674/? A/DEBUG: Build fingerprint: 'Android/sdk_google_phone_x86_64/generic_x86_64:6.0/MASTER/5056751:userdebug/test-keys'
02-20 10:19:38.654 1674-1674/? A/DEBUG: Revision: '0'
02-20 10:19:38.654 1674-1674/? A/DEBUG: ABI: 'x86'
02-20 10:19:38.654 1674-1674/? A/DEBUG: pid: 17287, tid: 17430, name: MediaCodec_loop  >>> com.app.video <<<
02-20 10:19:38.654 1674-1674/? A/DEBUG: signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xcc04a000
02-20 10:19:38.661 1674-1674/? A/DEBUG:     eax 00030c00  ebx ea207eb4  ecx 0000a300  edx ee53811c
02-20 10:19:38.661 1674-1674/? A/DEBUG:     esi ca0d5000  edi cc04a000
02-20 10:19:38.661 1674-1674/? A/DEBUG:     xcs 00000023  xds 0000002b  xes 0000002b  xfs 0000027f  xss 0000002b
02-20 10:19:38.661 1674-1674/? A/DEBUG:     eip ea201a38  ebp 003fffc4  esp cbb750b4  flags 00210206
02-20 10:19:38.662 1674-1674/? A/DEBUG: backtrace:
02-20 10:19:38.663 1674-1674/? A/DEBUG:     #00 pc 00002a38  /system/lib/libOpenglSystemCommon.so (goldfish_dma_write(goldfish_dma_context*, void*, unsigned int)+56)
02-20 10:19:38.663 1674-1674/? A/DEBUG:     #01 pc 00003853  /system/lib/libOpenglSystemCommon.so (ExtendedRCEncoderContext::lockAndWriteDma(void*, unsigned int)+67)
02-20 10:19:38.663 1674-1674/? A/DEBUG:     #02 pc 00003062  /system/lib/lib_renderControl_enc.so
02-20 10:19:38.663 1674-1674/? A/DEBUG:     #03 pc 0000314e  /system/lib/hw/gralloc.ranchu.so
02-20 10:19:38.663 1674-1674/? A/DEBUG:     #04 pc 00009e67  /system/lib/libui.so (android::GraphicBufferMapper::unlock(native_handle const*)+71)
02-20 10:19:38.663 1674-1674/? A/DEBUG:     #05 pc 0012987d  /system/lib/libstagefright.so (android::SoftwareRenderer::render(void const*, unsigned int, long long, long long, void*, android::sp<android::AMessage> const&)+813)
02-20 10:19:38.663 1674-1674/? A/DEBUG:     #06 pc 000dec7e  /system/lib/libstagefright.so (android::MediaCodec::onReleaseOutputBuffer(android::sp<android::AMessage> const&)+670)
02-20 10:19:38.663 1674-1674/? A/DEBUG:     #07 pc 000da678  /system/lib/libstagefright.so (android::MediaCodec::onMessageReceived(android::sp<android::AMessage> const&)+6920)
02-20 10:19:38.663 1674-1674/? A/DEBUG:     #08 pc 0000c9b9  /system/lib/libstagefright_foundation.so (android::AHandler::deliverMessage(android::sp<android::AMessage> const&)+41)
02-20 10:19:38.663 1674-1674/? A/DEBUG:     #09 pc 00010ed2  /system/lib/libstagefright_foundation.so (android::AMessage::deliver()+114)
02-20 10:19:38.663 1674-1674/? A/DEBUG:     #10 pc 0000ddef  /system/lib/libstagefright_foundation.so (android::ALooper::loop()+463)
02-20 10:19:38.663 1674-1674/? A/DEBUG:     #11 pc 0000e7a3  /system/lib/libstagefright_foundation.so (android::ALooper::LooperThread::threadLoop()+35)
02-20 10:19:38.663 1674-1674/? A/DEBUG:     #12 pc 00014aac  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+418)
02-20 10:19:38.663 1674-1674/? A/DEBUG:     #13 pc 0006bfae  /system/lib/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+98)
02-20 10:19:38.663 1674-1674/? A/DEBUG:     #14 pc 000141cf  /system/lib/libutils.so (thread_data_t::trampoline(thread_data_t const*)+122)
02-20 10:19:38.663 1674-1674/? A/DEBUG:     #15 pc 00081923  /system/lib/libc.so (__pthread_start(void*)+56)
02-20 10:19:38.663 1674-1674/? A/DEBUG:     #16 pc 000227f2  /system/lib/libc.so (__start_thread+25)
02-20 10:19:38.663 1674-1674/? A/DEBUG:     #17 pc 000170b6  /system/lib/libc.so (__bionic_clone+70)
02-20 10:19:38.851 1674-1674/? A/DEBUG: Tombstone written to: /data/tombstones/tombstone_02
02-20 10:19:38.851 1674-1674/? E/DEBUG: AM write failed: Broken pipe
02-20 10:19:38.851 1956-17480/system_process W/ActivityManager:   Force finishing activity com.app.video/com.app.video.MainActivity
02-20 10:19:38.851 1956-1973/system_process I/BootReceiver: Copying /data/tombstones/tombstone_02 to DropBox (SYSTEM_TOMBSTONE)
```

**Comment by carltian** [comment]
the same issue

react-native 0.63.2
react-native-video: ^5.1.0-alpha8,

component usage

`<Video
            key={uri}
            ref={this.videoInstance}
            paused={videoPaused}
            posterResizeMode="cover"
            poster={uri}
            resizeMode="cover"
            onLoad={() => {}}
            onEnd={this.afterEndVideo}
            style={this.styles.Image}
            source={{ uri }}
          />`

`2021-07-15 17:42:53.507 11593-13095/com.surveyapp E/MediaPlayerNative: error (1, -2147483648)
2021-07-15 17:42:53.507 11593-13095/com.surveyapp D/MediaPlayerNative: [notify] : [1170] callback app listenerNotNull=1, send=1
2021-07-15 17:42:53.508 11593-11593/com.surveyapp E/MediaPlayer: Error (1,-2147483648)
2021-07-15 17:42:53.509 11593-11593/com.surveyapp V/PlayerBase: baseStop() piid=10839`
